### ISSUE TITLE
Application API Response

### ISSUE THREAD

**Issue by f0rever-johnson** [FusionAuth/fusionauth-issues#10]
Why is there a difference between the Application object when retrieving one Application vs. retrieving all.

"One Application"
![screen shot 2018-10-22 at 10 09 44 pm](https://user-images.githubusercontent.com/21150708/47330817-9b389980-d647-11e8-8fb1-4305448b3d4e.png)

"All the Applications"
![screen shot 2018-10-22 at 10 09 34 pm](https://user-images.githubusercontent.com/21150708/47330818-9b389980-d647-11e8-8561-21c2171f45ea.png)

**Comment by robotdan** [comment]
Good eye, that was not intentional, it was just missing from the example JSON response. 

Fixed under commit https://github.com/FusionAuth/fusionauth-site/commit/93681d8d07051c785f001cf4dff948e50cb5e370

https://fusionauth.io/docs/v1/tech/apis/applications#retrieve-an-application

Thanks @f0rever-johnson much appreciated.
