### ISSUE TITLE
Breach detection causes user confusing issues with generic connector

### ISSUE THREAD

**Issue by ckolbeck-streem** [FusionAuth/fusionauth-issues#1020]
### Description

When a user logs in through FusionAuth for the first time and a request is dispatched through a configured connector, the strength of the provided password isn't checked until the the connector returns a 200. If breach detection is enabled and the password is weak, the FusionAuth user creation will fail with a message in the logs, but no indication to the user what happened. Instead they'll see a simple "Invalid Credentials" message.

Ideally I believe they would be created and put into a force-password-reset state.

**Comment by robotdan** [comment]
Possibly related to https://github.com/FusionAuth/fusionauth-issues/issues/895, or at a minimum we should review these together if we are in this part of the code.

**Comment by robotdan** [comment]
In this case, since the password is being managed by the connector, perhaps FusionAuth should not be doing any validation on the password, breach detection, constraint validation, etc. 

We could fix this and put up the correct error to the end user, but there is nothing for FusionAuth to do about since are not managing the user. In general, the reason we sort of bury the validation error during this create path is because we expect it to be a development time issue. In other words, the lambda (LDAP connector) or the Generic Connector response - didn't provide enough information to create the user in FusionAuth. 

The password piece doesn't fit into that category of dev time issue, and we can't tell the user how to change their password. So, we could skip this validation - or perhaps we still do the breach validation, but we only mark their account as using a breached password but not fail login. 

Any thoughts @ckolbeck-streem  - what would you expect, or what would you see as the ideal behavior here? 

@voidmain @mooreds any thoughts on this?

**Comment by mooreds** [comment]
It seems like what you are proposing is:

* if they are migrating users, continue to check for breached passwords
* if they are not, but using LDAP as the backend, don't check for breached passwords (or, at most, check but take no action)

This seems to make sense. Breached password detection should only apply where FusionAuth is the system of record for passwords, because that is where we can reliably provide the user with a path to fix it. If, somehow, we could check passwords of someone using any of the identity providers, we wouldn't want to do that, for the same reason.

**Comment by ckolbeck-streem** [comment]
In our case the connector is being used to migrate users off an existing system and into FusionAuth, after which FA will be the system of record. I think @robotdan's suggestion of creating the user, then forcing a password change on next login makes the most sense to me (if I understand right).

**Comment by ckolbeck-streem** [comment]
We're now seeing a similar issue caused by password complexity checks. It makes sense to me to employ a similar approach there if possible.
