### ISSUE TITLE
IP Addresses displayed as the same for multiple nodes in clustered setup

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1030]
### Description 
 IP Addresses displayed as the same for clustered nodes

### Affects versions
not sure.

### Steps to reproduce

1. Add two nodes to the system.
1. See they are shown being on the same address if you navigate to "System" and then "About".
1. If you reload the page and switch the active node responding to the request, all the ip addresses will be switched to the new value.

Note that the event log shows that the nodes are on different ip addresses (see forum post).

### Expected behavior

Different IP addresses displayed, since, well, the nodes are on different IP addresses.

### Screenshots

![node2](https://user-images.githubusercontent.com/91825/103327687-d0548980-4a12-11eb-8ebb-f3805f80f02e.png)
![node3](https://user-images.githubusercontent.com/91825/103327688-d0ed2000-4a12-11eb-9938-186cd56fc329.png)

### Platform

Deployed on kubernetes and replicated on AWS ec2 instances behind an nginx loadbalancer.

### Additional context

Came out of this forum post: https://fusionauth.io/community/forum/topic/536/multiple-nodes-sharing-ip-address

Per https://github.com/FusionAuth/fusionauth-issues/issues/1030#issuecomment-752685173 the IP is for display purposes only and doesn't affect functionality. All other information in the node details is correct.

**Comment by robotdan** [comment]
I don't know that this is a bug. If the host reports the same IP address, then that is what will be displayed.

Can the user that reported this bug provide details as to what they would expect to see based upon the underlying host? 

All we are doing is asking `NetworkInterface.getNetworkInterfaces` for the available interfaces, and looking for something that is up and not loopback. 

I would assume this is how Java is getting network details from K8s, or something like that.

**Comment by mooreds** [comment]
But in the event log, the IP addresses are different for each node?

See https://fusionauth.io/community/forum/topic/536/multiple-nodes-sharing-ip-address?_=1607606859190

Is that a different code path? Or are those different IP addresses than reported in the UI?

**Comment by robotdan** [comment]
The node address shown in the screenshot, and printed to the log is the value defined by `fusionauth-app.url` and `fusionauth-app.http.port`. 

The port will default to `9011` unless otherwise configured, and the value for `fusionauth-app.url` will be calculated at startup if not configured. This may be a hostname or an IP address depending upon the configuration. 

This is the URL that FusionAuth will use to communicate between nodes. We basically guess, we look for a site local address of some sort, and if we can't find a site local address, we fall back to `localhost`. 

If we have more than one possible site local address, we pick the "first" value that begins with `en`. 

The list of IPs shown in the About page in theory would be a super set of the value assigned to the node since it would contain any site local IPs and non site-local IPs. 

It is possible that if the underlying container assigns multiple IPs to the loopback interface they would not show up in the about dialog since we omit the loop interface when collecting the IP addresses. 

If we wanted to set up a k8s cluster and recreate we could confirm how these addresses are reported from the host through k8s to the JVM. This would be super low priority for me.

**Comment by mooreds** [comment]
I actually see this when standing up a two or three node cluster in AWS (with no k8s involved at all). I have a load balancer in front of three nodes and the address that is shown for all three nodes is the internal ip address of the ec2 instance that is responding to the request.

For node2, the address of that node is 10.0.0.7 and for node 3 it is 10.0.0.13. So when I am viewing the about page and node2 is responding to the request, all three nodes are shown as being on 10.0.0.7. When I am viewing the about page and node3 is responding, all three nodes are shown as 10.0.0.13. A reload on the about page sometimes flips around the IP addresses. 

See the following images:

![node3](https://user-images.githubusercontent.com/91825/103327600-75bb2d80-4a12-11eb-89a2-fb56465f440a.png)
![node2](https://user-images.githubusercontent.com/91825/103327602-75bb2d80-4a12-11eb-92c6-51141d49246a.png)

This is confusing.

**Comment by robotdan** [comment]
Looks like we need to store this info instead of retrieving it dynamically to ensure we get the correct value. As stated earlier, this info is for display purposes only and is not relate to any inter node communication in the cluster.
