### ISSUE TITLE
Twitter IdP accept access tokens

### ISSUE THREAD

**Issue by johnmaia** [FusionAuth/fusionauth-issues#1073]
### Problem
Our authentication flow requires that we access the user details before calling FusionAuth to register/authenticate it. To do so we need to exchange the request tokens for access tokens to retrieve the user details from Twitter. Unfortunately, because FusionAuth's current Twitter authentication flow only accepts request tokens, and because we've already exchanged them for access tokens, by the time that we call FA the request tokens are invalid. 

### Solution
FusionAuth should also accept access tokens. I would suggest that, in order to not break the current implementation, the `oauth_verifier` should no longer be a required parameter and it should be used as a "flag" parameter. 

**Example**:

- If `oauth_verifier` is given then the `oauth_token` and `oauth_token_secret` should be considered as request tokens.
- If `oauth_verifier` is not given then the `oauth_token` and `oauth_token_secret` should be considered as access tokens.

### Alternatives/workarounds
I haven't found a workaround.

### Additional context
https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens
https://oauth.net/core/1.0/#anchor9

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
To clarify, you are not using the FusionAuth login page for the Twitter login, and you are doing something like:

1. Redirect to Twitter, user logs in
2. You consume the Twitter response and make a request to the Twitter `/oauth/request_token` endpoint to get a `oauth_token`. 
3. You use this token to get user details, and then you want to be able to call the `/api/identity-provider/login` API to complete the Twitter login. However because you have already exchanged the `oauth_token` for an `access_token`, this request fails because the first thing we do is attempt to exchange the `oauth_token` for an `access_token` so we can collect user details and merge the user into FusionAuth. 

And your ideal is for the Login API to optionally take an `access_token` instead of the `oauth_token` so that we can skip the exchange and just use the already obtained `access_token`. 

Does that sound correct?

**Comment by johnmaia** [comment]
Yes, that's correct.

**Comment by robotdan** [comment]
Accepted PR https://github.com/FusionAuth/fusionauth-api/pull/12

**Comment by robotdan** [comment]
@johnmaia let us know if this one works for you now - once you get a chance to test it out.
