### ISSUE TITLE
[missing] Your request is missing a JSON body

### ISSUE THREAD

**Issue by kounelios13** [FusionAuth/fusionauth-issues#11]
Hello.I have setup a fusion auth server on port 9011.

I have created a user with default tenant

I am trying to use postman to login.
I send a post request to `localhost:9011/api/login`
In the body I pass the `loginId` and the password however when I press send I get the above error.

Any ideas how this could be solved?

**Comment by dseller** [comment]
Did you set the Content-Type header?

**Comment by robotdan** [comment]
Thanks @dseller this is likely the issue. 

Any of our APIs that take a JSON request body will require the correct `Content-Type` HTTP header. 
If Postman doesn't have an JSON body option, then you'll need to manually add the following HTTP header.

`Content-Type: application/json`

Let me know if that resolves your issue.

**Comment by robotdan** [comment]
I added a note on our API overview regarding the correct `Content-Type` to avoid confusion. 
https://fusionauth.io/docs/v1/tech/apis/

**Comment by kounelios13** [comment]
I won't be able to test  it till Friday probably.Once tested I will come back for updates

**Comment by kounelios13** [comment]
Hey I tried that but still getting the same error.Here are a couple of screenshots I took
![2](https://user-images.githubusercontent.com/11466138/47546893-ec70b380-d8fb-11e8-8259-c7e441217971.PNG)
![1](https://user-images.githubusercontent.com/11466138/47546894-ec70b380-d8fb-11e8-8c0c-898a00b9361b.PNG)

Is there anything wrong with what I am doing?

**Comment by voidmain** [comment]
It looks like you have “form-data” select for your request body. That should be JSON. 

I don’t use Postman, but I’m assuming it has an option for a JSON request body. Then just copy and paste the JSON format from the FusionAuth docs here: https://fusionauth.io/docs/v1/tech/apis/login

**Comment by robotdan** [comment]
Hi @kounelios13 to add to what @voidmain mentioned - since you have selected `form-data`, Postman will likely add the `Content-Type` header on your behalf and it won't be `application/json`. 

Instead, select `raw` while you have the `Body` tab selected, and then you'll see a drop down to the right of the radio buttons where you can select `JSON (application/json)`. Doing this will cause Postman to add the correct `Content-Type` header to the request. 

As @voidmain mentioned, in addition to setting up Postman to use the correct HTTP header, you will also need to send JSON instead of key value pairs as you have in the screen shot. 

See the following screenshot for an example. 

<img width="710" alt="screen shot 2018-10-27 at 8 38 44 pm" src="https://user-images.githubusercontent.com/1148709/47611329-7ddd4400-da28-11e8-8f0e-1d053a70165f.png">

And notice the `Content-Type` header that Postman added once I selected `raw` and `JSON (application/json)`. 
<img width="622" alt="screen shot 2018-10-27 at 8 38 51 pm" src="https://user-images.githubusercontent.com/1148709/47611330-7fa70780-da28-11e8-88cd-e40d3920cbc6.png">

Hope that helps.

**Comment by robotdan** [comment]
Please reopen if you're still having this issue. Thanks.

**Comment by emadbaqeri** [comment]
I have the same issue, anyone has the solution?

**Comment by mooreds** [comment]
@emadbaqeri this is a good topic for the community forum: https://fusionauth.io/community/forum/

**Comment by emadbaqeri** [comment]
> @emadbaqeri this is a good topic for the community forum: https://fusionauth.io/community/forum/

@mooreds thank you, that was helpful, I just worked around this and fixed
