### ISSUE TITLE
Have login.success webhook only fired when user and registration are complete objects

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1130]
### Problem

Have login.success webhook only fired when user and registration are complete objects. Currently, if the user is authenticated via a remote IdP for the first time, the login.success event has registration data in it that is stale. If an API call is made against that registration data (to update roles, for example), it fails with a 404.

The roles need to be modified because they are used to generate a correct JWT, which happens right after login.

(This is from a customer bug report).

### Solution

Don't send the login.success event unless the user and registration objects contained therein are available for other API calls.

### Alternatives/workarounds

Build your system so you can re-issue the JWT, or pre-create the user, or put the logic you would have in the webhook into a lambda (oh, for [issue 267](https://github.com/FusionAuth/fusionauth-issues/issues/267) to be done :) ).

### Additional context

Related:

- https://github.com/FusionAuth/fusionauth-issues/issues/1128
- https://github.com/FusionAuth/fusionauth-issues/issues/1129

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by spwitt** [comment]
Internal
- https://github.com/FusionAuth/fusionauth-app/pull/302

**Comment by spwitt** [comment]
Some notes from reviewing this bug:
* The 404 `/api/user/registration` response given as an example in the description has been resolved by an earlier fix to better manage database transactions
* I am adding tests to confirm that it is possible to modify the user's registration (e.g. adding roles) via the API from a `user.login.success` webhook
* However, the login response and JWT will _not_ contain user or registration data modified by the webhook

Including data on the initial response would require fetching the record from the database after each webhook call on the off chance that the response for the current API call is outdated. In this particular case there are a few alternatives:
* Modify the user or registration as part of a lambda rather than a webhook (this was not an option at the time this issue was created)
* Update the webhook handler code to consume the API response containing updated information
* Immediately refresh the JWT to get updated user/registration info

**Comment by robotdan** [comment]
No functional changes. Tests were added to assert the desired behavior.
