### ISSUE TITLE
Impossible to install/update due to major issue about internal file

### ISSUE THREAD

**Issue by sycured** [FusionAuth/fusionauth-issues#1150]
After updating FusionAuth to 1.25.0, I obtain

```
java.nio.file.NoSuchFileException: /usr/local/fusionauth/fusionauth-app/web/WEB-INF/lib/inversoft-tools-0.29.0.jar
```

Effectively, it's not the right version, the installed is **inversoft-tools-0.29.3.jar** not 0.29.0

**Comment by voidmain** [comment]
Thanks for the report. We'll need some more info in order to determine what is happening. Here's a quick list that will help:

* What deployment method are you using?
* What is the operating system?
* The full logs from the system
* A file listing of your installation directory that includes permissions

That information will definitely help point us in the right direction.

**Comment by sycured** [comment]
RPM install using dnf from 1.19.x on Oracle Linux.

The problem is the same on clean install… so you can reproduce it very easily.

**Comment by robotdan** [comment]
Thanks for the update, if you'd like further assistance please add all of the details that @voidmain requested otherwise we don't have enough to go on.

**Comment by sycured** [comment]
I need to maintain an existing fusionauth, planned to be decommissioned Q4 2021/Q1 2022 after moving to the new solution.

You can find my personal test instance (SELinux enforced) on: https://fusion.sycured.com
The listing: [ls.txt](https://github.com/FusionAuth/fusionauth-issues/files/6186707/ls.txt)

Full logs from the system, it's a joke or will you pay the bandwidth… it's GB of data if you want the entire system. As you can see in the listing, I've no file on /usr/local/fusionauth/logs and nothing inside /var/log and journalctl that can help you.

**Comment by voidmain** [comment]
Sorry, I should have clarified that I need the files in `/usr/local/fusionauth/logs` as well as the system journal, not the entire operating system.

That being said, this appears to be a support issue and not an issue with FusionAuth because you don't appear to have any log files. Usually this means that the installation is broken. We have a lot of people using version 1.25.0 successfully on Linux and I'm guessing this is an installation or configuration issue. Our primary login page (login.fusionauth.io) is currently running version 1.25.0 using Linux and it works fine. We installed there using Debian packages and have log files in `/usr/local/fusionauth/logs`.

If you have a support plan, please log into your account and open a support ticket there. If you don't have a support plan, you can post this to the forums and see if a community member can assist you. You can also purchase a support plan if you need further assistance and we'd be happy to help you debug the installation.

**Comment by sycured** [comment]
@voidmain you are talking about Debian when I told you that I'm using Oracle Linux which is a Red Hat Enterprise Linux recompiled from source like CentOS… it's a lot more different, I use your RPM package not the DEB package.

Thank you, you're confirming the right way that we're doing: moving out of fusionauth.

**Comment by voidmain** [comment]
@sycured - We need a lot of information in order to debug these issues and determine if they are bugs in FusionAuth or not. We also test against many variants of Linux (including CentOS) and have hundreds of customers doing the same all the time. RPMs are supported but your system might be configured in a way that causes applications like FusionAuth not to function properly. 

For example, the Linux security subsystem might reject file read requests from unprivileged users in the `/usr/local` file system. This is not a bug with FusionAuth, this is a configuration issue that you would need to fix.

Given the information you have provided up to this point, this did not look like a FusionAuth bug and therefore it isn't something we can fix in the core product. 

If you had a support contract in place, we would be able to provide additional support to help track this down. Without a support contract, there isn't much we can do though. This is the same with other products that have the similar support model to FusionAuth (i.e. MySQL or PostgreSQL).

I'm sorry to hear that you will be moving away from FusionAuth. Best of luck!

**Comment by sycured** [comment]
If you're not compliant with system using SELinux, it's not my problem…
Actually, I've no AVC for fusionauth so it's the end about using this solution.

**Comment by voidmain** [comment]
In case anyone else finds this issue, I want to close the loop on this conversation. FusionAuth works perfectly under SELinux, Redhat EL, and Oracle Linux. I ran a test this morning to be certain we didn't have any problems and everything worked really well.

Here are the steps I took and some screenshots:

1. I created a new Oracle Linux 8 instance
2. I uploaded the RPM package for `fusionauth-app` version 1.25.0 (technically it was a build from `master` that will soon become `1.26.0` but nothing has changed in our RPMs)
3. I installed the package using `rpm -i`
4. I installed PostgreSQL server on the server
5. I configured PostgreSQL server to allow localhost connections using the `md5` authentication mechanism
6. Used setup wizard to complete the install

Here are some screenshots of this process as well as a terminal that shows the version of Linux I'm on, FusionAuth running, and that FusionAuth has correct created a log file in `/usr/local/fusionauth/logs`.

<img width="1337" alt="Screen Shot 2021-03-24 at 8 01 29 AM" src="https://user-images.githubusercontent.com/377102/112325311-2e42e700-8c79-11eb-850b-27dee0df0fa4.png">
<img width="1337" alt="Screen Shot 2021-03-24 at 8 10 01 AM" src="https://user-images.githubusercontent.com/377102/112325315-2f741400-8c79-11eb-9967-e31b61638e27.png">
<img width="1337" alt="Screen Shot 2021-03-24 at 8 10 08 AM" src="https://user-images.githubusercontent.com/377102/112325317-300caa80-8c79-11eb-82c9-8d77e6bf32d6.png">
<img width="1337" alt="Screen Shot 2021-03-24 at 8 10 26 AM" src="https://user-images.githubusercontent.com/377102/112325318-300caa80-8c79-11eb-9ba7-dccff16b32f6.png">
<img width="1179" alt="Screen Shot 2021-03-24 at 8 11 37 AM" src="https://user-images.githubusercontent.com/377102/112325321-30a54100-8c79-11eb-9e2a-f4a2f0d6fb25.png">

If anyone is running into similar issues that @sycured is having, we encourage you to purchase a support contract and work with our support team to get you up and running.

Thanks for using FusionAuth!
