### ISSUE TITLE
.well-known discovery and correct url

### ISSUE THREAD

**Issue by botnyx** [FusionAuth/fusionauth-issues#116]
**Problem with the .well-known discovery and correct url**

I cant figure out how to display the correct url in the well-known discovery data.

for example:   https://xxx.xxxxxxxxx.org/.well-known/openid-configuration.
contains wrong information, as its using the internal hostname and port.
`{
  "authorization_endpoint" : "http://fusionauth:9011/oauth2/authorize",
  "claims_supported" : [
    "applicationId",
    "aud",
`

What am i missing here ?

**Comment by robotdan** [comment]
Hi @botnyx thanks for letting us know.

This is likely due to the proxy that you're using. Once the proxy forwards the request to FusionAuth running on `http://localhost:9011` if it doesn't pass along the correct headers then FusionAuth doesn't know enough to report the correct external URL. 

For example, if your external URL is `https://www.awesomesite.org` and FusionAuth is running at `http://localhost:9011` then the proxy needs to add the following headers (for example):

```
X-Forwarded-Protocol: https
X-Forwarded-Port: 443
X-Forwarded-Host: www.awesomesite.org:443
```

What proxy are you using, perhaps we can help you find the correct configuration.

**Comment by botnyx** [comment]
Hey there.
i have been looking at other issues , but did not find a solution yet. 

First, let me clarify my setup :  
The proxy is Ubuntu18 + Virtualmin ( Apache version 2.4.29) 
The fusionauth instance is a virtualmachine running Ubuntu 18.

Im kinda stuck to the Apache setup, so i cant use any other rev.proxy solutions like nginx or haproxy

But i will try to produce some working configs and post them here, in order to get the well-known/ discovery reflecting the correct information.

_a hour later i got the working config for my setup._ 

this works for me.
Both the 'unauthorized' error when posting something in the backend, as the incorrect discovery information is working correct now.

-----------------------------
`RequestHeader unset Host
RequestHeader unset X-Forwarded-Host

RequestHeader set X-Forwarded-Proto "https"
RequestHeader set X-Forwarded-Port "443"
RequestHeader set X-Forwarded-Host "my.external.dom"


ProxyPass / http://fusionauth:9011/
ProxyPassReverse / http://fusionauth:9011/
<Proxy *>
allow from all
</Proxy>`
----------------------------

i hope this helps somebody :)

**Comment by robotdan** [comment]
Thanks a lot @botnyx for the example config. We'll need to do a better job documenting some example proxy configuration to assist users. 

Thanks for your perseverance and contribution to FusionAuth!
