### ISSUE TITLE
Use proper ISO 639 alpha-2 in preferredLanguages for `he`, `yi`, and `id`

### ISSUE THREAD

**Issue by ceefour** [FusionAuth/fusionauth-issues#1165]
### Description 
As described in Legacy Language Codes in https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html ,
these are legacy language codes internal to Java.

However this is a legacy and even Java's own `toLanguageTag` uses `id` for Indonesian, not legacy `in`.

### Affects versions
1.23.3

### Steps to reproduce
1. Create a user with preferredLanguages = Indonesian or `id` (can be using UI or API)
2. Get that user using API
3. Observe that `"preferredLanguages": ["in"]`

### Expected behavior

```js
"preferredLanguages": ["id"]
```

### Platform
(Please complete the following information)
 - Device: any
 - OS: any
 - Browser + version : any
 - Database : any

### Related Issues
- https://github.com/FusionAuth/fusionauth-issues/issues/978

### Additional context

Going forward, FusionAuth should use proper ISO 639 alpha-2. This reduces potential for bugs and surprises, since it will work well with other systems.
However, if some users require it, a "backwards compatibility" flag can be used, to return legacy codes.

Java itself can accept both proper and legacy codes. So there shouldn't be any issues with accepting input, only for returning data.

**Comment by robfusion** [comment]
So this gets a little complicated, bear with me. This behavior is actually the behavior of jackson-databind :

https://github.com/FasterXML/jackson-databind 

We use that to do our serialization and deserialization of objects. Jackson will accept a large variety of string representations and convert them to java.util.Locale objects. If you are curious about the complexity of what it will handle as incoming input then you can take a peek at their _deserializeLocale method here:

https://github.com/FasterXML/jackson-databind/blob/2.13/src/main/java/com/fasterxml/jackson/databind/deser/std/FromStringDeserializer.java

That's why you can pass in a variety or strings that represent the same Locale and get back a result. That is very convenient, but has a side effect. How do you then represent the Locale object as a string when you retrieve it (serializer). Jackson chose to just fall back on calling the java.util.Locale.toString() method. That's what you will get when you serialize a Locale with jackson-databind. They could have chosen to go with calling Locale.toLanguageTag() to get the BCP 47 representation:

https://tools.ietf.org/search/bcp47

which is probably the better choice, but would also probably break tons of people who have persisted the serialized toString representations. java.util.Locale.toString() does not return a standardized format really. If you are curious you can read the doc here:

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Locale.html#method-detail

Basically it boils down to always getting a string in the format of:

`language + "_" + country + "_" + (variant + "_#" | "#") + script + "_" + extensions`

which is what you are seeing the the preferredLanguages, because the getLanguage() result on an indonesian Locale object returns "in" not "id". If you call getLanguageTag() on the same Locale you will get the BCP 47 result of "id" as you expected. Unfortunately, jackson-databind does not use the BCP 47 language tag representations when serializing Locales currently. 

In order for things to work smoothly through all the layers of serialization/deserialization, converters, etc. we have chosen at this point to stay consistent with jackson-databind's behavior when handling the Locale strings. So I'm not sure if there is an easy solution here without breaking existing persisted locale data as long as we continue to use jackson-databind for our serialization and deserialization.

**Comment by robotdan** [comment]
Going to close this out for now based upon the comment from @robfusion . @ceefour please re-open if you disagree with this assessment and we can possibly dig into it again.
