### ISSUE TITLE
Self service registration results in 400 error.

### ISSUE THREAD

**Issue by botnyx** [FusionAuth/fusionauth-issues#118]
Self service registration results in 400 error.

I created a application, and enabled self service registration, everything seems fine.
On the loginscreen, i clicked on 'Create an account'  which results in a 400 error.

The 'Create Account' link seems to be incomplete, as the state parameter contains 1 char.
 
Example:  
`https://fusionauth.domain.ext/oauth2/register?client_id=e6149d14-88e4-4cb7-ac72-111c512a6ceb&nonce=&redirect_uri=https://myapp.domain.ext/redirect.html&response_type=token&scope=&state={`

**Comment by robotdan** [comment]
Hi @botnyx 

Your example URL is not encoded, do you have an example of the encoded string? For example, the first character in your state parameter is `{` - to work properly on the URL this would need to be encoded to `%7B`. 

An example URL encoded may be
`https://fusionauth.domain.ext/oauth2/register?client_id=e6149d14-88e4-4cb7-ac72-111c512a6ceb&nonce=&redirect_uri=https%3A%2F%2Fmyapp.domain.ext%2Fredirect.html&response_type=token&scope=&state=%7B`

It is possible you are not encoding your state value. When you see the `400` can you capture the URL that you see in the address bar?

**Comment by botnyx** [comment]
I dont know what you mean by 'urlencode' as the urls are created by fusionauth.
im simply 'using' the provided link.    no custom-code whatsoever.

**Comment by botnyx** [comment]
The problem still exists, even when i removed the origin hosts.
It looks like the state-object isnt urlencoded at all.

You can see what happens here : https://bootstd.botnyx.com/oauthJS/index.html

**Comment by botnyx** [comment]
i just noticed, the  'forgot password link' has the exact same issue.

**Comment by robotdan** [comment]
Thanks, I clicked on your link and I see what is going on. I should be able to provide you a workaround shortly.

**Comment by robotdan** [comment]
Ok, I have a fix that will go into the next release. 

Here is the work around, update the following template: `/web/WEB-INF/templates/oauth2/authorize.ftl`

Current :

```
Don't have an account?
<a href="register?client_id=${client_id!''}&nonce=${nonce!''}&redirect_uri=${redirect_uri!''}&response_type=${response_type!''}&scope=${scope!''}&state=${state!''}&timezone=${timezone!''}&metaData.device.name=${(metaData.device.name)!''}&metaData.device.type=${(metaData.device.type)!''}">
Create an account
</a>
```

Fixed:

```
Don't have an account?
<a href="register?client_id=${(client_id?url)!''}&nonce=${(nonce?url)!''}&redirect_uri=${(redirect_uri?url)!''}&response_type=${(response_type?url)!''}&scope=${(scope?url)!''}&state=${(state?url)!''}&timezone=${(timezone?url)!''}&metaData.device.name=${(metaData.device.name?url)!''}&metaData.device.type=${(metaData.device.type?url)!''}">
Create an account
</a>
```

These parameters were not being escaped. Most of these do not need to be escaped, but in particular, the one that was causing you trouble was the state parameter. 

The summary of the change is to modify `&state=${state!''}` to `&state=${(state?url)!''}`.

Also, to use the `?url` on these parameters, you'll need to add the following to the top of the `authorize.ftl` file. 

```
[#setting url_escaping_charset="UTF-8"]
```

This change will not be persisted across an update of FusionAuth - but that is fine, this should be fixed in the next release. 

If you are using a theme, then you will either have to make this change to the theme or disable the theme and update the file that we ship. 

Let me know if that gets you by for now, thanks for reporting this issue. Two bugs in a day, we may have to pay you a bounty. :-)

**Comment by botnyx** [comment]
Thanks, that did the trick for both the Lostpass, as well as the Signup!

About that bounty : Dont bother: The project is the reward itself!
I was working on a similar solution in php with bshaffer's oauthserver library, but when i found out about this fusionauth,  its exact what i was trying to build.. which saves me a lot of coding :)

**Comment by robotdan** [comment]
Thanks @botnyx glad that FusionAuth fit the bill. 

> which saves me a lot of coding :)

This is the goal!
