### ISSUE TITLE
Userinfo endpoint still returns data after issueing logout

### ISSUE THREAD

**Issue by botnyx** [FusionAuth/fusionauth-issues#123]
### Steps to reproduce
1. Go to https://bootstd.botnyx.com/oauthJS/index.html
2. Click on 'Login with FusionAuth', use these credentials  : test@test.test/test12345678
3. You will welcomed : 'Hey test@test.test you are logged in.' and the token.
4. try any of the logout-endpoints.
5. refresh the page, 'Hey test@test.test you are logged in.' still states you are logged in.
6. take the token,  make a userinfo-call with postman or such.  (  or check the JS/network console on the page )
7. Try hitting the login button, and notice the FusionAuth login-page appears.

In short, after logout, the webinterface is loggedout,  but api-call to /userinfo with old token still reaps userdata.

### Expected behavior
After logging out, a a userinfo call shouldnt return data with the old token.

### Other findings

A introspect call also returns data...  
<pre>
`{
    "active": true,
    "aud": "e6049d14-88e4-4cb7-ac72-111c512a8ceb",
    "authenticationType": "PASSWORD",
    "email": "test@test.test",
    "email_verified": true,
    "exp": 1555330526,
    "iat": 1555326926,
    "iss": "my.fusioninstance.ext",
    "preferred_username": "test",
    "sub": "db239551-38d5-4808-adff-5bb26e373339"
}`
</pre>

**Comment by robotdan** [comment]
The `/oauth2/logout` endpoint will only invalidate the session held in the SSO so that the use is logged out of FusionAuth SSO. 

As long as an access token returned from FusionAuth as a result of a user authentication is not expired, it may be sent to the `/oauth2/userinfo` endpoint. 

The Userinfo endpoint does not validate the user is logged in, it only validates the access token. If the token is good, a `200` will be returned with a JSON response body. 

A common pattern for logout is for you to redirect to `/oauth2/logout` and then on a successful response you would delete any tokens you're holding in local storage or cookies.
