### ISSUE TITLE
Not sending email verifications for unverified user accounts after login

### ISSUE THREAD

**Issue by lliu-20200701** [FusionAuth/fusionauth-issues#1247]
### Description 
After login, if a user's email has not been verified, the email verification screen is shown, however, no verification email is sent. The verification email needs be sent by user clicking on "resend verification email". 

### Affects versions
1.27.2

### Steps to reproduce
1. Complete a sing up flow without verifying the email.
2. Login with the newly created account.

### Expected behavior
Receive another verification email upon login.

### Screenshots
N/A

### Platform
(Please complete the following information)
- Device: MacBook Pro
- OS: macOS
- Browser: chrome 81.0.4044.122 (Official Build) (64-bit)
- Database: MySQL 8.0.15

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by bguyza** [comment]
Update:
For this issue, I'm presuming that you are:
1. Creating an unverified User via the [User Import API](https://fusionauth.io/docs/v1/tech/apis/users/#import-users)
2. Logging in and potentially completing a custom registration flow 
3. Being prompted with the "Verification Required" page.

In short, FusionAuth does not send a verification email when a User is created via the import API.  This is intentional for reasons such as bulk imports where we want to maximize speed and efficiency.

By design, FusionAuth sends a verification email when a User is created in the UI or [User Create API](https://fusionauth.io/docs/v1/tech/apis/users/#create-a-user).  If I perform the steps outlined above using the create API instead, the system will send an email.

Please let me know if I accurately recreated the behavior you are experiencing or have any other questions?  

Thanks,
Brett

**Comment by robotdan** [comment]
After discussion with the client, we will plan to make the following adjustment. 

When email verification and email gated configuration is enabled, and the user enters the gate and the user does not have a pending verification email in flight, a new email will be sent automatically.
