### ISSUE TITLE
SSO session lifetime is not affected by configuration

### ISSUE THREAD

**Issue by originswift-sys** [FusionAuth/fusionauth-issues#1262]
### Description 
Unless I'm missing something here, the `Session timeout` value of tenants have no effect on the SSO session expiry. I currently have it set to `31536000` seconds and the SSO session still expires as if this wasn't configured at all.

### Affects versions
1.27.2, 3 nodes (Kubernetes)
Also experienced same in single node mode (Docker)

### Expected behavior
Increasing `Session timeout` should increasing the session lifetime accordingly, as documented.

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Windows 10 & Ubuntu 20.04
 - Latest versions of Chrome, Firefox and Edge
 - PostgresSQL 13.3

**Comment by mooreds** [comment]
Hi @originswift-sys . Thanks for using FusionAuth.

Can you please provide replication steps as to how you are verifying that the SSO session expires in a way you don't expect (API call, looking at cookie lifetime, using a sample app, etc)?

**Comment by originswift-sys** [comment]
So I've setup SSO. I hit the `/oauth2/authorize` with the correct params to use the auth code flow, and it all works great. I've verified that the session cookie expiry is set to the time I configured in the oauth tab of the tenant. Problem is, if I hit the `/oauth2/authorize`, it removes the cookie and prompts for login again with the toast that reads like "you've been logged out of fusionauth"

**Comment by originswift-sys** [comment]
I've tried numerous previous versions of fusionauth. Same result.
Deployed differently on different machines. Same result.
No logs indicate anything weird in dev mode.
Just consistent hourly session death.

**Comment by mooreds** [comment]
@jobannon do you have time to try to replicate?

**Comment by robotdan** [comment]
To ensure you are using the right config, there are two timeouts you will want to ensure are configured. 

1. SSO timeout. This is configured in `Tenant > OAuth > Session timeout`. This is the TTL in seconds that will control how long the SSO session lives. 
2. The FusionAuth admin session timeout. `Applications > FusionAuth > Edit > JWT > Refresh Token settings > Refresh Token duration`. Default is `60` minutes.


What values do you have configured for each of these?

**Comment by originswift-sys** [comment]
@robotdan 
1. 31536000
2. The default

Is the refresh token lifetime coupled to SSO session? I asserted that SSO session would outlive JWTs and catalyze obtaining new ones, regardless of the expiry of the tokens.

Also, my session has been alive for over 12 hours ever since I updated the session timeout of the default tenant to 31536000 as well. Previously, I only configured the tenant I created. I'm going to undo the default tenant session config now, destroy all sessions and see if I can decipher what's really going on.

**Comment by robotdan** [comment]
Your assertion is correct, if your SSO TTL is greater than your FusionAuth admin session TTL, then I would expect the FusionAuth admin session to die, it will kick you over to SSO, and because SSO is still alive, it will log you back into FusionAuth admin seamlessly, giving you a new FusionAuth session. 

Is this on localhost, or a prod URL using `https`?

**Comment by originswift-sys** [comment]
Production, using HTTPS.

I'm fine with a short-lived fusionauth admin session. My aim is to have SSO sessions for apps under the tenant I created last for at least a year. That is, the access token and refresh tokens of each app are allowed to die on inactivity, but the SSO session for that tenant lives long and the users don't have to supply login credentials again when the apps encounter a 401 and throw them to `/oauth2/authorize` (per my design).

This didn't work until I decided to try configuring the default tenant. The SSO session for the custom tenant kept dying as if it had some coupling with the default tenant session lifetime (I reckon it shouldn't?), which was still on the default 3600 seconds.

**Comment by robotdan** [comment]
When you end up having to login again after an hour - if you view the user's profile in FusionAuth admin, do you still see their SSO token under the "Sessions" tab?

**Comment by originswift-sys** [comment]
I'll observe and feedback after an hour.

**Comment by originswift-sys** [comment]
@robotdan the SSO session disappears after an hour as I returned the default tenant's session lifetime to 3600.

This implies the global SSO session is coupled to default tenant's session lifetime, and the session lifetime of other tenants are ineffective.

**Comment by robotdan** [comment]
There is only one SSO, which is the FusionAuth SSO, I believe this is then always configured by the default tenant value for `Session timeout`. 

However, I see that this value is available on each tenant, I don't know if that is a UI bug only or if we using it elsewhere. 

We'll investigate further.

**Comment by robotdan** [comment]
@jobannon can you set this up and attempt to replicate please.

**Comment by jobannon** [comment]
Interesting.  This seems adjacent to the main issue but:

1. If I spin up our node/typescript example app.  And create an `SSO_test_app`
1. Log in
1. As expected, I am presented with a `logout` button after logging in.  This would indicate to me that I have an SSO session setup.

-however-
1. If I use the FA admin UI and navigate to the login URL (for instance, below)
```
https://local.fusionauth.io/oauth2/authorize?client_id=f61c3986-9719-4792-9ec1-1a6551e2dc76&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth-redirect
```
I am not automatically logged in based on the previous session.  This could be expected behavior as maybe the node app and the direct copypasta from the admin screen creates slightly different cookies in the browser.  

-More importantly, after an hour-

- The FusionAuth Admin UI logged me out as I would expect
- The node application kept my logged-in session
- The direct IdP OAuth2 Login URL worked(https://local.fusionauth.io/oauth2/authorize?client_id=f61c3986-9719-4792-9ec1-1a6551e2dc76&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth-redirect) 

This was all tested on local dev setup. 

Also, I tested the Admin UI session timeouts (for sake of exploration, I ended up shortening the admin window duration).  If I set the `default` tenant to 60 seconds on the OAuth2, and the `refresh token duration` to one minute and the `JWT duration` to 60 seconds, then I become logged out very quickly, as expected!

![Screen Shot 2021-06-30 at 3 13 06 PM](https://user-images.githubusercontent.com/16090626/124032407-c6a5e180-d9b5-11eb-900c-0a27cf94138c.png)
![Screen Shot 2021-06-30 at 3 12 56 PM](https://user-images.githubusercontent.com/16090626/124032412-c7d70e80-d9b5-11eb-8125-71697d28a153.png)

**Comment by jobannon** [comment]
I don't believe that I understood the problem space fully; running additional recreate tests.  Will post back shortly.

**Comment by jobannon** [comment]
@originswift-sys I was not able to replicate this behavior.  If you have some other details regarding your setup that might affect and produce this result let us know.

**Comment by robotdan** [comment]
We have created the symptom a fix is forthcoming. 

To work around the issue, ensure that all tenants have an equal SSO Session timeout.

**Comment by robotdan** [comment]
@voidmain @brettwp @bguyza @jobannon  If you are interested, feel free to code review the change. See links to mentioned commits above (some are private) , main commits outlined below:

- https://github.com/FusionAuth/fusionauth-api/commit/b3dc99c53cf10cf5c7ef01edea3c91601d8fd8cf 
- https://github.com/FusionAuth/fusionauth-app/commit/b7923d81d52dc6f031928d7ee6cc98cbc03b8699 
- https://github.com/FusionAuth/fusionauth-database/commit/3fae85851cf8aa324f53369bcf0e1543cba8b710 

Summary: 
- Add FK to tenants, new tenantId field in domain
- Fix reaper
- Add test for multi-tenant SSO reaping
- Add new non-nullable column to refresh tokens by copying the table in migration (copying vs altering for performance)
- No API change to import refresh tokens, all changes are internal since we already have the tenant
