### ISSUE TITLE
Open source FusionAuth app/search code

### ISSUE THREAD

**Issue by richardpoole** [FusionAuth/fusionauth-issues#128]
### Problem
It's possible I'm an idiot and I just haven't found the repositories containing the server-side code, but I'm finding it very difficult to debug a permissions issue with FusionAuth because I don't have access to the source code.

### Solution
Release the source code of FusionAuth's server-side components on GitHub, ideally under a permissive [OSI-approved licence](https://opensource.org/licenses).

### Alternatives/workarounds
- Reverse engineer FusionAuth (in my experience, always more hassle than it's worth)
- Find an alternative to FusionAuth

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Can you open a separate issue if you're having problems with permissions? This is likely a proxy configuration issue due to missing X-Forward- headers causing our CSRF check to trip.


You're not an idiot, FusionAuth is not open source. 😁

The search engine is Elastic Search, and all of the client libs are open source.

**Comment by robotdan** [comment]
There are no current plans to modify our licensing terms for the source code of FusionAuth. 

This is something that we continually discuss internally and weigh the pros and cons of how we distribute and support the product. 

Thanks for the feedback!
