### ISSUE TITLE
Need more granular permissions for FusionAuth app

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#131]
### Problem

We would like to give access to FusionAuth to our customer care in order to see login report / user data. Unfortunately, we cannot restrict the permissions to read only in the user listing:

<img width="1342" alt="Screen Shot 2019-04-19 at 10 20 56 AM" src="https://user-images.githubusercontent.com/1580512/56410221-67080380-628d-11e9-9acb-4813104b35f2.png">

It could be nice to have extra permissions like:
-  User edit (user_edit)
-  User registration edit (user_registration_edit)
-  User delete (user_delete)
-  User lock (or can be included in user_edit or user_delete)
-  User manage without role escalation. Right now a user with the `user_manager` role cannot change their own roles, but can change others roles in the FusionAuth application, making privilege escalation trivial. Would be nice to limit a user_manager so they can modify roles in other applications but not for anyone in the FusionAuth application.

### Solution
By the way, what is ` User deleter (user_deleter)`?

**Comment by robotdan** [comment]
Thanks for the request @blanchonvincent . 

This is a good feature for the roadmap, I'll mark it as such. 



> By the way, what is `User deleter (user_deleter)`

For things like Applications, Users, and Tenants, we add a `_deleter` role. This means you can view, edit and add these items using the `admin` or `_manager` role for the respective item. 

In order to delete any of these things you will also need the `_deleter` role. So to delete a user, you will need either `admin`, or `user_manager` AND `user_deleter`. 

So - in theory, you should be able to assign your customer care folks the `user_manager` role and they will not be able to delete users. We do not currently hide the delete actions based upon their role, but the action will fail. 

This `user_manager` role will still allow the customer care user to add and remove user registrations. So in your screenshot, the delete user at the top will fail,  but the delete registration will succeed.  The `user_manager` will also be able to lock an account. 

We could add a `registration_manager` role which would allow add, edit, remove registrations on users. 

In your ideal scenario, it sounds like you want to allow viewing the user, but not allow add, edit or delete user registrations, account locking or user delete?

**Comment by blanchonvincent** [comment]
`We do not currently hide the delete actions based upon their role, but the action will fail.` Ok got it, that's why it is confusing.

`We could add a registration_manager role which would allow add, edit, remove registrations on users.` It would be amazing.

`In your ideal scenario, it sounds like you want to allow viewing the user, but not allow add, edit or delete user registrations, account locking or user delete?` yes exactly :)

**Comment by robotdan** [comment]
Great, thanks for that feedback @blanchonvincent . I'll update the milestone when I can get this into plan. This should be a fairly easy update.

**Comment by SebastianCanonaco** [comment]
Any news on this issue? Need this functionality too.

**Comment by robotdan** [comment]
@SebastianCanonaco no news to report. Upvoting issues does helps us prioritize our resources for community requested features. 

If you have a business need for this functionality we do offer paid support plans and professional services engagements to expedite features. 

Thanks for using FusionAuth!

**Comment by robotdan** [comment]
We do have more roles now, specifically a few roles geared towards user managers. 
https://fusionauth.io/docs/v1/tech/core-concepts/roles/

Please do re-open if there are roles we are missing that would allow you to offer a better experience for your users. 

Thanks!

**Comment by mooreds** [comment]
To answer the question in https://github.com/FusionAuth/fusionauth-issues/issues/131#issuecomment-485242318 for any future viewers, you can use the `user_support_viewer` role.
