### ISSUE TITLE
Not able to change user's email address with User API

### ISSUE THREAD

**Issue by Jlintonjr** [FusionAuth/fusionauth-issues#1333]
### Description 
I am attempting to change the user's email address with the patch endpoint `api/user/{userId}` . 
I am include the email in the request body as such:
```
{
   "user": { 
       "email": "newEmailAddress@email.com"
      ...other properties
  }
}
```

I would assume this to be able to update the user's email since the user's key is in the API route, but I am getting a 404 when I am changing the email value and I receive no error message or exception.

### Affects versions
1.27.2

### Steps to reproduce
1. Try to change the email in the request body

### Expected behavior
When the email is included, it will be updated if it is unique within the Tenant

**Comment by robotdan** [comment]
A `404` will not return a JSON body. Please provide a full example of the the request URL and a JSON body. 

The most likely case for getting a `404` is you are providing the wrong `{userId}` on the URL, so the user you are trying to update cannot be found by the Id.

**Comment by Jlintonjr** [comment]
Here is an example of a successful request that changes the user's username:
```
curl --location --request PATCH 'https://MY_DOMAIN/api/user/VALID_USER_ID' \
--header 'X-FusionAuth-TenantId: MY_TENANT_ID' \
--header 'Content-Type: application/json' \
--header 'Authorization: MY_API_KEY' \
--data-raw '{
    "user": {       
        "username": "ab2@test.com"
    }
}'
```

However, when I try to change the email property, is when I get the 404:
```
curl --location --request PATCH 'https://MY_DOMAIN/api/user/SAME_VALID_USER_ID' \
--header 'X-FusionAuth-TenantId: MY_TENANT_ID' \
--header 'Content-Type: application/json' \
--header 'Authorization: MY_API_KEY' \
--data-raw '{
    "user": {       
        "email": "ab2@test.com"
    }
}'
```
In this case when it throws the 404, the user's email address is `ab1@test.com`. When I include the email property to be `ab1@test.com`, I receive a 200, but the email address isn't being updated to what I need it to be updated to. It seems as if when then email property is included it is searching for the user by that value as well.

Please let me know if I can include any additional information.

**Comment by robotdan** [comment]
Thanks for that detail @Jlintonjr that is super helpful. We can try to recreate.

**Comment by Jlintonjr** [comment]
@robotdan I am debugging this more and I believe I'm seeing what the issue may be. I am able to update a user's email whose account is verified, but am unable to update a user whose email is not marked as verified. That is when I receive the 404 error. I hope that helps.

**Comment by jobannon** [comment]
@Jlintonjr That is super helpful -- will give us some good clues as we debug.

**Comment by mooreds** [comment]
@Jlintonjr what are your email/registration verification tenant settings?

**Comment by Jlintonjr** [comment]
@mooreds are these the settings that you are referring to?

![image](https://user-images.githubusercontent.com/11423675/128059332-a6ba2a38-c4f0-4e3a-8d46-1b43726fd738.png)
![image](https://user-images.githubusercontent.com/11423675/128059403-ab51fa43-4f07-41a1-a9ca-b84fe93b3274.png)

**Comment by mooreds** [comment]
Thank you, that is what I was asking about.

**Comment by jobannon** [comment]
@Jlintonjr I tested both `put` and `patch` and was able to make updates to my chosen user (even when unverified) using a simple rest client (Postman).  However, I am on version 1.29. 

The next thing I might check is your version, so see if this bug is perhaps version-specific.

**Comment by Jlintonjr** [comment]
We are on version 1.27.2. I will try to upgrade in the off-hours to see if that fixes the issue for us.

**Comment by robotdan** [comment]
We had another client report this issue in a separate support channel. They indicated they were noticed the issue `1.29.2`. We have been unable to reproduce, we have an integration test that performs this exact operation in a single tenant setup, and in a multi-tenant setup. 

@Jlintonjr If you are in development, or can recreate in a development environment - would it be possible to get a dump of your database for us to use to recreate? If so, if you're in the FusionAuth Slack channel, DM me, otherwise use the contact form on our website and we can arrange a secure transfer, and we can assist you with a dump command if you are not familiar.

**Comment by Jlintonjr** [comment]
Hi @robotdan , I just used the contact form on the website. We are using a multi-tenant setup and I was just able to reproduce the issue in our development tenant.

**Comment by voidmain** [comment]
It doesn't look like your email came through. Can you just email me directly so we can get a copy of your database? My email is brian@fusionauth.io.

**Comment by voidmain** [comment]
@Jlintonjr - We've tested against your database and I think we might have an idea of what is happening.

It looks like your API key is scoped to a Tenant, and the user you are editing is in a different Tenant. This will cause the API to return a `404`.

However, based on your previous cURL snippets, it looked like you were sending in the Tenant Id header. If that header is a different tenant than the API key is associated with, the API should return a `401`. That’s the part we aren’t sure on.

In order to figure out if this is still a bug or not, can you create a new API key that is not scoped to a Tenant and try using that key to make your calls?

This should work and allow you to update the users.

**Comment by Jlintonjr** [comment]
@voidmain The user that I sent over in the email is scoped to the `Dev` tenant, which is what the API key is scoped to. 

I just created a new API that isn't scoped to any tenant and it is still returning the same 404. 

I don't think the API key is the issue because when I use this key I am able to update other fields of that user just fine. The 404 is only ever appearing when I include the `email` parameter.

**Comment by robotdan** [comment]
Finally was able to recreate. 

Recreate:
1. Turn on email verification
2. Create a user, do not verify their email address
3. Turn off email verification
4. Update user's email address

Perhaps there is another way to get into this state, but I have not found it.

**Comment by robotdan** [comment]
Fix is available in 1.29.3.

**Comment by Jlintonjr** [comment]
Upgrading to 1.29.3 fixed this issue. Thank you all for your help on this!

**Comment by pmolaro** [comment]
Could I ask that someone verify that this issue hasn't returned in the latest version, 1.30.2? I'm having the same problem. I can update a user's properties in general. However when I try to update the email or username (we use emails as usernames), nothing changes in the user, and the console shows me a user not found response. My settings seem to be correct in the FA Admin, per the discussion above, so I wanted to get some verification that the issue hasn't re-surfaced. Thanks in advance.

**Comment by mooreds** [comment]
@pmolaro it is best to open a new issue with replication steps as that is more visible. Providing curl commands (like this comment: https://github.com/FusionAuth/fusionauth-issues/issues/1333#issuecomment-891751514 ) is even better as it lets us see quickly if the issue is reproducible in our environment.

Thanks for using FusionAuth!
