### ISSUE TITLE
Feature: Shopify app to "Login with FusionAuth"

### ISSUE THREAD

**Issue by jsmwoolf** [FusionAuth/fusionauth-issues#135]
### Problem
Part of our application will allow users to log onto Shopify stores using their credentials.  I know that Shopify supports this via Multipass, but it's for Plus merchants only.  Is there a way to configure FusionAuth to act as an SSO for Shopify?  In general?

If not, is there a way to integrate FusionAuth with another piece of software that supports this functionality?

### Solution
Publish an app in the Shopfiy app store to login with FusionAuth.
https://apps.shopify.com

### Alternatives/workarounds
You could optionally use FusionAuth as is, and purchase Shopify Multipass. 
https://help.shopify.com/en/api/reference/plus/multipass

This would still require that you code the Shopify Multipass API in your own application.

### Additional context

https://apps.shopify.com/smart-social-login
https://apps.shopify.com/login-with-amazon
https://help.shopify.com/en/partners/making-apps

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
I am not that familiar with Shopify but I read their Multipass documentation. 
https://help.shopify.com/en/api/reference/plus/multipass

From what I've read, Multipass solves this SSO issue by allowing you to create a user through their Multipass API to represent the currently authenticated user in your own application. 

In theory, it looks like we could build a Shopify application to "login with FusionAuth" - so the user would be authenticating against FusionAuth instead of Shopify. I believe this would negate the need for Multiplass. 

For example, here is one I found for Social login and another for Amazon login.
https://apps.shopify.com/smart-social-login
https://apps.shopify.com/login-with-amazon

This makes me thing it is possible to build an app for Shopify that handles login. If this is of interest to you, we could explore building this as part of a professional services contract, or if you want to build it open source we could possibly collaborate with you as we have time. 

I'll re-word this issue as a feature request in case anyone else wants to upvote it.

**Comment by jsmwoolf** [comment]
I'm definitely interested in this feature.  I'm working on this application on behalf of somebody else, so he would have to make the call on whether to actually do via a professional services contract.

If he refuses and I had to go with the open source route, what would be required in order for this application to be in a functional state?  Would I need to know how write plug-ins for FusionAuth?

**Comment by robotdan** [comment]
If you want to go pro-serve route,  use the Contact form on our website and we can get you a quote. 

>  what would be the requirements in order for this feature to be in a functional state? Would I need to know how write plug-ins for FusionAuth?

I've never written a Shopify app, so I have limited knowledge here.  But what I am thinking is that this app would simply use OpenID Connect. This means there is no custom code on the FusionAuth side of things. Since our login already handles all of the standard workflows such as login with social, forgot password, reset password, 2FA, etc, etc - if we can get Shopify to use FusionAuth as the IdP I think it will just work. 

If this is of interest to you, let's chat about this on the FusionAuth Slack channel.

The best case scenario is likely for us to build it out as a pro-server deal, it may be worth while to at least explore that option. We generally try to make our pro-serve quite reasonable, especially if it is something that we think could benefit the product in general.

**Comment by jsmwoolf** [comment]
I submitted a contact form about the feature.  When you respond, I'll be able to forward it over to the other guy to keep him in the loop.

**Comment by robotdan** [comment]
Great, I saw that come through. We should be able to get a quote put together Monday or Tuesday.

**Comment by robotdan** [comment]
Closing this one out. My guess is that it will work already as long as Shopfiy support OAuth2 / OIDC. We could explore building this as part of a professional services contract if anyone is interested.
