### ISSUE TITLE
Last login instant field is sometimes missing from the retrieve user API response

### ISSUE THREAD

**Issue by johnmaia** [FusionAuth/fusionauth-issues#1380]
### Description 
Using the FusionAuth node client, if you attempt to retrieve the user right after registering it the `lastLoginInstant` field is sometimes missing. In other words, the following parameters are sometimes missing.
- `user.lastLoginInstant`
- `user.registrations[x].lastLoginInstant`

If I insert a sleep between the registration request and the retrieve user request then the field is always filled.

### Affects versions
- `v1.30.1`

### Steps to reproduce
1. Using `@fusionauth/node-client@1.29.1` node dependency
2. Call `register` method
3. Call `retrieveUser` method using the `id` from the user registered on step **2** 
4. Notice that sometimes the `lastLoginInstant` is not set

### Expected behavior
The `lastLoginInstant` should always be present.

**Comment by mooreds** [comment]
@johnmaia this may be a transactional timing issue, esp since you are saying a sleep fixes the issue. 

If you need to ensure that the `lastLoginInstant` (and the rest of the registration object) is 100% complete, I'd suggest listening for a webhook. We added new webhooks that only fire after a transaction has completed in 1.30 (which you mention above you have upgraded to). This looks like the right one for you: https://fusionauth.io/docs/v1/tech/events-webhooks/events/user-registration-create-complete/

Let me know if I misunderstand the issue.

**Comment by johnmaia** [comment]
Hi @mooreds! Thanks for the fast reply.

It's nothing critical, it's just something we noticed on our tests but we can safely ignore.

**Comment by robotdan** [comment]
This is a change in `1.30.1`. We have a bunch of performance improvements to increase the potential RPS for login. 

A couple of the changes we made for login were:
- Move the update of the `lastLoginInstant` on the `user` and `registration` to an async process
- Move the Elasticsearch index update to an async process

So it will now be very possible to log a user in, immediately retrieve them and be missing the most `lastLoginInstant`. We decided this was reasonable to obtain higher performance during login. 

In practice, the update to the user record should be very fast and it should be done nearly as soon as the user logs in. However, because it is no longer done inline in the same TX - so there will be some timing here to deal with.
