### ISSUE TITLE
SAML + Auth2 SSO not working

### ISSUE THREAD

**Issue by janakapdj** [FusionAuth/fusionauth-issues#1419]
Hi
I am working on implementing SSO with different authentication methods
React Js application with Auth2
Sisense with SAML
I have followed the instruction  as given in https://fusionauth.io/blog/2021/02/09/single-sign-on-sso-with-fusionauth/ 
Both applications were individually authenticated and return back as expected but it won't work SSO as expecting ( when the user has logged in and authenticated by one application he/she should be able to access the other one without authenticating )
SSO time out also set in to 10 hours in tenant 
can someone help with this and give a suggestion?

I have attached configurations for both applications
![sisense](https://user-images.githubusercontent.com/5866239/135443038-7cb319b9-4942-4239-b202-32298c385073.PNG)
![user](https://user-images.githubusercontent.com/5866239/135443044-904b94de-f62a-4c50-a16f-c0395b28b1c2.PNG)
![web](https://user-images.githubusercontent.com/5866239/135443045-cf79fe47-e81a-43be-987b-6b1586f88656.PNG)

**Comment by mooreds** [comment]
Hi @janakapdj 

Thanks for using FusionAuth! This appears to be a support question, rather than a bug report with details reproduction steps. 

We use GitHub for feature request tracking and detailed bug reports, but not for support. (More here: https://fusionauth.io/technical-support/ )

If you have a support plan, please open a ticket here: https://account.fusionauth.io/account/support

If you do not have a support plan, please ask in our community forum: https://fusionauth.io/community/forum/

Thanks!

**Comment by janakapdj** [comment]
thanks, moorred ill post question on the community
