### ISSUE TITLE
Error after updating the password

### ISSUE THREAD

**Issue by erick4556** [FusionAuth/fusionauth-issues#1441]
Hello, I have an issue after updating the password. After I update the password, fusionauth redirects from "myurl/password/change/idUser" theme to "myurl/password/change/change". It shows an error 500 and it doesn't take the change password complete theme.

I attach an image
![error](https://user-images.githubusercontent.com/11901315/137548182-37e53526-2906-4931-ab22-4b74333c7a39.png)

I would appreciate your help

**Comment by erick4556** [comment]
> Hiya,
> 
> Thanks for using FusionAuth!
> 
> Please share:
> 
> * the 500 error that you receive.
> * the version of fusionauth you are on
> * if you have modified your theme at all
> * if you are self hosting or running in FusionAuth cloud.

**Comment by erick4556** [comment]
I just saw the image error 500 that I've uploaded
FusionAuth version: 1.19.6
I have modified the theme at all. When I update the password, the password changed but fusionauth redirects to myurl/password/change/change theme which it shows the error that i've uploaded and not to password change complete theme. All themes work good only password change complete theme neither works nor is displayed.
Self hosted

**Comment by mooreds** [comment]
That's a pretty old version of FusionAuth too (released about a year ago: https://fusionauth.io/docs/v1/tech/archive/release-notes/ ). I would recommend upgrading to the latest version and seeing if you can replicate the error.

**Comment by mooreds** [comment]
Hi @erick4556 . Fair enough, though there has been a ton of changes in the last year, including many bug fixes. 

If you tested in the latest version and the issue still existed, it would definitely be higher priority. You could always test by standing up a copy of your product database, upgrading it, and then seeing if the issue occurs. This would provide more info for us without impacting your production options.

You have a couple of options.

* See if the bug is fixed in a more recent version as mentioned above.
* Look through the detailed release notes to see if we have fixed this bug, upgrade to that version: https://fusionauth.io/docs/v1/tech/release-notes/
* Post in the forum to see if anyone else has encountered this bug: https://fusionauth.io/community/forum/
* If you have a paid support plan, open a ticket: https://account.fusionauth.io/account/support/

We're a small team and try to support everyone to the best of our ability, but supporting versions 10 minor releases behind the current release without a paid support plan is, as I'm sure you can understand, hard for us to do. Please help us by testing it out on the latest version or pursue one of the other options listed above.

Just as an FYI, it is extremely unlikely we will backport a fix to 1.19, so if we found a bug and fixed it, you'd likely have to upgrade anyway.

**Comment by mooreds** [comment]
Ah, I see you have already opened a forum message: https://fusionauth.io/community/forum/topic/1317/error-after-updating-the-password

Let's continue the conversation over there.

Closing.
