### ISSUE TITLE
OpenID Service provided link does not work with Identity Providers

### ISSUE THREAD

**Issue by qetzing** [FusionAuth/fusionauth-issues#1447]
### Description

After successfully creating an OpenID Identity Provider, you can activate the registration for a FusionAuth app, so you can register with a UI button via the specific provider.
Though, if you try to use the direct link by your 3rd party service application, you get the following error:

```json
{
  "error" : "invalid_request",
  "error_description" : "The request is missing a required parameter: redirect_uri",
  "error_reason" : "missing_redirect_uri"
}
```

To be a little more specific, I created my Discord Identity Provider, which I wanted to use via the link I get from the Discord Application:
![image](https://user-images.githubusercontent.com/41159142/137996745-5cdc5e7b-4128-4e13-9f9d-24ca47fe263f.png)

This link however does not work as I get the error above. On the other hand, the button to register, which FusionAuth provides, does work.
Though, I need for my service the direct link (because I'm having my own buttons, etc.), which does not work. 

Am I making something absolutely wrong or does FusionAuth simply not provide the needed functions?

### My Configuration

The link I get from the Discord Application (which works btw. fine):

https://discord.com/api/oauth2/authorize?client_id=XXX&redirect_uri=https%3A%2F%2FXXX%2Foauth2%2Fcallback&response_type=code&scope=identify%20email

My FusionAuth Identity Provider configuration:

![image](https://user-images.githubusercontent.com/41159142/137997168-0a8f7b30-ddb2-4bd7-9a84-796ab0315828.png)

**Comment by lyleschemmerling** [comment]
I believe this is the issue `Though, I need for my service the direct link (because I'm having my own buttons, etc.), which does not work.`.

The URL provided in the Discord URL Generator will not work. The login flow needs to initiate at FusionAuth so that we can handle the integration with Identity Provider which means you cannot go directly to Discord to initiate the flow.

We do have a blog post demonstrating [how to set up the discord integration](https://fusionauth.io/blog/2022/04/25/single-sign-on-with-discord).

I did verify that the integration with Discord works correctly when set up in this way.
