### ISSUE TITLE
Roles not combined between user assigned and group memberships

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1473]
### Description 

if you have a user with a role in an application, then assign them a group with roles, the user only has the one role until you remove the role individually assigned to them.

### Affects versions

1.30.2
Introduced under https://github.com/FusionAuth/fusionauth-issues/issues/480.

### Steps to reproduce

1. Add a user
2. Add an application with three roles: test1, test2, test3
3. Register the user for the application, register them for role test3.
4. Log them in to this app, examine the JWT. It will show test3 in roles. (I used the password grant if it matters)
5. Create a group, assign it roles test1 and test2
6. Assign the user to the group
7. Log them in again.

Expected: they would have roles test1, test2 and test3. Reality: only test3.

If you remove test3 from the user's roles (via admin ui), they will have test1 and test2 roles in the JWT

### Expected behavior

Group and user roles are unioned.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
@bguyza can you take a look at this this one - not 100% sure if this is a bug or working as designed. If the later, we'll need to review it to understand the original intent and if that still applies.

**Comment by bguyza** [comment]
This is the result of the change that was made [here (issue 480)](https://github.com/FusionAuth/fusionauth-issues/issues/480) to improve query performance.  When we use `COALESCE` as part of the join criteria for `application_roles`, we end up joining on the first non-null value.  Therefore we are not correctly joining roles that are assigned via groups (or via `group_application_roles) since `user_registrations_application_roles` is evaluated first.

I would say this IS a bug since the query is not returning all the roles as exhibited in the case where a user has one or more application roles AND group roles.  However, the previous correct version seems to have performance implications. 

I will see if I can come up with a solution that satisfies accuracy and performance.

**Comment by mooreds** [comment]
my vote, if I get to pick, is 'accuracy' :)
