### ISSUE TITLE
Retrieve lists of contained objects?

### ISSUE THREAD

**Issue by fogelfish** [FusionAuth/fusionauth-issues#148]
### Description
In my use case, I will have to retrieve lists of objects where results satisfy "has-a" or "belong-to" conditions.  For example, I might need a list of applications that belong-to one tenant; a list of user registrations that belong-to one application; a list of groups that belong-to one tenant; a list of groups that have-a particular role (or set of roles); a list of members that belong-to one group; or a list of groups that have one particular user as a member.

It doesn't appear that any FusionAuth API's produce this sort of output.  If that's true, do you know how queries like this could be run in elastic search and results returned to my client?

**Comment by robotdan** [comment]
Hi @fogelfish thanks for your question.  I think you should be able to accomplish each of these tasks. 

> a list of applications that belong-to one tenant

When making this API request using an API key assigned to a tenant, or by providing a request header, only applications belonging to the tenant will be returned. See https://fusionauth.io/docs/v1/tech/tutorials/tenants. 

For example, you can add this HTTP request header where `24b325e1-c1b8-4cc6-a2d3-ea316cec9e2e` is the Tenant Id. 

```
X-FusionAuth-TenantId: 24b325e1-c1b8-4cc6-a2d3-ea316cec9e2e
```
Or create an API key that is assigned to this tenant.



> a list of user registrations that belong-to one application

Yes, this can be done using the User Search API.  If you use the Advanced search panel in the UI and then toggle on the `Show query string` you will see the Elasticsearch Query String we are building. 
https://fusionauth.io/docs/v1/tech/apis/users#search-for-users

For example, here is the query string to return all users registered to the Application with Id `a8a913cf-5a22-48a8-858e-8c4c742205a3.

```
registrations.applicationId:a8a913cf-5a22-48a8-858e-8c4c742205a3
```

> a list of groups that belong-to one tenant

This is the same as retrieving the Applications. Using the Group API with an HTTP request header or an API key will cause only the Groups in the tenant to be returned. 

> a list of groups that have-a particular role (or set of roles)

You could currently using the Group API to retrieve all groups and then identify the Roles assigned to this Group. So indirectly I think you can accomplish this task. There are probably ways we could enhance this in the future, we could index the groups and roles so that they can more easily be returned by an Elasticsearch query. 


> a list of members that belong-to one group

This can be done using the User Search API. If you use the Advanced search panel in the UI and then toggle on the `Show query string` you will see the Elasticsearch Query String we are building. 

For example the following query string will return all users that belong to the Group with Id `c21f619c-c3b4-4f99-910f-9e9865ccde98`.

```
memberships.groupId:c21f619c-c3b4-4f99-910f-9e9865ccde98
```

> or a list of groups that have one particular user as a member.

I don't know that we have an API for this directly, everything is currently indexed around the user and the registrations or group membership.

You could use the User Search API to retrieve a single user which will contain Group Memberships which will then tell you which Groups this user belongs by Group Id. 

If you need help with specific queries, let me know and I can help. 

We will be providing additional examples and documentation of how to fully leverage the Elasticsearch Query DSL language in the near future.  https://github.com/FusionAuth/fusionauth-issues/issues/30

**Comment by fogelfish** [comment]
Thanks, @robotdan.  This is very helpful guidance.  I'm glad you'll be adding documentation for applying Elasticsearch in FusionAuth because I suspect (tho I don't actually know) that there is more speed and power to be gained by utilizing queries and filters there rather than cherry picking the JSON response.

For example, is there a way to instruct Elasticsearch to return only specific values from the entire base API response when listing groups belonging to one tenant?

`http://localhost:9011/api/group
(adding the X-FusionAuth-TenantId header)`

Let's say I want to see only the id and name of each group?

**Comment by robotdan** [comment]
> For example, is there a way to instruct Elasticsearch to return only specific values from the entire base API response when listing groups belonging to one tenant?


I think you're asking to prune the JSON response to only return the `id` and `name` fields (for example)?

This is not possible currently. Do you ask due to performance concerns with the size of the JSON response body? Or do you have another use case in mind?

**Comment by fogelfish** [comment]
You're right.  I'm new to FusionAuth and Elasticsearch and simply wanted to know if streamlining the JSON response with Elasticsearch filters would be possible.  Thank you.

**Comment by robotdan** [comment]
Closing this one out, I think this can be managed by leveraging a search query using the tenantId. 

If there is a use case where you want to full reporting of all objects such as applications, groups and users by tenantId, please open a feature request for that.
