### ISSUE TITLE
Error: Invalid Authorization Code

### ISSUE THREAD

**Issue by Nosherwan** [FusionAuth/fusionauth-issues#150]
### Description
I am using version 1.4.0 of fusionAuth. I am using Authorization code grant flow.

1. I register a front end web app and successfully redirect to the login page, "https://auth.chargetogether.com/oauth2/authorize?"
2. Upon completion of login, my web server callback is called with the new code.
3. I then make a post request to "/oauth2/token" endpoint with that code in addition to the other required params from my server app to get the access token. However in response I get the following error message:

```js
{ error: 'invalid_request', error_description: 'Invalid Authorization Code',
 error_reason: 'auth_code_not_found' }
```

I have spent alot of time on this, when I try to remove the code param altogether from the request I get the correct error message stating, no code param provided. However on providing it I get the auth_code_not_found error.

Following is the sever code I am using:

```js
 const url = 'https://XXX/oauth2/token';

            const data: any = {
                client_id: 'my-client-id',
                code: ctx.query.code,
                grant_type: 'authorization_code',
                redirect_uri: 'http://localhost:4000/tokens',
            };

            const queryString = Object.keys(data)
			.map(function (key: any) {
				return key + '=' + encodeURIComponent(data[key]);
			})
			.join('&');

            try {
                const result = await Axios({
                    method: 'POST',
                    url,
                    headers: {
                        'content-type': 'application/x-www-form-urlencoded'
                    },
                    data: queryString,
                });
                return result;

            } catch (error) {
                console.log('following error occurred', error.response.data)
            }
```

Can you please suggest what maybe happening here?

Thanks in advance.

**Comment by robotdan** [comment]
Hmm.. your code to call the Token endpoint looks ok upon initial inspection. The default TTL on the auth code is 30 seconds. Is it possible you're exceeding this timeout during testing?  If so, we will have expired the auth code, this could cause the error you're seeing. 

You can increase this value in the System Settings. Settings --> System --> Advanced --> External Identifiers, and modify `Authorization Code`. 

Let me know if that helps.

**Comment by Nosherwan** [comment]
@robotdan thank you for the quick response :).

However TTL was not the issue here.

I have figured out the issue. The redirect_uri defined in the above code is not the same as the one on which the first redirect request is received. So here is the explanation:

1. We have two callbacks defined in fusionAuth applications settings: edit application -> options -> `authorized redirect urls`. (screenshot below)
<img width="669" alt="Screen Shot 2019-04-30 at 9 10 26 am" src="https://user-images.githubusercontent.com/138489/56932711-16fc2d00-6b28-11e9-8548-8c21f1391da8.png">
2. The callback url ending in auth is the first one that receives the `code`. This callback then requests for the access token with the javascript code provided in the original description, however in the request it sends the second callback url.

It seems that fusionAuth does not like the fact that a different callback url is being sent in the second request, and instead of sending that as an error it says `Invalid Authorization Code`, which is not the correct error here.

**Comment by robotdan** [comment]
Thanks for the update @Nosherwan, glad you got past this issue. 

The OAuth2 specification states that the `redirect_uri` parameter provided on the Token Request match the one provided on the Authorization request. This is the reason for the validation.

https://tools.ietf.org/html/rfc6749#section-4.1.3

Because the response to the Token endpoint is a `200` with a JSON body, the redirect URI is there only to validate that the caller making the request knows the correct `redirect_uri` registered with the Identity Provider and is the same value specified during the authorization request (in case there are more than one registered). 

The reason for the "mis-leading" error message is that we assume that this is either a dev time issue, or a malicious request. So instead of telling the caller that the auth code was ok, but the redirect was incorrect we fail as if the code was invalid. (not found)

So that is the rationale for the message in case that is helpful. We are always trying to balance the line of helping the developer with good messages, and not giving a  malicious user enough information to refine their attack. 

Perhaps we are being a bit too cautious here with the messaging, I can certainly review this decision again to ensure we still feel it is the correct one. 

> Just want to mention so far your product seems to have good value and quality, so keep up the good work 👍🏼

Thanks! I appreciate the feedback. We always like to hear how people find FusionAuth, so if you're willing to share that would be great. You can also email me directly if you prefer. daniel _ at _ fusionauth.io.

**Comment by Nosherwan** [comment]
Nice explanation @robotdan.

I understand where you are coming from and why that particular error is sent back, however I would suggest instead of sending back a specific error than maybe a more generic error message would do. Something along the lines of `incorrect request params sent please review`.

Thank you for the details I will contact you in future at some point in time.

I have one more suggestion:
Fusionauth documentation does mention how to enable `self service registration`, however it doesnt specify clearly that a ` Authorization Code Grant Request` has to be sent to that endpoint.

If that was put somewhere in the docs it would be helpful for future users.

**Comment by robotdan** [comment]
@Nosherwan re: self service registration. Not sure if I understand. 

Do you mean that only The Authorization Code grant is working for self service registration, and not The Implicit Grant?

**Comment by Nosherwan** [comment]
@robotdan no I was probably not able to explain properly.
What I meant was I had to go through github issues to figure out that we had to send an authorization request from our client web application to redirect users to login/register page. It may not be apparent for first time users that they need to do that once self service registration is enabled for the application via fusionAuth.
Hope that is clear enough...?

**Comment by robotdan** [comment]
Ah, ok. I think I see what you mean. You are redirecting users from your own application to the self-register page in FusionAuth. 

I suppose that is do-able, the reason that isn't documented is because it wasn't how we intended it to be used. :-) We handle all of the redirects to that page. 

We intended it to be used without any code or modification on your end at all. For example, the following workflows will get the user through registration:

#### New User, not registered
1. Your application redirects to the FusionAuth OAuth2 login page
2. User clicks on `Don't have an account?`. 
3. User registers, and is logged in


#### Existing User, already registered, missing required fields
1. Your application redirects to the FusionAuth OAuth2 login page
2. User has an account already (or a partial one) and is already registered for the application
3. User authenticates, and FusionAuth identifies the user has not completed all of the required fields that were set during the Self Service registration. For example their profile is missing the Full Name. 
4. FusionAuth redirects the user to complete registration by setting the Full Name.
5. The user completes registration and is logged in


#### Existing User, not registered 
1. Your application redirects to the FusionAuth OAuth2 login page
2. The user an account already but it not yet registered for your application. (for example they have an account in the chat application, but not the forum, or something like that)
3. The user is authenticated and then they are redirected to the registration page to complete registration for the new application.
4. The user completes registration and is logged in


In your use case, when are you trying to redirect the user to the registration page, and how do you identify when the user should be redirected there? For example, when do you know if they have an account, don't have an account, have an account but are not registered, etc?

**Comment by Nosherwan** [comment]
@robotdan that is a good question as I would like to understand this more.

So far my understanding is:

1. we just redirect to the oauth login page at `/oauth2/authorize?` endpoint in fusionAuth with code,client_id & redirect_uri.
2. That page then has everything (login/register/forgot password) so far I have tested both login and register and in both cases the tokens plus user_id is passed back to our server app on the redirect_uri. So as far as we are concerned we have the `user_id` & `access_token`, we can potentially further inspect via introspection/user info endpoints to see user_details, which we dont want to store.
3. We are not worried about user details, as they will always be available on introspection/user info. We havent reached that stage in development to identify those requirements yet.
4. At this point our web server app stores the tokens and only sends back `access_token` to the front end app, plus any details like username etc for either(new/existing) user. We will leave it with the apps to refresh access_token just before it expires and send our web server app a request.

However according to your description above I have another question as follows:

In our current scenario the redirect or request to `/oauth2/authorize?` allows us to control where the user in the app ends up after the redirect, which would be in our specified web app. In all the cases you have described above how would fusionAuth redirect the user back to where they started from?

So does our strategy or scenario seem viable from the point of view of fusionauth or is there a better way? :)

**Comment by robotdan** [comment]
> In all the cases you have described above how would fusionAuth redirect the user back to where they started from?

The end of each example I described acts just like a login completion. In other words, from your end it will be transparent, the user will be redirected back to your app the same as if self service registration was not enabled. There will be no change in how you expect the user to return to your application. 

Did that answer your question? Have you been able to try self service registration using each of the example flows I described?

**Comment by Nosherwan** [comment]
I have tried at-least one example. 
where my app takes user to fusionauth login page, then I register as a new user it re-confirms my password ( I assume this is self service registration), it asks for firstname, lastname (they are enabled), and then redirects the app to our web server app. But this is all triggered by redirecting to `/oauth2/authorize?` endpoint.
If however I understand correctly we probably dont have to do the redirect, we simple have to forward the user to fusionauth login page, and because it has the callback uri already defined it will always redirect back to that url?

**Comment by robotdan** [comment]
> If however I understand correctly we probably dont have to do the redirect, we simple have to forward the user to fusionauth login page, and because it has the callback uri already defined it will always redirect back to that url? am I right?


You've got it. You use the FusionAuth login page, and you get the rest for free.

**Comment by Nosherwan** [comment]
However the registration link doesnt show up, I think redirect from our app is required for that.

**Comment by robotdan** [comment]
Hmm., ok, so you have Self Service registration enabled for the application in question that owns the `client_id`? 

Self Service registration was added in `1.4.0`, if you have enabled a theme and modified the `authorize.ftl` template you may not have the latest version. Is that possible?

**Comment by Nosherwan** [comment]
@robotdan I think we are on the same page just to clarify I send users from my web app to the following ur: `https://my.fusionauth.com/oauth2/authorize?client_id=xxxxxxxxxxxx&response_type=code&redirect_uri={your URI here}` that represents the application that has Self Service Registration enabled. This page has login plus registration links.
I am on version `1.6.0` right now.

**Comment by robotdan** [comment]
>  I think we are on the same page just to clarify I send users from my web app to the following url: https://my.fusionauth.com/oauth2/authorize?client_id=xxxxxxxxxxxx&response_type=code&redirect_uri={your URI here} that represents the application that has Self Service Registration enabled. 

This sounds correct. 

The redirect that you build to FusionAuth does not change just because you have Self Service registration enabled. 

You should see a login that looks like this:

![image](https://user-images.githubusercontent.com/1148709/57005129-670fd980-6b92-11e9-9ae4-4646919f90fb.png)

**Comment by Nosherwan** [comment]
Confirmed I can see similar page as that screenshot you have just provided above.

**Comment by robotdan** [comment]
> Confirmed I can see similar page as that screenshot you have just provided above.


Does that all make sense then? You'll just redirect to the `/oauth2/authorize` URL and we'll take care of the rest. Feel free to open other GitHub issues if you get stuck on anything or want to provide additional feedback.

**Comment by Nosherwan** [comment]
Thanks alot @robotdan yes it does all make sense now. I will definitely refer back to issues here or create more if required. 👍🏼

**Comment by LucasPiffer** [comment]
Hi @robotdan I think I'm experience a slight different issue which I believe to be a configuration problem rather than a bug. I have a route inside my application that redirects the user to authorize url. At first time, opening in icognito mode after 20 minutes without interact, it fails. At second attempt it works. I had two different errors one of them is auth_code_not_found and for one specific error I got AuthenticatedNotRegistered for userState. Could you help to understand what may be causing this behavior? Using version 1.23.3

**Comment by mooreds** [comment]
@LucasPiffer we don't really respond to closed github issues (other than with this kind of message :) ).

If you have a support contract, please open a support ticket, which you can do from your account portal. 

If you have a question or concern, please post on the forum: https://fusionauth.io/community/forum/ 

If you have a bug with replication steps, please open a new issue in this repo. Feel free to reference this issue as a related one.

These different steps help us provide support for our customers and community. Thanks!

**Comment by LucasPiffer** [comment]
Thanks
