### ISSUE TITLE
How to change user avatar image on FusionAuth?

### ISSUE THREAD

**Issue by ngoc199** [FusionAuth/fusionauth-issues#1513]
Please consider posting your question on the [FusionAuth forum](https://fusionauth.io/community/forum/).

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

I am really new to FusionAuth.

When I navigate to the user in the Admin, I can't change the avatar image, even the avatar of my admin account.

I keep going through all the tabs, but found nothing 😞

So how do you change the avatar image on FusionAuth in your videos?

P/s: I have posted the question on the forum, but seems like no one saw it :(

**Comment by mooreds** [comment]
Closing this as a support issue.

The forum is the correct place for asking support questions (unless you have a paid plan, in which case please open a support ticket via the account portal).

I see you asked here: https://fusionauth.io/community/forum/topic/1391/how-to-change-user-avatar-image-on-fusionauth

As documented here https://fusionauth.io/technical-support/ we try to answer support questions not otherwise addressed by the community weekly.
