### ISSUE TITLE
Add support for response_mode=form_post during Implicit grant

### ISSUE THREAD

**Issue by bertiehub** [FusionAuth/fusionauth-issues#159]
authorize responce_type=id_token&response_mode=form_post returns a query

Version 1.5.0 did not return 'id_token', but 'code'. That was not a problem.
Version 1.6.1 returns 'id_token', but uses redirect (response_mode=query). Maybe the next version could use 'form_post' instead.

**Comment by robotdan** [comment]
Hi  @bertiehub , can you please expand upon the issue? 

We do not currently support the `response_mode` parameter, and therefore do not support the `form_post` for any grant type. I do not believe there was any change in this behavior between `1.5.0` and `1.6.1`.

Support for implicit grant was new in `1.5.0`, so when requesting the Implicit Grant by providing a `response_type` of `id_token`, we will always return this value using the `fragment` response mode (never `query`).

When using the Authorization Code grant, we always use the `query` response mode. 

Are you requesting that when requesting `id_token` as the `response_type` for the Implicit Grant that we optionally support the use of `form_post` as the `response_mode`? 

We can certainly look at adding this support. The more ideal approach is to not use the Implicit Grant, it is much less secure than the Authorization Code Grant. Is there a reason that you need to utilize the Implicit grant instead of the Authorization Code grant?

**Comment by bertiehub** [comment]
yes, it is better to use "code". No problem. 
But the authorize response is different in 1.6.1. 1.5.0 returns code, 1.6.1 returns id_token (if id_token was requested).  
The client code (AspNetCore.Authentication … yes, it is another story) could not handle query/get response having id_token ( I would have implemented it).

This shows the difference:
1)
FusionAuth version 1.6.1
========================
(enabled grants: Authorization Code,Implicit, Refresh Token)
redirect (client-->fusionauth):
http://localhost:9011/oauth2/authorize?client_id=ff9dfb92-188
qs parameters:
client_id: ff9dfb92-188e-47a1-a9df-f18e87450d58
redirect_uri: http://10.250.0.156:5002/callback
response_type: id_token
scope: openid
response_mode: form_post
state: CfDJ8KiyLDK4QWpHkFnXuzPozvBPHspFPwlQ698fhi7ePAm3YC6mqX
x-client-SKU: ID_NETSTANDARD2_0
x-client-ver: 5.3.0.0

redirect (fusionauth-->client):
http://10.250.0.156:5002/callback#scope=openid&state=CfDJ8Kiy
qs parameters:
scope=openid
state=CfDJ8KiyLDK4QWpHkFnXuzPozvBPHspFPwlQ698fhi7ePAm3YC6mqXt
userState=Authenticated
id_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImVITTBH



2)
FusionAuth version 1.5.0
========================
(enabled grants: Authorization Code,Implicit, Refresh Token)
redirect (client-->fusionauth):
http://localhost:9011/oauth2/authorize?client_id=0933c1af-a1b
qs parameters:
lient_id: 0933c1af-a1b1-4ba2-9592-7747a277eb42
redirect_uri: http://10.250.0.156:5002/callback
response_type: id_token
scope: openid
response_mode: form_post
state: CfDJ8KiyLDK4QWpHkFnXuzPozvCViL0G7fe_IbG7uh8btsOL0t2VM1
x-client-SKU: ID_NETSTANDARD2_0
x-client-ver: 5.3.0.0

redirect (fusionauth-->client):
http://10.250.0.156:5002/callback?code=oZjE5-o_7o6S_h_LTHt1Rh
qs parameters:
code: oZjE5-o_7o6S_h_LTHt1Rh2GsKxuTKopl3IgRtg24M8
state: CfDJ8KiyLDK4QWpHkFnXuzPozvBOG5Gn_7W-INF8FY2hD_dQ0EDSUZ
userState: Authenticated

**Comment by robotdan** [comment]
Thanks for that additional info - that is helpful. Do you have self service registration enabled? 

We fixed a bug that was in 1.50 where we returned a `query` response instead of the `fragment` for the implicit grant when self service registration was also enabled. 

We should have never been returning a `query` response to the implicit grant, this was a bug and outside of the OAuth2 specification. 

Let me know if that clears it up, or if I am still misunderstanding. Thanks!

**Comment by bertiehub** [comment]
I have self service registration ON.
If the client asked "id_token", 1.5.0 returned code after user creation, and also, if the user already exists. (this was handled ok by the client)
1.6.1 returned 'code' after user creation, but id_token if the existing user was just logging in.
(now I use 'code'. That is fine. Maybe an idea of getting id_token in form_post comes from an analog to SAML post)

**Comment by robotdan** [comment]
Available in 1.11.0
