### ISSUE TITLE
When adding a user action via the admin ui and you enable a webhook, you see an email template dropdown

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1602]
### Description 

When adding a user action via the admin ui and you enable a webhook, you see an email template dropdown. You should only see that when you enable the email template sending.

### Affects versions
1.33.0

### Steps to reproduce

1. Log in to the admin UI
2. Navigate to System, then User Actions
3. Add a new user action
4. Enable 'send to webhook'

You will see a dropdown for 'start template' but that contains email templates.

### Expected behavior

Only show 'start template' when 'email user' is enabled.

### Screenshots

![Screen Shot 2022-02-17 at 2 29 45 PM](https://user-images.githubusercontent.com/91825/154574034-d5e4e5e7-59e9-49a3-926c-e79c44e11dfc.png)

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
I don't know that this is accurate. We optionally render an email and send the rendered template in a webhook w/out sending it. This was so that the receiver could send it w/out having to render the template themselves -this was a holdover from CleanSpeak, not sure if anyone ever uses it that way. 

I can look at the code to verify that is the intended case to verify my assumption is correct.

**Comment by mooreds** [comment]
Okay, appears to be working as designed in this case.
