### ISSUE TITLE
What is the difference between "monthly" daily active user and the "monthly active user"

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#161]
Here two graphs:

- from "daily active user" with "monthly" as dimension:
<img width="1018" alt="Screen Shot 2019-05-14 at 10 33 24 AM" src="https://user-images.githubusercontent.com/1580512/57675725-d0342a00-7633-11e9-8ab9-6473ec708b7f.png">

- from "monthly active user"
<img width="933" alt="Screen Shot 2019-05-14 at 10 33 32 AM" src="https://user-images.githubusercontent.com/1580512/57675738-da562880-7633-11e9-857d-50cd49d427ac.png">

Could you explain what is the difference and why the numbers are different?

**Comment by voidmain** [comment]
Hi @blanchonvincent. The difference is how the number of logins are counted. Let's say that you have a user named John. If John logs in 4 times on Monday May 13th, he will be counted as 1 Daily Active User for Monday and 1 Monthly Active User for May. If John then logs in 2 times on Tuesday, he will be counted as 1 Daily Active User for Tuesday and 0 Monthly Active User for May. This is because he has already been counted for May but not for Tuesday.

Let's assume that is all John logs in and he is your only user. At the end of the month, your statistics will look like this:

Daily Active Users (summed up for May): 2
Monthly Active Users (for May): 1

This is why the Daily Active User numbers are higher when you roll them up to a monthly view.
