### ISSUE TITLE
User can create account with invalid email

### ISSUE THREAD

**Issue by pablomadrigal** [FusionAuth/fusionauth-issues#1625]
### Description 
Users can sing up with emails which do not contain a domain value ie ‘com, net, org’ etc…

### Affects versions
1.30.2

### Steps to reproduce

1. Open one application with registration form
3. Enter the following values:
- Email: test@invalidmail.
4. Submit the form

### Expected behavior
Email field should display a message indicating ‘Invalid Email’

### Additional context
We have already try with Regex in the validation for the email in the "Edit Field".
To get there:

1. Go to Fusion Auth admin page
2. Go to  "Customizations" on the sider menú
3. Go to Form Fields
4. Modify the "email" field
5. Add "validation"
6. Use some Regex for the field

![Error FA email](https://user-images.githubusercontent.com/22465189/157303499-b0b290a5-7364-4d8d-a09c-565498119037.png)

**Comment by mooreds** [comment]
Just to confirm, you have a valid license and have entered it in the Reactor page, correct?

**Comment by pablomadrigal** [comment]
It's correct

**Comment by mooreds** [comment]
I am unable to replicate with this regular expression: `^[^@]*@[^@]*\.[^@]*$`. However, I'm on 1.32.0. Can you test that version and see if you still see the issue?

**Comment by robotdan** [comment]
I can confirm that `test@invalidmail.` passes. 

We are relatively lenient because there isn't an agreed upon standard for what a deliverable address is. There are some basic rules, lots of other complex rules, and then it is up to the MX to decide if it is deliverable. So the one true test is to perform email verification. If the user can receive an email at the specified address, it is valid. 

That being said, this may just be a miss our validation logic. 

We can investigate further.

**Comment by robotdan** [comment]
Internal
- https://github.com/inversoft/inversoft-validator/commit/b83ab0b327204fd7cd606ce89b313e3451234032
