### ISSUE TITLE
No "user.update" Webhook after email verification.

### ISSUE THREAD

**Issue by unkis** [FusionAuth/fusionauth-issues#163]
### Description 
Hello no "user.update" Webhook after email verification with setup password.
 
if you create a user via API and go to email and click on the setup password link and after up you pass

### Steps to reproduce
0. setup "user.update" Webhook
1. create a user via API without password but with email verification
`{
  "sendSetPasswordEmail": true,
   "user": {
  	"email": "<your Email>"
  }
}`
2. Go to Email and click on the link to confirm the email and setup the password
3. setup the password and click ok
4. No "user.update" Webhook would be sendet :(

### Expected behavior
"user.update" Webhook should be sent with user and password information.
or new Webhook event must be created maybe "user.email_verified" or something like that

### Platform
© FusionAuth 2019 
FusionAuth™ version 1.6.1

### Additional context
Any other Webhooks are working.

**Comment by robotdan** [comment]
Hi @unkis thanks for reporting this issue. You're correct, currently the `user.update` event is not sent when the user's email address is marked as verified. 

I'll review with the team to see if we want to fire the full update event, or add a new event type as you suggested. 

Thanks.

**Comment by prabhakarreddy1234** [comment]
@robotdan  we have similar requirement to update `verified` status in our database through webhook. Also if webhook supports password change event that would be great.

**Comment by robotdan** [comment]
Thanks for the feedback @prabhakarreddy1234, we'll review this request.

**Comment by prabhakarreddy1234** [comment]
@robotdan  Any ETA on this would be helpful in our planning. This is a bit of blocker for us in completing the user flow.

**Comment by robotdan** [comment]
I can likely get it in the upcoming release, but no current ETA on that. 

For anyone on this thread, do you have a preference for the `user.update` event, or a new event type of `user.email.verified`. 

Leaning towards `user.email.verified` because it does not occur due to the Update User API, but because of a separate workflow.

**Comment by prabhakarreddy1234** [comment]
Thanks. I prefer `user.email.verified`

**Comment by robotdan** [comment]
FYI, whatever we add here for a new event type, we'll likely mimic for the User Registration verification. This is a similar work flow to email verification. 

For example, we'll likely then also add `user.registration.verified` for the Registration Verification event.

**Comment by davidmw** [comment]
@robotdan for our planning purposes it would really be very helpful to understand where this webhook / event will appear on your schedule.  Can you share anything on it?

**Comment by robotdan** [comment]
HI @davidmw it is possible we can get this into the upcoming 1.8.0 feature release. I would expect to have that out mid-to-late July. 

Schedules may change since we provide preference clients purchasing support contracts or professional services, etc. This means it is possible for other work to come up that may take precedence. 

Thanks!

**Comment by davidmw** [comment]
@robotdan thanks and happy to see this assigned now!
