### ISSUE TITLE
new JWT claims and doc reserved claims

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#1669]
### Description
1. add `tid` and `auth_time` claims. 
2. Add `tid` and `amr` to the existing reserved claims list.
   - Reserved `amr`, `exp`, `iat`, `sub` and `tid`
   - Reserved for Vending API `amr`, `exp` and `iat`
   - Reserved for Client Credentials `amr`, `aud`, `exp`, `iat`, `permissions`, `sub` and `tid`.
3. Add header claim `gty` (grant types) which is immutable and contains a list of one or more claims in order of use.
   - Example: `authorization_code, refresh_token` would be in a JWT that was returned from the Refresh Grant when the original request began with an authorization code grant.  

Note, `amr` will likely be added under #1484 or #1491. 

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1484
- https://github.com/FusionAuth/fusionauth-issues/issues/1491

### Documentation
- [x] Updated reserved claims for various grant types
- [x] New claims can be returned in JWTs, review Token doc, Login response doc, and OAuth2 endpoint response doc
- [x] New `gty` header claim

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by matthewhartstonge** [comment]
I would like to make a motion to reverse the reservation of claims...

Our lambdas (both user + client creds) were/are configured to inject our API endpoint as the intended audience (a common use case when setting `aud` for validating server side - even seen it in your examples 😉). Our apps and external API consumers both talk to our API endpoint (the intended audience). This makes the validation a bit more painful due to the split brain situation (user tokens can set an `aud` and client credential tokens could, but now can't as it's now reserved/overwritten).

When designing our SaaS we (and I'm sure others will as well) specifically referred to and used the OAuth2.0 RFCs, JWT RFCs and other references to reserved claim names when designing our user and client credential tokens. The `v1.36.X` reservation of `tid` caused an issue too, as we run a multi-tenanted SaaS product and used this claim to inform clients what tenants they had access to, luckily, we were able to work around that by configuring a `allowedTenants` claim instead. We have been using the data component within user and client (entity) records to store scopes, roles, permissions, allowed tenant access and more based on application logic, so it's a pain to now have:

1. Extra unused baggage within the JWT payloads that can't be removed.
2. To patch around and design different logic pathways/attributes when we are using the RFC claims as intended.

I guess the question is - are these claims _required_ for FusionAuth to do it's thing (with exception to the token introspection endpoint, but even then, this should only require a `jti`, `sub` or some other linking id that could be contained maybe within the JWT header) or can they be _set by default_ and FusionAuth enable the claims to be overriden? 🤔 

 * As far as I can tell, there doesn't seem to be a requirement by FusionAuth to reserve these claims as the access token isn't used for the FusionAuth API endpoints - as that's what the FusionAuth API tokens are used for...
 * I don't mind the claims initially being set by default based on the internal FusionAuth permission/app bindings
 * BUT - I would like them to be _overridable_ given it's third-party applications being catered for. 

The paradigms that FusionAuth have may not align at all times with how clients need to use the system when dispensing tokens. As the token is intended to be sent back to the developer's application and backend services, I would hope that the tokens can work for the developer first and foremost (obviously while enforcing security as best as possible).

The other option, if there are claims _required_ by FusionAuth - are you able to namespace them? i.e. `fa-tid`, `fa-aud` e.t.c.

sidenote: I guess I also don't want to have to play jwt claim cat+mouse in terms of having to work around claims as they become reserved in newer versions 😂

**Comment by robotdan** [comment]
Thanks for the feedback @matthewhartstonge this is an issue we have discussed at great lengths. The primary motivation for reserving claims is security. 

If we did not have any reserved claims and allowed a lambda to mutate all claims, in general this would be ok as long as FusionAuth will never use the JWT itself. That is to say, "modify the claims at your own risk" because it is your application that must then trust the token, not FusionAuth. 

However, there are some conditions where we end up using the JWT. In these cases, there are privilege escalation paths and account takeover vectors that we want to protect against. 

For example, in the normal JWT for a user login, the following are now reserved `amr`, `exp`, `iat`, `sub` and `tid`.  

- `exp` and `iat`, I don't know if there is any objection to these in general since they control expiration.
- `sub` - since this is a "registered" claim, and it represents the user for which the JWT represents, this seems like a good candidate to reserve. 

The `tid` is new, and in theory we could modify this decision and remove it from the reserved list. This makes life a bit harder for FusionAuth because we have to have a way to consistently identify the user and tenant. We can always identify the tenant by the `sub` claim because the User Id is currently globally unique across tenants. However, I'd like the option to make the userId unique within a tenant only to allow for some additional use cases where a userId is hard coded to match an external FK of some sort. If we were to make this change in the future, then the `sub` would no longer be guaranteed to be unique in a tenant, and I'd have to have some consistent way to identify the tenant in which this user (`sub`) exists. 

We reserved these claims so that we can trust them and use them ourselves to validate the claims within the JWT and to protect ourselves from account take over and escalation attacks. 

For example, the new support for SCIM server uses a JWT produced by the client credentials grants between entities, and we plan to add this same support for API authentication. Without reserving some claims, we could not protect ourselves from a user with access to modify a lambda from becoming an admin user, or making a SCIM call to create an admin user, etc. and taking over the entire system. 

I do understand there are some consequences to these decisions, and we do try to weigh these risks when we make changes such as this one.

Your comment about cat+mouse is a good one, and we don't want that either. We have actually discussed name spacing all of our reserve claims as you suggested such as `fa:`, or `fa-`, we could revisit that decision.  

Another possible option would be to expose this as configuration, and if we decide to add new reserved claims that could impact existing users we only enable them as reserved for new installations, and leave existing instances as they are but add the new claims as options to the configuration. This of course opens us up to the potential security issues I described, but we could warn the user that modifying the list of reserved claims can be dangerous if you don't understand the risks or provide anyone access to modifying a populate lambda, and then hand the user the foot gun. 😁

**Comment by robotdan** [comment]
For anyone that added a 👎 to the above thread - if you want to open a separate issue and document your use case and possible solutions to fit your needs, that would be helpful. 

Thanks!

**Comment by matthewhartstonge** [comment]
Uh, foot gun?? 

I think you mean:
![image](https://user-images.githubusercontent.com/6119549/167968401-8544e984-8ddc-436d-8b5e-8c4f35601ddc.png)
😂

Memes aside, I think either of those proposed options are great. 😄 
I'll open a GH issue and link back.

In regards to privilege escalation, a part of me says, if you're entrusting a non-admin staff member to be able to touch the lambdas, you've already waiving potential privilege escalation concerns within your own app..
So like, only let an admin send it after code review :joy:
But hey, zero trust and whatnot.
I hear that. 👌
