### ISSUE TITLE
Select multiple tenants on application

### ISSUE THREAD

**Issue by Lg0enga** [FusionAuth/fusionauth-issues#167]
### Problem
For my architecture I have multiple tenants for one application. I would like to know if it is possible with FusionAuth that there can be more tenants on one application in the future.

### Solution
I would like to select multiple tenants when creating an application. This allows me to save a connection string to the tenant and use the same application with multiple tenants with other database connections for my application

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Hi @Lg0enga thanks for taking the time to open this issue. 

An application can only live in one tenant by design, there are no plans to change this architecture. If you can explain your use case a bit further, I may be able to suggest an alternative approach.

**Comment by Lg0enga** [comment]
Thanks @robotdan 

I have an application that multiple companies can log in to. The companies are the tenants.
One tenant (company) has its own database and its own users, but use the same application.

So all tenants (companies) use the same application with their own database and own users.

My idea was to use a tenant to build a connection string for the logged-in user in the application used by multiple tenantes.

**Comment by robotdan** [comment]
You'll likely just want to create an application per tenant. In this case each application will represent the same application on your end. 

A common way this is done is by modifying the sub-domain. For example, Zendesk provides each client a different URL so that they know who is logging into their website. Zendesk is one application, but each of their clients is a "tenant" in that I have my own namespace for email addresses for my agents. 

If your company is `Acme. Corp`, your Zendesk URL may be `https://acme.zendesk.com`. This way when you access the URL Zendesk can provide the appropriate login mechanism. 

In a similar way, you may want to build a similar model so that when a user from Company A wants to access your application, using the URL you'll know how to build the URL to FusionAuth with the correct `client_id`. 

To circle back to the Zendesk example, without this sub-domain namespace, or some other identifier for a client, Zendesk would not know how to log you into the agent backend service. 

There are different strategies for this, the sub-domain is just one option. Hope that helps.

**Comment by Lg0enga** [comment]
Thanks for help @robotdan!

I solved it with sub-domains. Works perfect for me this way.
