### ISSUE TITLE
Is there a way to get the JWT exp in the response object?

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#168]
### Description
I'm currently login in users using the `/api/login` endpoint. In my app, every request needs to check if the JWT is still valid (not expired).
I know I could decode the JWT to check the exp date. But I was wondering if there's a way to get that info in the first `/api/login` request.
Thanks!

**Comment by robotdan** [comment]
I think what you're asking is if the Login API response could return a human readable expiration of the token? This isn't currently available. 

Since you're using the Login API, the OAuth2 equivalent would be the Password grant. 
https://fusionauth.io/docs/v1/tech/oauth/endpoints#resource-owner-password-credentials-grant-request

This response will return an expiration. 

```
{
  "access_token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0ODUxNDA5ODQsImlhdCI6MTQ4NTEzNzM4NCwiaXNzIjoiYWNtZS5jb20iLCJzdWIiOiIyOWFjMGMxOC0wYjRhLTQyY2YtODJmYy0wM2Q1NzAzMThhMWQiLCJhcHBsaWNhdGlvbklkIjoiNzkxMDM3MzQtOTdhYi00ZDFhLWFmMzctZTAwNmQwNWQyOTUyIiwicm9sZXMiOltdfQ.Mp0Pcwsz5VECK11Kf2ZZNF_SMKu5CgBeLN9ZOP04kZo",
  "expires_in" : 3600,
  "id_token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0ODUxNDA5ODQsImlhdCI6MTQ4NTEzNzM4NCwiaXNzIjoiYWNtZS5jb20iLCJzdWIiOiIyOWFjMGMxOC0wYjRhLTQyY2YtODJmYy0wM2Q1NzAzMThhMWQiLCJhcHBsaWNhdGlvbklkIjoiNzkxMDM3MzQtOTdhYi00ZDFhLWFmMzctZTAwNmQwNWQyOTUyIiwicm9sZXMiOltdfQ.Mp0Pcwsz5VECK11Kf2ZZNF_SMKu5CgBeLN9ZOP04kZo",
  "refresh_token": "ze9fi6Y9sMSf3yWp3aaO2w7AMav2MFdiMIi2GObrAi-i3248oo0jTQ",
  "token_type" : "Bearer",
  "userId" : "3b6d2f70-4821-4694-ac89-60333c9c4165"
}
```

The `expires_in` value is seconds from "now". Would that work for you? 

The Password Grant can be called from a backend similar to the Login API, you'll need to pass a `client_id` instead of an `applicationId` and the request body is form encoded instead of JSON.

**Comment by robotdan** [comment]
Hi @AlvMF1 was there anything else I can help you with on this issue or an outstanding feature request that we should open to satisfy this requirement? 

If not, I'll close it out. Thanks!

**Comment by AlvMF1** [comment]
No, I'm good. Thanks!
