### ISSUE TITLE
All system emails fail to send, but test email works 

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1742]
### Description 

System emails fail to send, but test email send works fine to multiple addresses.

### Affects versions

1.36.4 on FusionAuth cloud (business)

### Steps to reproduce

Hard to reproduce, just happened one day. When it happens, tried the following troubleshooting steps:

* sent test email to different domains (again, this works)
* reviewed the email templates
* tried different actions that should trigger email (
* set `smtp.debug=true` per the https://fusionauth.io/docs/v1/tech/admin-guide/troubleshooting#troubleshooting-email section

Only had one tenant.

No configuration was changed between when emails were sent and when they were not.

### Expected behavior
Emails should continue to be sent.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context

Here's the forum post: https://fusionauth.io/community/forum/topic/2091/all-system-emails-fail-to-send-but-test-email-works

Rebooting the instance fixed the issue; system emails were then sent.

Using mailgun on port 587 with TLS.

**Comment by voidmain** [comment]
That's quite odd. If anyone hits this issue, before restarting FusionAuth, please take a thread dump and a heap dump and let us know. We might be able to analyze those and figure out if there is an internal issue with JavaMail or something else perhaps.

**Comment by robotdan** [comment]
Sounds like a threading issue since any emails sent at runtime are threaded off, and the test email is sent in the current thread. As @voidmain mentioned we'd need a thread dump or something like that to take a guess at this one.

**Comment by mooreds** [comment]
Note this happened on FusionAuth cloud. If this happens to anyone else on FusionAuth cloud (cc @shortstack :) ) please let us know and we'll take the needed diagnostic thread/heap dumps. If someone else sees it running self-hosted, please share that info. If it contains sensitive information, please post to this issue and we'll work out a secure transport.

**Comment by dengste** [comment]
We have the same problem since last week. Test emails work fine, but password reset mails are not delivered. We have verified multiple times that the SMTP gateway works fine (which should be clear anyway, since the test mails are delivered). We also tried various different recipients. I even put in my private SMTP relay server to which I have full log access, and I can say without a doubt that our FusionAuth instance does not even try to contact the server for sending the password reset mail, although the logs say a mail was sent.

Needless to say, this is a pretty serious issue for us and impacting us heavily. We are on the Business Hosting + Starter Plan and have opened a ticket with you guys last week, but after some initial communication, we unfortunately haven't heard back. Last communication from you was from a week ago, and further communication from us this week remains unanswered, so I hope by reaching out through GitHub I might be more successful. I'd very much appreciate if you could take a look at the ticket (ID is 73190), or please tell me how to proceed to get help on this.

**Comment by robotdan** [comment]
Was finally able to recreate and identity the issue.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/218
- https://github.com/prime-framework/prime-email/pull/2

**Comment by robotdan** [comment]
Part of the fix will be to add timeouts. 

```
mail.smtp.connectiontimeout=3000
mail.smtp.timeout=3000
```

**Comment by dengste** [comment]
Yes, I've actually seen in my SMTP server logs that the connection is kept open. So usually, the client is supposed to send a QUIT command when it's done, upon which the server will close the socket. It seems that you don't do that?
