### ISSUE TITLE
Trim whitespace from user input on backend (username/emails)

### ISSUE THREAD

**Issue by matthewhartstonge** [FusionAuth/fusionauth-issues#1779]
### Description
Currently anywhere a user submits a form that contains an input field for a username or email address, if white space is contained within the field, FusionAuth returns unable to find the person's account.

### Affects versions
v1.36.4

### Steps to reproduce
1. Go to `/oauth2/authorize`
2. Enter username, within the quotation marks: `' testuser@example.com '`
3. Enter password
4. Click Submit
5. See error: `unable to find account`

### Expected behavior
User can sign in, if account exists after being trimmed.

### Screenshots
This is purely for user experience as it is never clear when filling in forms if white space has been added accidentally to the end of an entry. The worst part is when people manage to save their credentials with pre/appended white space into their password managers.

![is there whitespace?](https://user-images.githubusercontent.com/6119549/176788235-57754c49-f378-4b96-893f-8bd3cb5cc153.png "👀 Can you tell if there is any white space?")
![image](https://user-images.githubusercontent.com/6119549/176788413-5ad854a5-ab0d-427f-a826-5536ee135a68.png "😠 Blast! You found the white space! I would've got away with it too if it weren't for you meddling developers!")  

### Platform
(Please complete the following information)
 - Device: Any
 - OS: Any
 - Browser + version: Any

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
- We have migrated from another auth service that already trimmed whitespace on user input fields.

### Workaround
Currently, the workaround is to slap some JavaScript into the themes to counter this, which works, but isn't great from a migration point of view where the old auth service already trimmed for users:

`_helpers.ftl`
```ftl
[#macro jsTrimElements]
<script>
  function trimElements(elementIds=[]) {
    for (let i = 0; i < elementIds.length; i++) {
      let element = document.getElementById(elementIds[i]);
      if (element) {
        element.value = element.value.trim();
      }
    }
  }
</script>
[/#macro]
```

email `verification.ftl`, oauth `authorize.ftl`, oauth `register.ftl`, oauth `passwordless.ftl`, `forgot-password.ftl`
```ftl
[@helpers.html]
  [@helpers.head]
    ...
    [@helpers.jsTrimElements /]
  [/@helpers.head]

  [@helpers.body]
    [@helpers.header]
      [#-- Custom header code goes here --]
    [/@helpers.header]

    [@helpers.main title=theme.message('login')]
      ...
      <form action="authorize"
        method="POST"
        onsubmit="trimElements(['email', 'username', 'loginId', 'parentEmail', ])"> [#-- Inject the js array of required elements to be trimmed here --]
        ...
```

**Comment by robotdan** [comment]
Internal:

Needs some more review, but we could update the contract of the login Id (username and email) that it cannot contain leading or trailing spaces. If the value does, they will be removed during creation or updating. 

And then during login we could also always trim.

The risk here is that we are assuming removing leading and trailing spaces does not affect the canonical version of the login Id. So be absolutely certain of this you actually have to know the type of "login Id" - i.e. is this a username or email, and then know what the rules for canonicalization.

**Comment by glen-84** [comment]
FYI: https://fusionauth.io/community/forum/topic/1762/how-to-trim-input-fields

Can you explain how leading and trailing whitespace is ever intended/expected/useful? I can't think of any examples.

I mean, an email address with leading or trailing whitespace is not even valid, and when have you ever seen a username with whitespace around it? 🙂

I consider this a bug.

**Comment by robotdan** [comment]
I think I outlined the reasons in quite a bit of detail int he above comment. 

But I can try and provide additional information. 

The Login API which is used by end users of FusionAuth as well as our own login page takes a parameter called `loginId`. A login Id can be either an email address or username. 

That is to say, login does not know if the value you enter is an email address or username. There is no agreed upon way to canonicalize a username. 

Users of FusionAuth may utilize the username to store a username, phone number, email address, gov unique Id, or any other unique Id or fabricated identifier unique to their use case or business domain. 

Therefore, if we begin trimming this value, we are making an assumption that the end user of FusionAuth does not allow leading or trailing whitespace for their current usage of this value.

Additionally, we would have to make the assumption that to date, no customer has stored a value that contains a leading or trailing whitespace. 

For all of these reasons, and because this can be solved w/out changes to FusionAuth as described above, I do not consider this a bug, and do not plan to change the current behavior of FusionAuth.

You don't have to agree - but I hope that helps you understand my perspective

**Comment by glen-84** [comment]
`username` I've never seen usernames with leading or trailing whitespace.
`phone number` I've never seen phone numbers with leading or trailing whitespace.
`email address` Not valid.
`gov unique Id` I've never seen government IDs with leading or trailing whitespace.

Do you have other examples? I wonder that Auth0 and others do.

Imagine printing out your login ID – how would you know if it had trailing whitespace?

How is it considered secure for one person to have the ID `robotdan`, and another to have the ID `robotdan `?

I would personally even go further and trim passwords and other input data as well, but I won't go there now. 😛

> we are making an assumption that the end user of FusionAuth does not allow leading or trailing whitespace for their current usage of this value

I think it's a fair assumption to make.

> make the assumption that to date, no customer has stored a value that contains a leading or trailing whitespace - even if they did not intend to store it that way initially

It could be corrected with a migration, or an option could be added to trim leading and trailing whitespace (enabled by default in new deployments).

You're asking almost all users to make a change to the software because 1 or 2 may have really bizarre requirements.

**Comment by glen-84** [comment]
This got me yesterday when I was signing into our app and the Android keyboard auto-completed with a trailing space. I couldn't understand why my sign-in details were not working.

I wish you would reconsider. Yes, everyone can implement this themselves, but that just seems silly when almost everyone requires this.

**Comment by mstepin** [comment]
I would say I agree with pretty much all of glen-84's sentiments above (apart, of course, trimming passwords, but thats outside the scope of this issue anyway :D ).
This seriously needs to be reconsidered, at the very minimum as a **configurable** option (to avoid a riff between FusionAuth and their very few customers who have bizarre requirements allowing their users to have leading or trailing spaces on their usernames, irrespective of username type)

**Comment by glen-84** [comment]
@mooreds FYI.

**Comment by mooreds** [comment]
Thanks Glen, duly noted. We appreciate community feedback, but I think that @robotdan was pretty clear on his reasoning and the decision is made.
