### ISSUE TITLE
Filtering managed domains at login

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#178]
### Problem

Background:  https://github.com/FusionAuth/fusionauth-issues/issues/176#issuecomment-500492264

We are facing a use case that calls for creating many SAML Identity Providers for a single application. Each (or many) customers will have a managed domain configured with us.

When our list of registered Identity Providers exceeds a dozen or so it will be annoying and error prone to require each user to identify their organization / domain in the UI prior to login.  

Can we optionally supply the managed domain as a URL parameter so that FusionAuth shows the needed Identity Provider button on the login screen?

#### Domain Filter

When providing the domain or email address in the `login_hint` request parameter, and an IdP is configured to manage the domain, the login page can be skipped. 

#### Identity Provider Hint

Optionally provide an `idp_hint` query parameter when redirecting to the FusionAuth `/oauth2/authorize` endpoint to cause FusionAuth to bypass the login page and redirect directly to the requested IdP. 

You may also provide the `login_hint` and this value will be passed along to the target IdP.

### Notes

My guess is this will only work for redirect based IdPs, such as SAML and OpenID Connect. In theory we could make this work for Twitter, Google and Facebook, but but I don't know that this is a use case we need to solve. Currently Facebook and Google use pop-ups, so we'd have to support redirect flows for these IdPs first.

**Comment by robotdan** [comment]
Thanks for the suggestion @davidmw  - this is a good idea. I'll have to take a look, but this sounds very doable in the near future.

**Comment by voidmain** [comment]
One question on this, will you only have a single identity provider per domain? Or will you have multiple?

**Comment by robotdan** [comment]
@davidmw to add to what @voidmain asked..  we aren't sure exactly what you're asking for, currently only a single IdP configuration can be assigned to a domain at a time. 

If you can outline the workflow as such it will be helpful, for example:

Today: 
1. Hit the FusionAuth login page
2. Type in `user@example.com` - where `example.com` is managed by `IdP A`. 
3. FusionAuth forwards the user to `IdP A` login page and does not even prompt them for a password because this user is managed by a different identity provider. 

Enhancement option 1 : scenario A
1. Hit the FusionAuth login page providing `domain=example.com` on the request URL
2. In this case because `example.com` is managed by `IdP A` we skip the FusionAuth login screen and forward the user to `IdP A` without passing `Go` or collecting `$200`. :-) 

Enhancement option 1 : scenario B
1. Hit the FusionAuth login page providing `domain=acme.com` on the request URL
2. In this case because `acme.com` is **NOT** managed by any IdP configurations in FusionAuth we show the user a normal login screen and do not prompt them for their email address before showing them the login screen with a password field. 

Can you confirm it is one of these, or something completely different you're asking for? If you're interested, it may be faster to jump on a phone call and talk through the user case to make sure we understand it. Feel free to submit a "Contact" request on the FusionAuth web page and we can arrange a brief call. 

Thanks!

**Comment by davidmw** [comment]
Yes the basic request is to support Enhancement option 1 (both scenarios).

First let me describe some edge cases:
1) in a school kids in grade 8+ are using Google sign on while younger kids are participating in a move to Microsoft
2) the domain could represent a larger organization and there are IdP configured at school or city level below that.
3) teaching staff may use different account types than students. 

We can't assume users will be accessing the service from school IPs. It is very likely that our app will be configured on an application launcher which could be configured with URL params (this is the reason for the request).

Coming from my ignorant vantage point - a possible more general solution would be an IdP configuration linked to each user account so that we don't run into domain fencing challenges. I mean the IdP could be configured in FusionAuth as today but the user profile could be linked to any of those configured IdP. When I do a bulk import of users I'd probably default that entire population on the same IdP and don't really care what email domains they use. 

Then, to login:
The user provides username or email address on the first screen. If user is managed by IdP they get forwarded to that IdP. Else user is shown a password field on FusionAuth.

**Comment by mv4208** [comment]
This enhancement would be great for our use cases:

Enhancement option 1 : scenario A

Hit the FusionAuth login page providing domain=example.com on the request URL
In this case because example.com is managed by IdP A we skip the FusionAuth login screen and forward the user to IdP A without passing Go or collecting $200. :-)
Enhancement option 1 : scenario B

**Comment by davidmw** [comment]
Another possible enhancement, seeking more flexibility and control. Let us specify, on the request URL, the IdP by name or short ID. eg: www.myfusion.com/idp/google

This forwards user to the IdP and could allow us end run around the managed domain scenario.

**Comment by robotdan** [comment]
This is a good idea @davidmw . One of the issues we closed as dup to this one mentioned a similar use case. https://github.com/FusionAuth/fusionauth-issues/issues/544

**Comment by davidmw** [comment]
@robotdan Issue #389 can probably be closed as a dup of this one.

**Comment by seanadkinson** [comment]
@robotdan Any timeline available on this enhancement?

Our use case:

* User is logged into Customer Portal with Customer IdP (portal is a separate app, not managed by us)
* Customer Portal provides a link to open our Application, which uses FusionAuth
* Our Application is configured to use Customer IdP for authentication
* User is prompted with FusionAuth login screen, and chooses Customer IdP
* Since they just came from the Customer Portal, they are usually always still logged in

What we'd like to do is get rid of the login screen in this scenario.  If we can provide the desired IdP as a query param, they will almost never see any login screen, since they just followed a link from Customer Portal, where they were logged in.

**Comment by davidmw** [comment]
@robotdan On this topic, I'm now running into a problem due to the global nature of managed domains across all tenants and applications. Our tenants are configured to support test / staging / production environments.

So lets just talk about the test environment. We have three apps and when attempting to support some enterprises and their particular SSO solution - each app is assigned a different client_id requiring that I configure one IdP per app. But the global nature of the managed domains means I can't install their email domains into each of those IdP.

It really seems like the managed domain scope should be limited to a single app.

**Comment by robotdan** [comment]
Thanks for the feedback @davidmw. 

We initially envisioned an IdP for `Acme Corp.`, and that IdP would manage all users with an email address ending in `@acme.com`. 

In your example, this this only problematic in test, or is there a production use case where you have different IdP configurations managing the same domain and then you manage the separation by only assigning an IdP to the correct application? 

In theory we could relax this restriction, if we did I think we would have to validate that any single application is only enabled for one IdP for a particular domain. This would ensure that when we show the login page with only an email address which is already scoped to a `client_id` (application) that we never have more than one IdP that can handle that user.

**Comment by davidmw** [comment]
Hi @robotdan. This is a problem in production as well. Handling it by application would certainly be an improvement. And allowing IdP identification on the URL to override this would be fantastic.

Even before this multi app issue came up, I've found a need to configure a SSO for managed domain use AND need to put the same SSO's button on the login screen.

For example, some schools tell us they want to use Google SSO. But I don't want to hide the Google button for other users. In fact keeping the Google SSO button visible can provide one-click login to managed domain users - letting them skip the email field.

So maybe an option in the managed IdP to display the button? Currently I need two IdPs for each SSO - one managed and one not to keep the button visible. I should check to see if this is a quick template update.

**Comment by robotdan** [comment]
Thanks for this use case @davidmw this is helpful.

**Comment by davidmw** [comment]
@robotdan I've found an existing solution. If I set up one IdP with managed domains, enable it for all apps in our suite, and use overrides for each app to support the multiple OAuth client_ids provided by the customer it works as needed.

Still need to create a second IdP that is unmanaged to get the SSO button to appear but this is a minor thing.

**Comment by robotdan** [comment]
@davidmw This one is delivered in 1.19.0. 

Re: Your use case to have the managed domains not be unique to an IdP configuration, if that is still something you'd like considered, please open a separate issue and just link to this thread and we'll track that separately. 

Thanks!

**Comment by davidmw** [comment]
Hey @robotdan this works great - happy to see it released!
