### ISSUE TITLE
Increasing memory usage

### ISSUE THREAD

**Issue by timameye-gantner** [FusionAuth/fusionauth-issues#1825]
### Description
We are running fusionauth in a container on AWS ECS for 9 weeks now. Since those 9 weeks our memory usage has been doubled while we only have added 40 users to the application. Is this normal behaviour?
![image](https://user-images.githubusercontent.com/99190323/184298640-10b86a1f-609b-4a06-a491-90d49e4e538a.png)
We are using the 1.36.4 image with nginx in front of it.

Could this be a potential memory leak?

Thanks in advance!

**Comment by mooreds** [comment]
@timameye-gantner Hmmm. This kind of thing is tough to diagnose.

Any other usage changes, particularly around the spikes above? 

Is this a production system or a test system that you can experiment with? If the latter, what happens if you import say 1000 users and then mark them all as inactive?

FusionAuth caches a lot of things (applications, tenants, identity providers, roles, etc) in order to be performant, so the relationship between memory used and number of users is not linear.

**Comment by timameye-gantner** [comment]
Hi @mooreds 
Sorry for my delayed response. 

This only occured on our production environment, and is only recently in use by our customers.

It could be related to caching and I'm going to keep an eye on this as the users will increase in the upcoming months.
I'll close this issue and make a new one if I notice any problems.

Thanks for your response!

**Comment by mooreds** [comment]
Thanks @timameye-gantner . Please re-open if you have more details or anything seems out of normal.
