### ISSUE TITLE
Seeking OAuth Login flexibility

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#188]
### Problem
We believe we'd like to utilise the OAuth login UI generated by FusionAuth (including password reset, password change complete, etc) to avoid reinventing the wheel and to use the IdP integration that is already in place. The email templating system doesn't meet our needs so we are using SendGrid for related communications.

We have applications established in FusionAuth to mirror the products in our product suite plus one common application that handles shared functionality (creating and logging in users).  One of our apps is for kids, one for school staff - so the UIs are different. Additionally we are multi tenant (production, development, test) which creates a 3x multiple of the apps we establish in FusionAuth.

The FreeMarker UI templates can support logic based on app id https://stackoverflow.com/questions/56382906/leveraging-fusionauth-login-verify-screens 

This is the look we want to achieve on the kids app, replacing the right hand column with typical OAuth controls: 
<img width="512" alt="Screen Shot 2019-06-19 at 3 43 01 pm" src="https://user-images.githubusercontent.com/3413901/59740651-0eb0aa80-92ac-11e9-91b1-ec21ecdd6a5b.png">

There may not be any common elements or placement with the other login screens. We need to achieve at least two sets of UI screens for our apps and the current templating system would be difficult to manage and very difficult to preview the results. The app ID for each tenant would need to be handled - something like this scattered across the templates:

[#if client_id == 'ee31103f-2fc1-4bb5-ba95-development' || client_id == 'ee31103f-2fc1-4bb5-ba95-test' || client_id == 'ee31103f-2fc1-4bb5-ba95-production'  ]

which isn't a great way to iterate on visual designs.

I see the better solution as a Vue / Javascript component that handles just the UI for the login fields (or the core fields / labels of the other templated screens).  These could potentially be served directly off the FusionAuth server or put in our release and embedded on our pages as needed.

**Comment by robotdan** [comment]
We do have plans to update our theme capability to save, import, export, share etc - and then optionally assign a different theme per tenant. 

Would this satisfy the requirement, or would you also need this to optionally be assigned per application? 

No plans currently to replace our Freemarker templates with Vue or other JavaScript component. Can you expand on that idea and how it may enhance the flexibility?

**Comment by davidmw** [comment]
I’d probably use themes on per app basis (across tenants) but you may have more customers wanting it the other way.  

I’m certainly not suggesting a FreeMarker replacement. Your planned enhancements plus a very flexible preview tool that shows rendered page (allowing us to exercise conditional logic on the templates) would be very helpful. 

As for the Vue solution - this might be a npm Vue.js component that is included in our UI as a reactive panel. That component would let us incorporate the core dynamic OAuth UI elements and should handle the FusionAuth API (or middleware API) - a login alternative with self hosted UI and factory built flow.

**Comment by voidmain** [comment]
The kicker with Vue (or any front-end framework) is that OAuth is a browser redirect based flow for the code and implicit grant types (password and client credential grants excluded). Therefore, the best integration is actually to navigate away from the Vue app, to FusionAuth and then back to the Vue app. 

On the flip-side, you can use other flows for native UIs. We've built one of these out in Angular and it covers most of the features we have in the FusionAuth OAuth UI (forgot password, setup password, MFA, registration, etc). It took a while to write it and it ended up with a lot of code to maintain but it works.

I put together a bunch of flow diagrams for all the different types of workflows that you can check out here:

https://fusionauth.io/articles/logins/types-of-logins-authentication-workflows

One other main point on the workflows is that the most secure workflow is still OAuth Authorization Code Grant because it is the only workflow where FusionAuth is the only entity managing passwords and it can secure cookies properly. The second most secure is the OAuth Password Grant. This grant requires that your Vue app make calls to your backend, which then makes calls to FusionAuth. Other workflows suffer from issues like unsecured cookies or local storage. Both of these have significant security issues that need to be considered.

**Comment by mooreds** [comment]
Can we close this one @davidmw ? Tenants support different themes now. I know this issue moved into talking about SPAs as well, so wanted to check to see if the root issue of oauth login pages flexibility had been addressed.

**Comment by robotdan** [comment]
I think the core request here is application based theme configuration? If so, we have this feature open. https://github.com/FusionAuth/fusionauth-issues/issues/769

If that is the core requirement, we can close this as superceded. I have linked this issue to #769 .

**Comment by davidmw** [comment]
Yes, happy to close this and will watch #769 with interest.
