### ISSUE TITLE
Add code delivery via email to 2FA

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#203]
### Problem
Text messaging and auth apps aside, a very common delivery of security codes is email. And apparently that's not an option.

### Solution
Present options to users on how to get the code (when enabled): text, app or email.

### Additional context
We have international users and sending text messages could not be an option. I understand that might not be the most secure way, but for our use case it would be good enough.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Thanks for the request @AlvMF1 - this is on the road map for sure. 

All we need to do is add an email template, and some configuration options, and this should be fairly easy to get put together.

**Comment by joaonice** [comment]
@robotdan how about an endpoint that returns the `code`? Then anybody can implement a generic delivery mode.

**Comment by robotdan** [comment]
Thanks for the suggestion @joaonice we have discussed something similar to this idea. We have kicked around the idea of essentially pushing the code to an endpoint (very much like our webhooks) during a login request and allow the code to be delivered however you like.

**Comment by zbruhnke** [comment]
@robotdan this feels like something that could have the email verification code you created for us a while back could be re-purposed for possibly?

**Comment by zbruhnke** [comment]
@AlvMF1 Actually thinking through this more I've realized how you could re-purpose the system as is to do what you're looking for.

There is a setting in FusionAuth your tenant settings that allows you to change the email verification to either Digits or encoded bytes and to change the number of digts or encoded bytes.

If you choose digits you could easily build a page that allows someone to type in their code like we have done in this screen shot: https://go.hmb.la/NCiHUB

Then on logout you could just reset their email to not verified every time.

This way every time they login they get dropped to this verify page.

We generated an email template that sends the code and sends it in the Email template as well.

It's not a perfect flow since you're un-verifying their email every time and re-verifying it on every single login but it does exactly what you're looking for!

**Comment by robotdan** [comment]
This should work, please re-open the intended use case described above is not possible with the FusionAuth APIs. 

- https://fusionauth.io/docs/apis/two-factor#start-multi-factor
- https://fusionauth.io/docs/apis/two-factor#send-a-multi-factor-code-during-login-or-step-up
- https://fusionauth.io/docs/apis/two-factor#send-a-multi-factor-code-when-enabling-mfa
