### ISSUE TITLE
insertInstant and lastLoginInstant is different for newly created users

### ISSUE THREAD

**Issue by Hurtak** [FusionAuth/fusionauth-issues#2048]
### Description 
We have logic that detects newly created users by comparing `insertInstant` and `lastLoginInstant` - we assume these two are the same for newly created users.
But, from what I am seeing in 1.42.0 it seems to be that the difference between these two is
- `0` (correct) for google auth provider
- ~`17` (incorrect) for regular email+password login

BTW is this the correct way to see if user was created or is there some better way?

### Affects versions
1.42.0

### Steps to reproduce

- register user with email+password through the API
- observe returned user data timestamps of `insertInstant` and `lastLoginInstant`, presumably these 2 should be always the same for newly created users

**Comment by mooreds** [comment]
Since those are in milliseconds, I believe the difference is that there is time taken to hash the user's password and otherwise verify that a username/password combo is valid. Whereas, because we trust the google IdP, the time difference is zero. This is an implementation detail and since it is not documented, there's no guarantee that this difference will remain in future versions.

> BTW is this the correct way to see if user was created or is there some better way?

There are a couple of approaches here, it depends on what you are trying to do.

* You could use the `user.create` or `user.create.complete` webhook: https://fusionauth.io/docs/v1/tech/events-webhooks/events/user-create to record the UUIDs and create dates of users in an external datastore (redis, dynamodb).
* You could determine what a reasonable value for the difference between a login and a create is. Personally, I'd be comfortable with any duration less than 5 seconds (5000 ms) between last login instant and insert instant indicating a use was new, but depending on the operation, you could vary that.

**Comment by robotdan** [comment]
I don't know that we plan to change anything here. 

I'll close as working as designed, but if we can identify a good use case for why this current behavior should be modified, please re-open.
