### ISSUE TITLE
JWT token issue

### ISSUE THREAD

**Issue by forenheith** [FusionAuth/fusionauth-issues#206]
Hello, I am trying to get JWT with the following end point in the Postman: http: // localhost: 9011 / api / jwt / issue? ApplicationId = 91edba61-e159-4177-a15c-b3e6ba58162a I also put the my API key as authorization header, but why I get 401 error code in the response. Could you help me solve this problem?

**Comment by robotdan** [comment]
What is your exact URL?

It should be `http://localhost:9011/api/jwt/issue?applicationId=91edba61-e159-4177-a15c-b3e6ba58162a`

The curly brackets in the doc signify the notation.

If that is correct, then you may get a 401 if your JWT is expired.

**Comment by forenheith** [comment]
![Postman_GCVWVvNTeC](https://user-images.githubusercontent.com/7276744/60351100-b412ff00-99cd-11e9-88aa-a0386d763372.png)

**Comment by forenheith** [comment]
I'm using API key (not JWT) as authorization header (case 1 from documentation) to get my JWT

**Comment by robotdan** [comment]
Ah, ok. 

That API is not accessible with an API key. 
https://fusionauth.io/docs/v1/tech/apis/jwt

![image](https://user-images.githubusercontent.com/1148709/60353018-54453580-9986-11e9-9a86-944776345562.png)


You'll see this only has the badge icon which means that is the only supported authenticated mechanism. This API is designed to take a JWT that is valid for one application and provide a JWT for another application for which you are registered. This authentication is done via the JWT because that identifies the user. An API key is not tied to a user.
