### ISSUE TITLE
User not registered still logged in

### ISSUE THREAD

**Issue by garsiv1932** [FusionAuth/fusionauth-issues#2090]
i have a structure of applications and tenants based on registrations, so users must be registered on the application, if he is not registered he will be logged in, but won't be granted access to the Application, but i dont want that, i want that fusionauth reject the user in the login screen like when the password is wrong?
Is that possible?

![Screenshot from 2023-02-03 10-52-11](https://user-images.githubusercontent.com/65036539/216619928-b9fd0dc6-f9c0-48b1-91b6-9e2aa78534c5.png)

**Comment by mooreds** [comment]
Thanks for using FusionAuth! However, @garsiv1932 this appears to be a support question, not a feature request or bug report. Let me know if I'm incorrect.

Otherwise, please seek support in one of two ways: 

- If you have a plan with support, please open a support ticket: https://account.fusionauth.io/account/support/
- If you do not, please create a forum post: https://fusionauth.io/community/forum/ so the community can assist.

Here's more about our technical support guidelines: https://fusionauth.io/docs/v1/tech/admin-guide/technical-support

I'm going to close this ticket based on the support guidelines.

**Comment by garsiv1932** [comment]
you can answer that you cant help me because i dont have a contract, but you cant approve my forum post.

**Comment by mooreds** [comment]
@garsiv1932 we had a spam problem on the forum, so we have a post queue that gets reviewed regularly for all new users' posts. It's a pain (for everyone) but we had too much spam before we turned that on.

I just approved your post and gave it an upvote, so you should be able to post in the future without going into the queue.

Thanks for using FusionAuth, and thanks for posting to the forum.

Cheers!
