### ISSUE TITLE
Updates to the OpenAPI spec needed

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-issues#2103]
### Description 
Open API Missing BaseSAMLv2ApplicationConfiguration when building

### Affects versions
List the version you are running, and any other versions you have attempted a recreated. 

### Steps to reproduce
1. Try and build from the OpenAPI Spec using autorest and openapi-client below.
2. Get the following errors below

### Screenshots
Open API Missing BaseSAMLv2ApplicationConfiguration when building

Examples from autorest and openapi-client below.

```
(test) ➜  openapi-client git:(fusionauth-openapi) ✗ autorest --input-file=../../openapi/fusionauth.yaml --python  --namespace=fusionauth 
AutoRest code generation utility [cli version: 3.6.3; node: v18.14.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ^3.7.0.
info    |    Loading AutoRest core      '/Users/richard/.autorest/@autorestcore@3.9.4/nodemodules/@autorest/core/dist' (3.9.4)
info    |    Installing AutoRest extension '@autorest/python' (latest -> 6.4.0)
installing... [========================================] 100% | 16/16
info    |    Installed AutoRest extension '@autorest/python' (latest->6.4.0)
info    |    Loading AutoRest extension '@autorest/modelerfour' (~4.23.5->4.23.7)
error   | InvalidRef | Ref '#/components/schemas/BaseSAMLv2ApplicationConfiguration' is not referencing a valid location. components,schemas,BaseSAMLv2IdentityProvider,properties,applicationConfiguration,additionalProperties
    - file:///Users/richard/dev/authentication-service/openapi/fusionauth.yaml:6873:11
fatal   | Plugin 'full-ref-resolver' completed with some error.
error   |   Error: Plugin 'full-ref-resolver' completed with some error.
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.
```

Openapi-generator

```
(test) ➜  openapi-client git:(fusionauth-openapi) ✗ openapi-generator generate -i ../../openapi/fusionauth.yaml -g python -c fusionauth.config.yaml 
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 131
Errors: 
        -attribute components.schemas.BaseSAMLv2IdentityProvider.BaseSAMLv2ApplicationConfiguration is not of type `schema`
Warnings: 
        -attribute components.schemas.BaseSAMLv2IdentityProvider.BaseSAMLv2ApplicationConfiguration is not of type `schema`

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:620)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:647)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:465)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

Internal -> tickets - 73173

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Database [MySQL | PostgresSQL] & and version

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by robotdan** [comment]
@jobannon do you know what needs to be changed here?

**Comment by mooreds** [comment]
My first guess is that we need to exclude `BaseSAMLv2ApplicationConfiguration` because we only want concrete implementations to be added to the spec. See https://github.com/FusionAuth/fusionauth-client-builder/blob/master/bin/build-openapi-yaml.rb for more. It's kinda hairy and would need to be tested out for sure.

**Comment by spwitt** [comment]
The bigger issue seems to be the inclusion of `BaseSAMLv2IdentityProvider` after recent code changes. The Ruby generator has special handling for `BaseIdentityProvider` and then [looks for classes that extend that](https://github.com/FusionAuth/fusionauth-client-builder/blob/0d7a42cec559c5229527a5048db3c3df786578ac/bin/build-openapi-yaml.rb#L602-L604) to build out all the identity provider definitions.

The updated spec is missing `SAMLv2IdentityProvider` and `SAMLv2IdPInitiatedIdentityProvider` because they don't directly extend `BaseIdentityProvider`. `BaseSAMLv2IdentityProvider` _does_ extend `BaseIdentityProvider`, so it is included. The `BaseSAMLv2ApplicationConfiguration` type is missing because it doesn't exist. The Ruby code modifies the IdP class name [according to a standard pattern](https://github.com/FusionAuth/fusionauth-client-builder/blob/0d7a42cec559c5229527a5048db3c3df786578ac/bin/build-openapi-yaml.rb#L199-L206) in order to come up with the application configuration type.

I'm not sure whether it is better to refactor Java classes or add more edge cases to the Ruby generator. It probably depends on how much value `BaseSAMLv2IdentityProvider` adds in the Java code vs repeating the values in two classes.

**Comment by mooreds** [comment]
This fix will be picked up next time we release, which should be the 1.45 release.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-client-builder/pull/67
