### ISSUE TITLE
OAuth2: Query params issue when redirect_uri has a # used on SPAs

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#215]
### Description 
When trying to do the oAuth2 flow with the redirect being a SPA URL that has a `#` in its route, the query params are returned with an `&` instead of `?`.

### Steps to reproduce
1. Run the OAuth2 with `redirect_uri` like `https://myapp.com/#/login`
2. Login
3. Redirection is `https://myapp.com/#/login&code=XXX`
4. The SPA router, won't match the `/login`.

### Expected behavior
Redirection being `https://myapp.com/#/login?code=XXX`.

### Additional context
The hacky workaround is adding a trailing `/` to the `redirect_url`. This way we have to update the SPA route to `/login/:data` and parse `data` to get the code.

**Comment by robotdan** [comment]
Thanks for letting us know @AlvMF1. 

What does your request look like? Are you passing `response_type=code` or `response_type=token` ? 

From your notes it looks like you're using the Authorization Code Grant (`response_type=code`)  - but then the response is for an implicit grant. (using `#`). 

This may already be fixed, but I can verify.

**Comment by AlvMF1** [comment]
1. Disabled
2. 1.7.2
3. Authorization code

**Comment by robotdan** [comment]
Thanks @AlvMF1 I've recreated. The `#` is causing us a problem.. should have it fixed for the upcoming 1.8.0 release. It sounds like you have a way to work around this bug for now?

**Comment by robotdan** [comment]
So I'm waffling a bit on this fix, a lot of SPAs are moving away from using the fragment because it makes some things trickier, you don't get browser history, etc. Now that there is a browser history API, I believe this strategy is slowly becoming deprecated for SPAs. 

 I think Angular now by default uses the Path Location routing strategy over the Hash Location, however the latter can still be enabled. 

I can make the redirect URL look like `https://myapp.com/#/login?code=XXX` - but technically since anything after the `#` is a fragment and not a query string, I am having to make an assumption that I know what the fragment contains.

What framework are you using?

**Comment by AlvMF1** [comment]
I understand your concern. We're using React and `react-router` and we might switch to `BrowserRouter` at some point...

**Comment by robotdan** [comment]
Ok. Let me think on this a bit more, in theory I can ship this change, but once if I have to make assumptions about how to build the URL outside of the spec it may be dicey.

**Comment by robotdan** [comment]
Hi @AlvMF1 

Decided not to fix this one, I think the way we are handling the URL is technically correct and to fix it I have to break spec. 

Lots of ways to handle this, but from my point of view, the work around you have is correct. I think you should redirect to some route on your backend, handle the code exchange to FusionAuth, and then redirect to your SPA. 

This way your SPA does not have to call FusionAuth to get an access token which is a good thing. 
This allows you to have better options for how to store an access token, you could write it back to your SPA as a secure HTTP only cookie for example. 

Thanks, let me know if you have questions.

**Comment by AlvMF1** [comment]
😢 
Just kidding, that's alright. Thanks!
