### ISSUE TITLE
Bug: search by query string in PHP client

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#22]
**Describe the bug**
As written in the documentation, the search is a GET method: https://fusionauth.io/docs/v1/tech/apis/users#search-for-users

The PHP client is using POST method: https://github.com/FusionAuth/fusionauth-php-client/blob/master/src/FusionAuthClient.php#L1729-L1734

**To Reproduce**
Just use `searchUsersByQueryString`

**Expected behavior**
Should work and return a user list :D

**Screenshots**
<img width="972" alt="capture d ecran 2018-11-09 a 09 29 46" src="https://user-images.githubusercontent.com/1580512/48245007-43997c80-e402-11e8-8eb1-38b81fdf4304.png">

**Comment by robotdan** [comment]
Hi @blanchonvincent - the `searchUsersByQueryString` in the PHP client takes a request object and does use the `POST` method. 

We initially didn't document this because we only added the `POST` to make the API call easier in the client libraries. 

The following is in the doc for the command in the PHP library, this is likely not very intuitive and since it is not documented on the search API page as a `POST` command, I can see why this is confusing. 

```
* @param array $request The search criteria and pagination constraints. Fields used: queryString, numberOfResults, startRow, and sort fields.
```

I'll add the `POST` method to the documentation. 

In the mean time, try the following request. 

```
searchUsersByQueryString(["search" => ["queryString" => "vincent"]]);
```

Let me know if that gets you going.

**Comment by robotdan** [comment]
Pending documentation update. Need to document the `POST` method of the search API.

**Comment by robotdan** [comment]
Documentation updated with the `POST` version of the search API. 
https://fusionauth.io/docs/v1/tech/apis/users#search-for-users
