### ISSUE TITLE
Dart client is not working

### ISSUE THREAD

**Issue by vcampitelli** [FusionAuth/fusionauth-issues#2240]
### Description 
As stated in FusionAuth/fusionauth-dart-client#13, our Dart client library is throwing a lot of errors.

I tried fixing it by changing the `char` type to `String` as it was complaining that `char` doesn't even exist and I solved all `Error: The parameter '...' can't have a value of 'null' because of its type 'String', but the implicit default value is 'null'` errors by making a lot of parameters nullable.

I still received a bunch of `Error: A value of type 'Future<ClientResponse<dynamic, dynamic>>' can't be returned from a function with return type 'Future<ClientResponse<ActionResponse, Errors>>'` that I tried solving by changing a few things in how we use Generics but couldn't get anywhere.

Finally, I tried downgrading Dart SDK from 2.19 to 2.7 _(which was the last SDK change introduced by FusionAuth/fusionauth-dart-client@b8496c5e0699f0722e462864136f8b6dba9300d7)_ and our lib to 1.21.0 _(which is mentioned in [README](https://github.com/FusionAuth/fusionauth-dart-client/blob/master/README.md))_ and I still got errors, so I gave up.

I then tried using [OpenAPI Dart Generator](https://openapi-generator.tech/docs/generators/dart/) but got other errors. There's an open PR OpenAPITools/openapi-generator#12574 that tries to fix some of them, so I built from source and tried using it but still no luck. Finally, I tried using the [OpenAPI Dart Dio Generator](https://openapi-generator.tech/docs/generators/dart-dio/) _(that uses [dio HTTP client](https://pub.dev/packages/dio))_ and it finally worked, but I still need to tweak a lot of settings to generate correct docs (that are currently wrong).

### Affects versions
- Tried a lot of client versions from 1.21.0 to 1.45.1 (latest)

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by vcampitelli** [comment]
Here's how I used the [OpenAPI Dart Dio Generator](https://openapi-generator.tech/docs/generators/dart-dio/) to build a library from our [OpenAPI spec](https://github.com/FusionAuth/fusionauth-openapi/blob/master/openapi.yaml):

```shell
docker run --rm \
  -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
  -i /local/openapi.yaml \
  -g dart-dio \
  -o fusionauth_dart_client \
  -c openapi-generator-dart-dio-config.yaml
```

I've started building a example client to be added to the [fusionauth-example-client-libraries](https://github.com/FusionAuth/fusionauth-example-client-libraries) repo:

```dart
import 'package:dio/dio.dart';
import 'package:fusionauth_dart_client/fusionauth_dart_client.dart';

Future<Tenant> getTenant(DefaultApi api) async {
  final response = await api.retrieveTenantWithId(tenantId: "");
  final Tenant? tenant = response.data?.tenants?[0];
  if (tenant == null) {
    throw Exception("Couldn't find any tenants");
  }
  return tenant;
}

Future<void> patchTenant(DefaultApi api, Tenant tenant, String issuer) async {
  final patched = new Tenant((b) => b..issuer = issuer);
  await api.patchTenantWithId(
      tenantId: tenant.id!,
      tenantRequest: new TenantRequest((b) => b..tenant = patched.toBuilder())
  );
}

void main() async {
  final client = FusionauthDartClient();
  client.setApiKey('ApiKeyAuth', 'Api-Key Here'); // Change this

  final api = client.getDefaultApi();
  final issuer = "http://localhost:9011";

  try {
    print('Searching Tenant...');
    final Tenant tenant = await getTenant(api);
    print(' [ ] Found: ${tenant.id}');
    print('Updating Tenant issuer: ${issuer}');
    await patchTenant(api, tenant, issuer);
  } on DioError catch (e) {
    print(e);
    print(e.response);
  }
}
```

I've paused developing this to wait for any suggestions.

**Comment by mooreds** [comment]
So I think we should definitely replace the dart client library with the one you've generated, especially after https://github.com/FusionAuth/fusionauth-client-builder/pull/68 is merged.

The question is, how. Options I see are:

* create a new repository called `fusionauth-dart-client-openapi` or `fusionauth-dart-client-new` or `fusionauth-dart-client-generated` or `fusionauth-dart-client-v2` or `fusionauth-dart-openapi-client`. This is good because it sets a pattern if we want to do the same with other client libraries that work. (php, go, etc). In those cases, we'll be maintaining two versions of the client library for a substantial period of time. Any suggestions on good names?
* because dart is totally busted, we could push this new version into the `fusionauth-dart-client`. That kicks the can down the road in the case of the go/php/etc, but lets us get the dart client working quickly.
* we could I suppose have two branches inside the `fusionauth-dart-client` repo. 
* something else. 

@andrewpai @robotdan any thoughts?

**Comment by andrewpai** [comment]
Closing due to deprecation of the library.

**Comment by mooreds** [comment]
Are there any website/doc updates we need to make to complete deprecation?
