### ISSUE TITLE
Support to specify refresh token expiration time on Login API request

### ISSUE THREAD

**Issue by joaonice** [FusionAuth/fusionauth-issues#2273]
Hi everyone!

We have an application with all our users but we have to distinguish the logins that are coming from the mobile and web apps and set different durations to the issued refresh token. Since this setting is an application (or tenant setting), how can we do such a thing? 

Thank you!

**Comment by mooreds** [comment]
Hi @joaonice .

Thanks for using FusionAuth!

This is a support question, so is best asked through support channels. We use GitHub for bugs and feature requests, not support. You have two options for support:

* File a support ticket if you are on a plan with paid support: https://account.fusionauth.io/account/support
* Open a forum post: https://fusionauth.io/community/forum/

Here's more on our technical support options in general: https://fusionauth.io/docs/v1/tech/admin-guide/technical-support

Because this is a support request, I'm going to close this issue, but the team looks forward to answering your question in one of the two above locations.
