### ISSUE TITLE
JVM -Xmx, -Xms, and additional java args not being set by start script

### ISSUE THREAD

**Issue by lyleschemmerling** [FusionAuth/fusionauth-issues#2284]
### Description 
the `resolveConfigurationProperty` function tries to check for the `FUSIONAUTH_CONFIG_DIR` to look up the props file, but that variable is never set (`CONFIG_DIR`) is.

### Affects versions
`1.38.1` to `1.46.0` (assuming this is shipped in 1.46.0)

### Steps to reproduce
Check jvm settings

### Expected behavior
Should respect what is in fusionauth.properties

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
This will only affect machines that were relying on `fusionauth.properties` to obtain the JVM args for heap size and additional java arguments

Since we are not explicitly setting the Java heap size properties on FusionAuth app the JVM is using the VM default which looks to be about 25% of the VM available RAM. So far we haven't seen any systems with OutOfMemory errors so it is unlikely that this is hindering performance on any machines that we have seen. However if necessary the parameters can be set via `FUSIONAUTH_APP_MEMORY` and `FUSIONAUTH_APP_ADDITIONAL_JAVA_ARGS`.

FusionAuth instances running in Docker should be container aware and should only be using memory allocated to the container. Anyone explicitly setting the JVM args via environment variables will be unaffected.

This will only affect `fusionauth-app` and not `fusionauth-search` (i.e. ElasticSearch).

**Comment by robotdan** [comment]
Can you add some details to explain what is happening due to this bug and whom it will affect, or not affect? 

For example:
1. Does not affect Docker, or anyone using environment variables to set memory
2. Does not affect `fusionauth-search` , only `fusionauth-app`
3. When `-Xmx -Xms` are not set, the VM will default the heap to something, in our observation it was 25% of available RAM. So this should be considered if anyone runs into this issue or the heap config for the Java process for `fusionauth-app` is too low or too high.

**Comment by lyleschemmerling** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/253
