### ISSUE TITLE
Free Marker error when a slash is added in URL

### ISSUE THREAD

**Issue by petechungtuyco** [FusionAuth/fusionauth-issues#233]
### Description 
As the title suggests, we get an error whenever we add an addition forward-slash in the URL. Is there any workaround we can do or even catch the error?

### Steps to reproduce
1. Go to Fusion Auth Login page
2. Add an additional forward-slash in the URL (e.g. /oauth2//authorize)

### Screenshots
https://imgur.com/a/b4ouRsh

Thanks!

**Comment by robotdan** [comment]
I've been unable to recreate as of yet, do you have any other information that may help? 

- FusionAuth version?
- Are you using a custom theme?
- Do you have self service registration enabled?

**Comment by petechungtuyco** [comment]
Hi @robotdan 

- Fusion Auth version: 1.7.1
- Yes, I am using a custom theme (but even in admin page it does happen. Try **/admin//user**)
- Yes, my self-service registration is enabled

**Comment by robotdan** [comment]
Thanks @petechungtuyco that is helpful, I am able to recreate. I'll let you know what I find out.

**Comment by robotdan** [comment]
So the RFC for the URI does indicate `/oauth2//authorize` and `/oauth2/authorize` are discrete URIs. Often times file system resolution will behave properly because most file systems will treat `/` the same as `//`. 

In our case we are resolving the first template correctly `/oauth2//authorize` and then when that template attempts to include another one it uses a different resolution strategy that fails. 

That is all to say, this is currently working as designed. Is there a reason you are adding the additional `/` or are you able to keep it from happening if it is being added automatically by some other service?

**Comment by petechungtuyco** [comment]
This error was found by our security team. It's because they don't like showing java stack trace in the frontend. Anyway, we solved this by handling the URL in our nginx. Thank you for your support @robotdan !

**Comment by robotdan** [comment]
Thanks for the update @petechungtuyco, we should probably handle that error better and return a 404. 

I'll keep this issue open to review how we handle this exception and see if we can fail a bit more gracefully.

Thank you for the feedback.

**Comment by andrewpai** [comment]
This was properly addressed in FusionAuth 1.46.0.
