### ISSUE TITLE
On logout it is not clearing the access token and refresh token

### ISSUE THREAD

**Issue by kamaleshdas1997** [FusionAuth/fusionauth-issues#2407]
### Description
On logout it is not clearing the access token and refresh token, so when i try to login again it auto authenticate the previous user and redirecting to home page with asking for login

I am using react SDK and my logout endpoint is in node server. Here is my logout code:

![image](https://github.com/FusionAuth/fusionauth-issues/assets/47658720/276b7407-100d-4086-b35e-3aba6a057a6f)

Is this a question about how to use FusionAuth? Please consider posting on the [FusionAuth forum](https://fusionauth.io/community/forum/) instead.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
This is working as designed. The front channel oauth logout doesn't revoke JWTs or refresh tokens (I'll update the doc to make it more clear). 

You can revoke the refresh token via APIs: https://fusionauth.io/docs/v1/tech/apis/jwt#revoke-refresh-tokens and JWTs via an additional system design: https://fusionauth.io/articles/tokens/revoking-jwts

Thanks!

**Comment by mooreds** [comment]
Actually, I apologize, I misread your question. It looks like your cookie deletion isn't occurring correctly, probably because you are setting the cookie and then redirecting, when you want to redirect, then delete the cookies.

This also is a support question, so please use the support channels:

* https://fusionauth.io/community/forum/ (community support)
* https://account.fusionauth.io/account/support/ (paid support)
