### ISSUE TITLE
Logout URL not working

### ISSUE THREAD

**Issue by kramaswamy7** [FusionAuth/fusionauth-issues#242]
### Description
Hi all,

In the FusionAuth config for my application, I have placed a URL in the Logout URL field. From my understanding (from https://fusionauth.io/docs/v1/tech/oauth/endpoints#logout), the precedence that is used is firstly the Logout URL from the application, and then from the main system settings.

However, when I try logging out from my application, the Logout URL is not triggered unless I set it at the system level.

I have verified that I am passing the ClientID with the logout, as indicated in the endpoints documentation:

https://{MyServer}/oauth2/logout?client_Id={MyClientID}

I should note that the log out works properly - it's the redirecting that fails.

Please let me know if I can provide any other information.

Thanks!

**Comment by robotdan** [comment]
If I understand correctly, you have configured a logout URL for the application (Applications --> OAuth --> Logout URL) and a global Logout URL System Configurations --> OAuth --> Logout URL).

When you call the logout URL by redirecting the browser to `https://{MyServer}/oauth2/logout?client_id={MyClientId}` you are redirected to the global URL instead of the application specific one? 

We will always return a `302` from the `/oauth2/logout` endpoint, if no logout URLs are configured system wide or in the application we will redirect to `/`, otherwise we will prefer the application value over the system one. 

Can you screenshot your configuration for your application OAuth tab and the system configuration OAuth tab?

**Comment by kramaswamy7** [comment]
Hi Dan,

Here's some screenshots with data removed -  let me know if this helps explain.

If I don't put the value in the system setting (despite having one in the app setting), I get directed to:

https://{MyAuthServer}/oauth2/authorize?client_id={ID}&response_type=code&redirect_uri=%2Flogin&state={State}

If I do put that value in the system setting, I get properly directed to the destination.
![ss1](https://user-images.githubusercontent.com/19194795/62073331-81e3ff80-b20e-11e9-98fa-859ca3260c97.png)
![ss2](https://user-images.githubusercontent.com/19194795/62073332-81e3ff80-b20e-11e9-8553-dba35f2ea73f.png)

**Comment by robotdan** [comment]
Can you tell me what the URLs are respectively? You can change any sensitive information - but it would be helpful for me to see the structure of each of the URLs. 

For example just change your domain to `example.com` or something like that.

**Comment by kramaswamy7** [comment]
The URLs are the same for each - and sure, if we use example.com, they would be https://subdomain.example.com/en/

**Comment by kramaswamy7** [comment]
Hi Dan, any ideas on what the problem could be?

**Comment by robotdan** [comment]
I don't, I am not able to recreate your error. 

In your example you show `https://{MyServer}/oauth2/logout?client_Id={MyClientID}` - is that just a typo or is that how you're sending the URL? 

In that example, you have an uppercase value as the `I` instead of a lowercase `i`. 
 `client_Id`  should be `client_id`.

**Comment by kramaswamy7** [comment]
Hi Dan,

That was exactly the problem - I had the upper case I. Thanks, now it's working! Perhaps in your documentation, you should add the fact that those url parameters are case-sensitive? I feel like generally people assume querystring parameters are case-insensitive.

**Comment by robotdan** [comment]
Great, glad to hear that worked for you @kramaswamy7 . 

Actually the specification indicates all query parameters are case sensitive unless documented otherwise. Generally speaking, only the scheme and host are case in-sensitive. For example `http://example.com` is equivalent to the URL `HTTP://EXAMPLE.COM`. 

https://tools.ietf.org/html/rfc3986#section-6.2.2.1

> The other generic syntax components are assumed to be case-sensitive unless specifically defined otherwise by the scheme (see Section 6.2.3).

But adding a note to the documentation isn't a bad idea. Thanks!
