### ISSUE TITLE
VueJS SDK and Quickstart

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2429]
Create a vuejs SDK (like the Angular and React SDKs in functionality) and a changebank quickstart application using the SDK.

**Comment by ColinFrick** [comment]
Working on it

**Comment by ColinFrick** [comment]
Hey @mooreds I have created the Vue SDK here: https://github.com/sonderformat-llc/fusionauth-vue-sdk

I'm unsure what to include in the README.md because both React and Angular reference an example application (not the quickstart) for the backend f.e. https://github.com/FusionAuth/fusionauth-example-react-sdk/tree/main/server. Should I also create such an example application?

**Comment by mooreds** [comment]
No, please just point folks to the quickstart Vue application. 

Let me know when you'd like me to migrate the SDK over the FusionAuth.

**Comment by Aaron-Ritter** [comment]
Closed under https://github.com/FusionAuth/fusionauth-site/pull/2529
