### ISSUE TITLE
OpenID Connect Reconcile Lambda: id_token with a RSA Signature is provided

### ISSUE THREAD

**Issue by charlesericjs** [FusionAuth/fusionauth-issues#2501]
### Problem
We cannot retrieve the tenant ID (`tid`) and the object ID (`oid`) claims from the [Microsoft Azure AD v2.0](https://learn.microsoft.com/en-us/azure/active-directory/develop/id-token-claims-reference) / [Graph API UserInfo](https://learn.microsoft.com/en-us/azure/active-directory/develop/userinfo) endpoints and the UserInfo response from Microsoft cannot be modified:

![image](https://github.com/FusionAuth/fusionauth-issues/assets/23261761/9592cf8a-bf18-4f28-b95d-d30afc60f61c)
 
These 2 claims are only available in the **id_token** and **access_token**. However, since the id_token is signed using an asymmetric key-pair, it will not be available to the Lambda, per your [doc](https://fusionauth.io/docs/v1/tech/lambdas/openid-connect-response-reconcile). Because of this limitation, we cannot verify the information we need to perform a secured login as is recommended by Microsoft [based on recent findings](https://msrc.microsoft.com/blog/2023/06/potential-risk-of-privilege-escalation-in-azure-ad-applications/).
 
### Solution
Since the `tid` and `oid` claims are in the **id_token** returned by Microsoft, we want to retrieve them from said token to reliably identify a user and protect them from account takeover / privilege escalation attacks. 

This is THE [recommendation from Microsoft](https://learn.microsoft.com/en-us/azure/active-directory/develop/id-token-claims-reference): 

![image](https://github.com/FusionAuth/fusionauth-issues/assets/23261761/39a6ade7-6e2f-48ec-8ce4-5c720262bb57)

However, because they are not even considered in your OpenID Connect IdP settings (because they are not generic claims), we need to obtain them in the OIDC reconcile lambda and validate them ourselves in our system.  

Furthermore, Microsoft suggests using the id_token instead of calling the UserInfo endpoint altogether:

![image](https://github.com/FusionAuth/fusionauth-issues/assets/23261761/0d8fde31-9f35-4090-98b4-d1ece7891cb2)

This would also give us the ability to read the [xms_edov parameter](https://learn.microsoft.com/en-us/azure/active-directory/develop/migrate-off-email-claim-authorization). 

> Side note: 
this is still a suboptimal solution, because during a brief window, a malicious actor would have a session created until we revoke its tokens once it is detected that the `tid` and `oid` values do not match the ones from a legitimate user. Throwing an exception in the lambda would prevent this, but it's a way too massive security rule to code there.

### Alternatives/workarounds
We tried using the Azure AD v1 endpoints: 
- https://login.microsoftonline.com/organizations/oauth2/authorize
- https://login.microsoftonline.com/organizations/oauth2/token
- https://login.microsoftonline.com/organizations/openid/userinfo

because they do offer a more detailed UserInfo response with the `tid` and `oid` claims:
```json
{
    "amr": "[\"rsa\",\"mfa\"]",
    "family_name": "",
    "given_name": "",
    "ipaddr": "",
    "name": "",
    "oid": "",
    "onprem_sid": "",
    "rh": "",
    "sub": "",
    "tid": "",
    "unique_name": "",
    "upn": "",
    "uti": "",
    "ver": "1.0"
} 
```

But this method will never return the `email` claim and all our users are created using the `email` claim from Azure AD v2 and Graph API. There is no way to guarantee that `unique_name` and `upn` claims will have the same value as email so we cannot use this workaround especially if one of our customers also allow user/passwords login. Also, it's not enticing to use older specs.

### Additional context
Microsoft recommends never using the email claim for authorization purposes as it opens applications to account and privilege escalation attacks.

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/36
- https://github.com/FusionAuth/fusionauth-issues/issues/222
- https://github.com/FusionAuth/fusionauth-issues/issues/2189
- https://github.com/FusionAuth/fusionauth-issues/issues/2494

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

### Documentation
- [x] Document when the `id_token` is available to be used to resolve claims such as `emailClaim`, `usernameClaim`, and `uniqueIdClaim`. It used to be only available for the `emailClaim` and `usernameClaim` when signed using the `client_secret` using an HMAC algorithm. It is now available to resolve the `uniqueIdClaim` and additionally can be verified even when signed using a symmetric key as long as the public key is published via JWKS and resolvable via `.well-known/openid-configuration` endpoint. 

### Release Notes
When the `id_token` is returned from the IdP and the signature can be verified it will now be used to optionally resolve the `uniqueIdClaim` in addition to the `emailClaim` and `usernameClaim`. This means you can configure the `uniqueIdClaim` to a claim that is only available in the `id_token`. Prior to this change, the `id_token` could only be verified if it was signed using the an HMAC algorithm using the `client_secret`. With this change, if the IdP publishes public keys using the JWKS endpoint that is resolved from the `.well-known/openid-configuration` FusionAuth will attempt to validate the signature.

**Comment by robotdan** [comment]
To clarify how linking works in FusionAuth, just as M$ recommends we do link on the `sub` claim. This is configurable, so you could modify this if you wanted to link on `oid` for example. As long as the claim you configure is globally unique, we are good. 

This means once the link is established the email could change in FusionAuth or in M$ and the link would remain. 

The only thing we use the email for is to identify a user that has not yet been linked. We call this the linking strategy. 

For example, the first time a user logs in, we cannot resolve the user in FusionAuth by the `sub` claim because we have never seen it before. If you configure FusionAuth to link by email, we first see if we have previously built a link for this user by looking up the `sub` claim in the IdP mapping. If the link does not yet exist, we have to decide if the user exists in FusionAuth yet, or if we need to create a user. 

This is where we use the linking strategy. When configured to link by email, we look to see if a user exists with the email returned by the Userinfo response. If a user exists, we link this user. 

This does have risk of account takeover if you do not trust the IdP you are using. It is always paramount that you trust the IdP, if you do not, you should not use the IdP for federation. 

In version 1.48.0 we are adding an option to reject a link if the `email_verified` claim is present, and is `false`. 
- https://github.com/FusionAuth/fusionauth-issues/issues/2423

This will help in some cases - assuming the IdP can return this claim. However, the only way to full protect against account takeover in this example is to never trust the IdP at all. 

This can be done by never linking automatically, or asking the user to log in or create a user to complete the link. This forces the user to prove they already have an account in FusionAuth. These are both options today, you just need to adjust the linking strategy. 

Another option is to have FusionAuth always perform email verification inline during a linking workflow such that we do not have to trust the 3rd party IdP to perform email verification. This work is planned under this issue:
- https://github.com/FusionAuth/fusionauth-issues/issues/2506

**Comment by charlesericjs** [comment]
While I agree that you offer linking strategies that would allow us to validate users, it make no sense to me to do this in an OIDC flow where on of the main goal is to provide as less friction as possible for the user when logging in.

We already use the link by email strategy, and I can see in the event logs that the sub claim is also used to link the external user once the FA user has been linked at least once by email. The problem is that your system doesn't check if the sub has changed when an malicious actor use the correct email. It will link by email regardless of the sub value.

I also understand the idea of having to trust the  IdP, but it's Microsoft we are talking about, not some obscure company. To me, the only reason we cannot trust Microsoft right now is because we cannot read the id_token or the access_token, both of which being OIDC standards.

I think it's fair to request full OIDC functionality when using and OIDC IdP in FusionAuth.

Having the email_verified claim in the Userinfo response would help a lot, but Microsoft have no information regarding the support of this claim, so your upcoming support for this won't fix the issue with this IdP.

**Comment by charlesericjs** [comment]
Was on my phone, closed the issue by accident lol.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-app/pull/334

**Comment by charlesericjs** [comment]
Tested with v1.48.0 and it works. Thanks again for adding this functionality very quickly!

**Comment by robotdan** [comment]
Re-opening per our process until the documentation changes are complete.
