### ISSUE TITLE
Email verification by third party won't work without e-mail sending by fusionauth 

### ISSUE THREAD

**Issue by stoica-florian** [FusionAuth/fusionauth-issues#251]
### Description
I use the provided API's to do the email verification process by a third party which also sends the e-mail.
In order to do this I had to add invalid credentials  for smtp server.
There should be a alternative to use own e-mails from third party, in order to register users that require e-mail verification smtp settings are mandatory and templates should be selected.

**Comment by robotdan** [comment]
Thanks for the feedback @stoica-florian - this is something we have discussed quite a bit. 

We do want to be flexible understanding that some will want to use external email provides. However because email is integral to many features in FusionAuth it is difficult to remove the requirement for an SMTP configuration all together.

**Comment by robotdan** [comment]
I think this can be accomplished by explicitly verifying the user's email address with the Verify Email API.

**Comment by MikeBroders** [comment]
@robotdan 

but how would be the flow and parameters to keep email-verification enabled and suppress fusion-auth sending the verification-email?

**Comment by mooreds** [comment]
@MikeBroders this is a great question for the forum, just sayin.

https://fusionauth.io/community/forum/
