### ISSUE TITLE
Unable to login user right after creating an application

### ISSUE THREAD

**Issue by johnmaia** [FusionAuth/fusionauth-issues#252]
### Description
We're developing a script that reproduces the following steps:
- Create a new `tenant`
- Create a new `application` on the previous `tenant`
- Create a new `user` on previous `application`
- Login the previous `user`

And **sometimes** it fails on the last step:
```js
{ 
  fieldErrors: { 
    applicationId: [{ 
      code: '[invalid]applicationId', 
      message: 'Invalid [applicationId]. An application with Id [27827def-166f-4026-ad60-3f1efa28afe5] does not exist.' 
      }] 
    } 
  },
  successResponse: null, 
  exception: null 
}
```

And if we check `fusionauth` (dashboard) we can see that the `applicationId` exists.

I know that it's very unlikely, but is it possible that it's necessary to flush elastic search engine before login in the `user`? Given that these steps are executed one after another.

**Comment by johnmaia** [comment]
`Update:` We were using a cluster with two instances of `fusionauth` and we've now reduced to a single instance and apparently the error disappeared.

**Comment by robotdan** [comment]
Thanks for letting us know @johnmaia  - there is a timing issue here due to an application cache load. This is likely the reason you are not able to recreate on a single node. 

When you are running two nodes, in the start up logs you will see a message about the IP address detected for the node. FusionAuth will prefer a site local address if one exists, and if each node can communicate over this address the cache reloads should be near instant across the cluster. If there is not inter-node communication then we will fall back to a timer based cache load. 

For example here is the startup message that mentions the address selected:

```
Aug 02, 2019 7:15:47.201 AM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Dynamically set property [fusionauth-app.public-url] set to [http://192.168.43.183:9011]
```

In this case `http://192.168.43.183:9011` has been selected and if I were to run multiple nodes this would be the address used by other nodes to communicate to this node. 

This value is also configurable if the automatic detected one is not ideal for your configuration. 

The validation path should likely not be using the cache - so we can enhance this in the upcoming release to remove the possibility of a timing issue.
