### ISSUE TITLE
Improve docs search

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2553]
Improve docs search.

* Algolia
* One of the other options (internal: https://inversoft.slack.com/archives/C04DGBXKPGC/p1700071389776319 )
* Make pagefind better.

**Comment by bglw** [comment]
👋 Let me know if there's anything I can build into Pagefind to help improve things for you

**Comment by jobannon** [comment]
I think that we should have an advanced Search Page that a user can toggle. 
Right now we just have what I would call "quick find" functionality.  What I am suggesting is Advanced Search Capabilities if a user needs to get more granular when searching our documentation.  

This would allow the user to filter by 
- API 
- Guides
- Tutorials
- Release Notes
- ETC

Adding the ability to bookmark doc pages per logged in user would be another nice to have.

**Comment by LucasPMorris** [comment]
I may approach it as: What do our customers search for? Do they find the answer? 

I use certain parts of the documentation more than others (because certain habits are already forming based on my use, but different users would have different habits, but we could likely determine the general habits). We can guess what and how our users search but we will all have different viewpoints. We could also do recursive analytics that take count of how many times a user searches more than once, how long they stay on that page, if they use Command+F a lot, etc. Then adjust the search to account for those parameters after every so many searches.

In regards to Josh's opinion, when I did one of the start up exercises for the position, after FusionAuth was running I wanted to observe the user object. Finding the structure of that object was very difficult, in other words, scoped searches as Josh suggests would have expedited my search significantly.

**Comment by mooreds** [comment]
Leave it be for now.

**Comment by mooreds** [comment]
searching for `hosted backend` or `hosted backend apis` doesn't return the hosted backend API pages.

**Comment by andrewpai** [comment]
We've made some changes to improve search. Closing this issue and we will open another if we decide we need further improvements.
