### ISSUE TITLE
Create API resource status code

### ISSUE THREAD

**Issue by pbuzulan** [FusionAuth/fusionauth-issues#259]
### Description 
When I use API to create a resource and it successfully ends you return a 200 status code instead of 201. In general the http status code of  an insertion with a happy ending is 201 and not 200. Same for duplicate entry, you return a general 400 instead of 409 or whatever. I needed to create a layer that intercept the response and returns a proper status code.

**Comment by robotdan** [comment]
Thanks for the feedback @pbuzulan . 

The upside of returning `400` with a JSON response body is that we can provide very detailed information with regards to why the request failed. 

We often will return one-to-many validation errors at the same time, for example the requested Id may be a duplicate, the name is too long, a missing field is required.  In theory we could arrange validation in a more sequential process where we first check for a duplicate, return a specific status code, and then once the user corrects that issue and make the request again we return `400` with the additional validation errors. 

Thus far we've chosen to return as much validation in one go as possible to limit the amount of retries or trial and error that is necessary on the developer side of things. 

With that in mind, we likely won't be able to make status codes for every type of validation, but perhaps there are specific use cases we could consider. 

With regards to a `409` - technically this is used for conflict, but it wouldn't be a stretch to consider this for a duplicate key of some sort. In our case the conflict may be a duplicate Id, name, or other unique attribute. So in this case we'd still want to return JSON because of the variable nature of the reason.

What was the use case you are solving that you need to create a layer and intercept JSON response on a `400` to map the status code to something else? Is it for duplicate email addresses or unique Ids? 

Thanks!

**Comment by pbuzulan** [comment]
It makes sense now I've read your opinion but what about resource created status code? 

> What was the use case you are solving that you need to create a layer and intercept JSON response on a 400 to map the status code to something else? Is it for duplicate email addresses or unique Ids?

Basically  it's for duplicated email, I let fusionauth assign a random id to the resource.

**Comment by robotdan** [comment]
If you wanted to make one more additional API request before attempting a create operation you could first attempt to retrieve a user by email.

**Comment by voidmain** [comment]
The created response of a `201` would likely only be returned from a `POST` request since that is the HTTP method that FusionAuth uses to indicate an object is being "created" (which is the same verb from the HTTP specification). While FusionAuth could respond with a `201`, the combination of `POST` and `200` is essentially the same. Your logic could just check those two things to determine if the create was successful like this:

```
if (method == 'POST' && status == 200) {
  // Yay! it was created
}
```

Are there specific cases where this type of logic won't work for you?

**Comment by pbuzulan** [comment]
> The created response of a `201` would likely only be returned from a `POST` request since that is the HTTP method that FusionAuth uses to indicate an object is being "created" (which is the same verb from the HTTP specification). While FusionAuth could respond with a `201`, the combination of `POST` and `200` is essentially the same. Your logic could just check those two things to determine if the create was successful like this:
> 
> ```
> if (method == 'POST' && status == 200) {
>   // Yay! it was created
> }
> ```
> 
> Are there specific cases where this type of logic won't work for you?

Yes that's right, I could do anything I want, more likely to check use your python library method was_successful() but what I wanted to ask is how come you didn't use such approach since the beginning.

**Comment by voidmain** [comment]
That's a good question. I'm not positive why we originally decided to use `200` for `POST`. Maybe it was just to be consistent with all successful operations. I tend to prefer if everything that is successful (include `GET`, `DELETE`, `PUT`, etc) use the same status, but I can see how people like to be inline with the HTTP specification.

We could make a case for changing this in FusionAuth 2.0 though. For now, we probably won't make any changes to status codes since it could potentially break integrations.
