### ISSUE TITLE
User Import API Email Validation

### ISSUE THREAD

**Issue by matt1hathcock** [FusionAuth/fusionauth-issues#2601]
### Description 
I can import a user with a non-standard email format such as markdown text:

```
[matt+postman-test@fusionauth.io](mailto:matt%2Bpostman-test@fusionauth.io)
```

When I go to edit this user in the Admin UI I am unable to make changes and save the user because the email now fails validation.

User create/update API fails with an invalid email. Admin UI fails to create/update user with invalid email. Client libraries fail to create/update user with invalid email.

### Affects versions
Current version 1.48.3.

### Steps to reproduce
1. Import User with Postman
2. Get 200 ok
3. Search user in Admin UI
4. Click to Edit User
5. Click to Save User

### Expected behavior
User import should fail if the email is not a valid format.

### Screenshots
![Screenshot 2024-01-04 at 3 12 10 PM](https://github.com/FusionAuth/fusionauth-issues/assets/44510264/93297d01-d399-4fc8-a983-31c8e12290c0)

### Platform
 - macOS
 - Chrome Version 120.0.6099.129

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
Issue may be impacting elasticsearch querying as well in recent issue here: https://github.com/FusionAuth/fusionauth-typescript-client/issues/96

This is where we initially discovered the email formatting and tested how this got into the database.

**Comment by robotdan** [comment]
I believe this is working as designed. The Import API in some areas is intentionally less strict than the User Create / Update to allow imports to go more smoothly. 

It can be very difficult to know what a valid email address looks like. While this one is quite obviously not valid - it is not always that simple. The best way to tell if an email is valid is to validate it by trying to send something to it. 

If you are importing an email address, we make the assumption that "you" the developer thought this email address was valid at some point in time because you had it your data model. 

I would prefer to leave this behavior as is because it affords us some flexibility in allowing you to bring data into FusionAuth. It is up to the one using the Import API to ensure the data is correct and pristine to the best of their knowledge.

**Comment by matt1hathcock** [comment]
thanks @robotdan ok to close I assume

**Comment by idasilva** [comment]
i'v been working on a migration project to FusionAuth and needed to get existent users with a non-standard email format, the import api was very import.

**Comment by mooreds** [comment]
@idasilva thanks for using FusionAuth. If you have an issue or feature request, please open a new issue rather than commenting on an old issue.
