### ISSUE TITLE
jwt.refresh-token.revoke not firing

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#261]
### Description 
Even after setting up the web hook to listen to `jwt.refresh-token.revoke`, apparently this event is never fired.

### Steps to reproduce

1
![image](https://user-images.githubusercontent.com/15204146/62741941-8a4bef80-b9f1-11e9-8f1b-515b1bd9dc61.png)

2
![image](https://user-images.githubusercontent.com/15204146/62741946-8f10a380-b9f1-11e9-87a0-8ca65eae16ee.png)

3
![image](https://user-images.githubusercontent.com/15204146/62741950-9172fd80-b9f1-11e9-9708-743e0c8d6e75.png)

4
![image](https://user-images.githubusercontent.com/15204146/62744578-00edea80-b9fc-11e9-87d3-c649858f8dfa.png)

5
```
curl --request DELETE \
  --url 'http://localhost:9011/api/jwt/refresh?userId=<user_id>' \
  --header 'authorization: <api_key>'
```
### Expected behavior
The event to fire. But I get nothing on the configured URL.

### Platform
v1.7.2

**Comment by robotdan** [comment]
That event should be sent as a result of your `curl` example. What is the HTTP status code on your curl response? 

As long as the user has at least one refresh token you should see the event fired. 

When you use the test a webhook interface and you see the `The event was successfully sent.`, did your webhook receive any JSON? For us to return that status you must have returned a `200`. 

In that example your webhook is `http://host.docker.internal:4000/useres/mage-logout`, is that the same webhook as `http://localhost:8080/test` in your other screenshots?

**Comment by AlvMF1** [comment]
> What is the HTTP status code on your curl response?

200

> ...did your webhook receive any JSON?

It did.

> ...is that the same webhook as...?

I've updated the screenshot. The correct address is `http://localhost:8080/test`.

**Comment by robotdan** [comment]
For good measure, can you make this request right before deleting the refresh tokens for this user to ensure at least one exists? 

```
curl --request GET \
  --url 'http://localhost:9011/api/jwt/refresh?userId=<user_id>' \
  --header 'authorization: <api_key>'
```

https://fusionauth.io/docs/v1/tech/apis/jwt#retrieve-refresh-tokens

**Comment by AlvMF1** [comment]
Ah, that was it. Like you said before:
> As long as the user has at least one refresh token you should see the event fired.

Is that documented anywhere? Also, shouldn't it fire anyways, since we get a `200` out of the `DELETE`?

**Comment by robotdan** [comment]
Ok, good deal, assumed that may be the case.  

Returning a `200` from the Revoke JWT API seems correct to me, since we did what you asked, the user exists by that Id and we did attempt successfully to delete all refresh tokens owned by the user.  

Regarding the doc for that event, 

https://fusionauth.io/docs/v1/tech/events-webhooks/events#jwt-refresh-token-revoke

> The following scenarios will cause this event to be generated:
>- A single Refresh Token is revoked
> - All Refresh Tokens owned by a single User are revoked
> - All Refresh Tokens for an Application are revoked

From one perspective the text described for that event does sound like it would be possible to send an event when `All Refresh Tokens owned by a single User are revoked` even if no refresh tokens were revoked. 

Do you think there is a benefit to send the event when no tokens were deleted? We could send this event for each of the scenarios outlined above regardless of if anything was actually deleted. 

I'd have to think about that some more, but let me know how you're using this and that may help.

**Comment by AlvMF1** [comment]
Maybe there's no benefit other than consistency? I guess a doc addition would be enough.
Up to you guys.

Thanks, anyways!

**Comment by robotdan** [comment]
Thanks for the feedback @AlvMF1 we'll kick this around a bit and see what we come up with.

**Comment by mooreds** [comment]
This should be documented under https://github.com/FusionAuth/fusionauth-site/pull/966

**Comment by mooreds** [comment]
Closing, as this is deployed.
