### ISSUE TITLE
Provide a default From Email for Email Template configuration

### ISSUE THREAD

**Issue by engineertdog** [FusionAuth/fusionauth-issues#262]
### Problem
When you first set up email in the FA UI, you then have to go and manually change the `From` email for all of the templates.

### Solution
I think that by default, the templates should use the email set in the SMTP settings, but be configurable so that email templates can use another email if requested. However, I think that utilizing the default email set in the SMTP settings would suffice in a majority of cases because this should be a general informational email address for the authentication service.

### Alternatives/workarounds
One alternative would be to be able to test send any email template by providing an email address to send the test to. The result would be a full log of how the test went. This could also suffice as another feature request as it would be something desirable to see. Tests like these can be found in many applications, and I think it would be another benefit, in addition to the original FR.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
> I think that by default, the templates should use the email set in the SMTP settings, but be configurable so that email templates can use another email if requested.

There is not currently an email address in the SMTP settings, the username may be an email address in some cases, but not necessarily. 

We could perhaps add a default "From address" that would be used by all templates by default that would be defined in the "global" email configuration unless otherwise overridden per template. 


> One alternative would be to be able to test send any email template by providing an email address to send the test to. The result would be a full log of how the test went. 

This is in plan, we intend to have a test button on the SMTP configuration, and then at some point within the email template UI have an option to send any particular template to an email address. We would either provide the output as a result of the action, or send the results to the event log.

Thanks for the feedback and suggestions.

**Comment by engineertdog** [comment]
> > I think that by default, the templates should use the email set in the SMTP settings, but be configurable so that email templates can use another email if requested.
> 
> There is not currently an email address in the SMTP settings, the username may be an email address in some cases, but not necessarily.
> 
> We could perhaps add a default "From address" that would be used by all templates by default that would be defined in the "global" email configuration unless otherwise overridden per template.

Ah you're right. I never thought about it because in my implementations, the username is always an email. I forgot about instances where that's not the case. I think that would be an easily suitable solution.

> > One alternative would be to be able to test send any email template by providing an email address to send the test to. The result would be a full log of how the test went.
> 
> This is in plan, we intend to have a test button on the SMTP configuration, and then at some point within the email template UI have an option to send any particular template to an email address. We would either provide the output as a result of the action, or send the results to the event log.

That sounds good to me!

**Comment by robotdan** [comment]
We could also think about adding a default base URL that could be made available in the email templates. 

That way could ship the email templates with a URL value of `${baseURL}/email/verify/${verificationId}` instead of `http://localhost:9011/email/verify/${verificationId}`.

See this suggestion from https://github.com/tauinger-de via issue https://github.com/FusionAuth/fusionauth-issues/issues/294

**Comment by MrKanthaliya** [comment]
Is this feature got implemented? I am still getting emails from userrname mentioned SMTP configuration instead of 'From Email' in email templates.

**Comment by voidmain** [comment]
@MrKanthaliya this could be caused by your SMTP server. FusionAuth sends a MIME email to the SMTP server with the `From` header in the format `from-name <from-email>`. The SMTP server might be removing this and replacing it with your SMTP username.

**Comment by MrKanthaliya** [comment]
Hi @voidmain , just tested with sendgrid. works fine with `smtp.sendgrid.net`  but getting same issue with `smtp.gmail.com`.

**Comment by voidmain** [comment]
Ah. Gmail isn't technically a general purpose SMTP server. It only allows you to send mail as a single Gmail user. Therefore, Gmail will likely ignore some of the email headers coming in. Sounds like they are ignoring the `From` header.

Sendgrid is a better solution for sending emails to users. You can also use the AWS SES. Most cloud providers have an email service as well. These services are designed to send emails from applications and backend services, so they will support all the headers.
