### ISSUE TITLE
Can using fusionauth with NestJS?

### ISSUE THREAD

**Issue by nguyenthanhtien** [FusionAuth/fusionauth-issues#2703]
Our team want using fusionauth with NestJS.  Can guide me how to implementation FusionAuth for NestJS backend with jwt?

**Comment by mooreds** [comment]
Hi @nguyenthanhtien 

Thanks for your question. I'm not aware of any nestjs implementations, but FusionAuth should work with any of these OIDC plugins: https://www.google.com/search?client=firefox-b-1-d&q=nestjs+oidc 

I'm not endorsing any of those, since I haven't used one, but any OIDC plugin should work with FusionAuth for adding login to your app. If you need more integration, you can use our Typescript client library: https://fusionauth.io/docs/sdks/typescript

GitHub issues are for bug reports and feature requests. If you have further questions, please [ask in our forum](https://fusionauth.io/community/forum/) or [open a support ticket](https://account.fusionauth.io/account/support/).

I'm going to close this issue.
