### ISSUE TITLE
[Bug]: Bulk deletes fail when using AWS-hosted Opensearch

### ISSUE THREAD

**Issue by lyleschemmerling** [FusionAuth/fusionauth-issues#2744]
### What happened?

We have a report of the [bulk delete users API](https://fusionauth.io/docs/apis/users#bulk-delete-users) failing when using an AWS-hosted Opensearch instance for self-hosted FusionAuth.

using an api call
```
/api/user/bulk?hardDelete=true&dryRun=true&limit=1&queryString=*
```

fails both using the Elasticsearch compatibility mode reporting 7.10 and the Opensearch mode 2.11 with the following error response:

```
{
   "fieldErrors": {},
   "generalErrors": [
     {
     "code": "[SearchEngineRequestFailedException]",
     "message": "A request to the search index has failed. This error is unexpected. Please review the troubleshooting guide found in the documentation for assistance and the available support channels."
     }
   ]
}
```

and an error in the logs:

```
 ERROR io.fusionauth.api.service.search.BaseElasticsearchSearchEngine - Failed to set a Point in Time on index [fusionauth_user].
```

This does not appear to affect instances of Elasticsearch or Opensearch running via docker images, so this may be specific to the AWS-managed service.

### Version

1.49.2

### Affects Versions

\>= 1.48.0

**Comment by robotdan** [comment]
I think this is working as designed isn't it? Is this the case where the AWS service is in a compatibility mode so it looks like Elasticsearch but is actually OpenSearch or vise vers?  If so, that is working as designed, we won't be able to guess what the underlying service actually is if we are told it is one or the other. 

If this is a legit bug otherwise, please clarify.
