### ISSUE TITLE
Timeout on add/update user through web/api when changed password algorithm

### ISSUE THREAD

**Issue by thlautg** [FusionAuth/fusionauth-issues#2799]
## (Put bug title here)
When changed password algorithm for tenant, the following actions/apis will timeout
* timeout on update user api: 
   url: `api/user/{{uuid}}` 
   body:
```
{
    "applicationId": "{{application-id}}",
    "user": {
        "password": "supersecurepassword" // new password
    }
}
```

* timeout on creating a new user using web portal

### Description 
Timeout on add/update user through web/api when changed password algorithm

### Observed versions
1.50.1

### Affects versions
1.50.1

### Steps to reproduce
1. create a new tenant
2. create a test user for this tenant user+inv1@gmail.com (this should success)
3. change password for this user using postman api user+inv1@gmail.com (this should success)
4. change the password algorithm for this tenant 
5. create another test user for this tenant user+inv2@gmail.com (this should failed by timeout)
6. change password for old user using postman api user+inv1@gmail.com (this should failed by timeout)

### Expected behavior
The api/web portal action should not timeout, they should work as expected

### Screenshots
If applicable, add screenshots to help explain your problem. Delete this section if it is not applicable. 

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: Windows
 - Browser + version: Chrome 126.0.6478.127
 - Database: postgres 14.11

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

**Comment by mooreds** [comment]
@thlautg thanks for filing this bug. 

What were the values of the password algorithm (original and new)? 

Where they both built-in algorithms ([as documented here](https://fusionauth.io/docs/reference/password-hashes)) or was one custom?

**Comment by thlautg** [comment]
@mooreds Thanks for replying!

The algorithem and the corresping settings are built-in, they are as follows

Original (when making a new tenant):
(actually they are just default values)
- Cryptographic hash settings:
  - Scheme: Salted PBKDF2 with SHA-256 with 256-bit derived key
  - Factor: 24000
  - Re-hash on login or change: disabled
- Password settings
  - Minimum length: 8
  - Maximum length: 256
  - all other complexity setting are off

Updated:
- Cryptographic hash settings:
  - Scheme: Salted Bcrypt
  - Factor: 30
  - Re-hash on login or change: enabled
- Password settings
  - Minimum length: 8
  - Maximum length: 50
  - all other complexity setting are off

**Comment by mooreds** [comment]
Gotcha. 30 is quite high for a bcrypt factor. 

See https://stackoverflow.com/a/75691338 where a factor of 16 takes 3 seconds to hash on a local computer. Since each increase in the factor roughly doubles the amount of time it takes to hash the password, I'd expect it to take on the order of 50000 seconds, or 13 hours (of course it depends on the hardware). 

Can you try dialing that factor back to 14 or 15 and see if you see the timeout?

**Comment by thlautg** [comment]
Hi @mooreds , thanks for the solution, chaning back the factor to 15 solves the timeout problem, though it does take ~8 seconds to make the api call

**Comment by mooreds** [comment]
Yup. That is because the hashing is taking that long (primarily). 

You could also test 13 and 14 as factors. 

You're weighing the balance between preventing credential stuffing and good user experience. Our CEO wrote an article about it: https://fusionauth.io/articles/security/math-of-password-hashing-algorithms-entropy 

Thanks for using FusionAuth!
