### ISSUE TITLE
Documentation improvement - search on user data

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#30]
As you explained, we can search by user data like `data.Foo: Bar`.
Could add this in the documentation?

Also, how can I search user data from a specific application? Since we can register user data for each application, how could I find those data?

**Comment by robotdan** [comment]
Yes, we will add some examples to the documentation. 

To search by Application, you may use the following query string where the Application Id is `3c219e58-ed0e-4b18-ad48-f4f92793ae32`. 

```
registrations.applicationId:3c219e58-ed0e-4b18-ad48-f4f92793ae32
```

So to search on `data.Foo:Bar` for users in a particular application, you'd join these together:

```
registrations.applicationId:3c219e58-ed0e-4b18-ad48-f4f92793ae32 AND data.Foo:Bar
```

If you end up doing any searches in the UI, you can expand the `Advanced` section click `Show query string` to see how we are building the corresponding Elasticsearch query string based upon the input field and the selectors that scope the search by group, application or role. 

We are looking to build out intelli-sense on our search input field in the UI to provide a more powerful search experience without requiring the user to understand the [Elasticsearch query string DSL](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html). 

Let me know if that gets you past this hurdle. Thanks.

**Comment by robotdan** [comment]
Pending documentation update. Need to document examples of the query search string and perhaps add a link to the Elastic query string DSL.

**Comment by ChakshuGautam** [comment]
I am using the following query `"queryString": "mobilePhone: some phone number"` but am unable to get any result. I am able to search using fullName, etc easily.

**Comment by robotdan** [comment]
Hi @ChakshuGautam the `mobilePhone` will indexed be available in the upcoming version. 
See https://github.com/FusionAuth/fusionauth-issues/issues/165

**Comment by ChakshuGautam** [comment]
Sorry for the duplicate comment. Really thankful for such an awesome product.

**Comment by andrei-tara** [comment]
Is there a way to sort results on from user data ? using fusionauth-java-client did not find any way of doing that allowed fields are only birthDate, email, fullName, insertInstant, login, tenantId, username. Did sort by querying elastic search directly and it seems to work. Is there any plan to include this feature?

**Comment by robotdan** [comment]
Thanks for the comment @andrei-tara  - you're correct, the only fields that you can current sort on are the ones you mentioned. The reason for this limitation is due to how we construct the Elasticsearch index. 

We only index specific fields as `keyword` or optionally when `text` we enable `fielddata` to allow sorting. For example, a `text` field that does not explicitly have `fielddata` enabled cannot be sorted in the Elasticsearch index. We do this for memory and storage reasons, Elasticsearch stores more data in order to create a sortable field vs a non-sortable field. We do not store entire documents in Elasticsearch, we only build indexes to use to more quickly look up users by Id in the relational db. 

When we index custom data, we allow Elasticsearch to guess at the field type, and so I suppose it is possible that certain fields are sortable within your custom data. 

Can you provide an example query string you used to sort on your custom data, and the output of your index mapping? 

Get Index mapping: `curl http://localhost:9021/fusionauth_user/_mapping/_doc`

**Comment by mooreds** [comment]
Added an example of searching `user.data`.  https://github.com/FusionAuth/fusionauth-site/pull/324 Missed the request to search on `registration.data` so will leave this open to add that.

**Comment by mooreds** [comment]
Added example in https://github.com/FusionAuth/fusionauth-site/pull/326 , closing.

**Comment by browniefed** [comment]
Is querying for `mobilePhone` only available if you are running Elastic Search?

This would be a nice addition to be able to just query normally (non-fuzzy) for mobile phone too, via the database search (non-elastic).

**Comment by mooreds** [comment]
@browniefed this seems like a support question. Please feel free to ask it in our community forum: https://fusionauth.io/community/forum/ or file a support ticket if you have an edition with engineering support: https://account.fusionauth.io/account/support/
