### ISSUE TITLE
Themes - some user templates ignored and can't be reset to default

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#304]
v 1.8.1 RC 1

Edits to the following user theme pages are ignored.  Changes are saved but the Fusion version is rendered to the browser. These pages also ignore the user's stylesheet and helpers.

This list is not exhaustive since I don't have an easy way to trigger many of the pages we aren't using.  If the error configuration of the page is returned to the user - it should probably also use the user stylesheet and helpers.

Also please note that it is no longer possible to delete template content in the user theme in an effort to restore the defaults. The editor refuses to save a blank template.

password/complete
password/sent
email/complete
email/send
oauth2Error

**Comment by robotdan** [comment]
This is working as designed. Due to the new theming options, a theme per tenant, unless we have a way to identify the tenant properly we cannot use a theme and we'll use the default FusionAuth theme. 


https://fusionauth.io/docs/v1/tech/release-notes/

> When using a theme, whenever possible provide the tenantId on the request using an HTTP request parameter. This will help ensure FusionAuth will render the page using your chosen theme. In most cases FusionAuth can identify the correct tenant and theme based upon other parameters in the request, but in some circumstances there is not enough information and FusionAuth will default to the stock theme if the tenantId is not explicitly provided.
> 
> For example in each of the shipped email templates the following has been added to the generated URL ?tenantId=${tenantId}. You may wish to add this to your email templates if you’re using themes.

You'll want to update any email template you're using that just takes an Id such as the Setup Password and Change Password templates (and others) to append `?tenantId=${user.tenantId}` to the URL. This will ensure that even if the `changePasswordId` is expired and we cannot resolve it to a user, we will still know which tenant you're requesting. 

The second part will be to ensure you have the tenantId preserved in a hidden field so that we can transition you from the Forgot password to a Sent template and preserve the requested theme. 

If you review the stock theme `_helpers.ftl` file you'll see that we now have a macro used on several front end pages such as `sent` and `complete`. 

```
[#macro oauthHiddenFields]
  [@hidden name="client_id"/]
  [@hidden name="code_challenge"/]
  [@hidden name="code_challenge_method"/]
  [@hidden name="metaData.device.name"/]
  [@hidden name="metaData.device.type"/]
  [@hidden name="nonce"/]
  [@hidden name="redirect_uri"/]
  [@hidden name="response_type"/]
  [@hidden name="scope"/]
  [@hidden name="state"/]
  [@hidden name="tenantId"/]
  [@hidden name="timezone"/]
[/#macro]
```

You could optionally use that macro, or just ensure you have added `[@hidden name="tenantId"/]` to your templates where you have other hidden fields such as `[@hidden name="client_id"/]`. 



> Also please note that it is no longer possible to delete template content in the user theme in an effort to restore the defaults. The editor refuses to save a blank template.

This is correct, previously we allowed partial themes, which means we would only save the modified parts of the theme. This caused a few issues because if you didn't modify the `_helpers` for example we may update it during the next release and it could in theory break uses. So now each theme is complete and standalone.  This also means that we don't allow you to revert to a default (which would be the FusionAuth stock theme) because we don't know if it will be compatible with your theme. 

If you want to "default" a template, you can copy and paste the template from the FusionAuth theme, but depending upon how your theme works, you may have to make changes to make it work in your theme. 

I hope that helps. I apologize for these issues, they are sort of growing pains of our theming strategy. In order to make themes work per tenant we had to add a few more details.

**Comment by davidmw** [comment]
Thanks Dan but there is still some strangeness to themes in our instance.

The FusionAuth theme does not contain oauthHiddenFields macro. If I use the + button to add a theme, the new one also lacks the macro.  Would it be possible to update our default theme if you sent it as JSON and we use the Create Theme api? 

The link from /oauth2/authorize for /password/forgot includes the tenant id.

The forgotten password screen is correctly themed and contains hidden field for tenant which is set correctly. The form on this screen posts to itself with 

`  <form action="forgot" method="POST" class="full">`

so /password/forgot reappears in the browser with no parameters. 

Then the /password/sent screen is shown, with no parameters on URL, no hidden fields, and no theme.

Another video: https://www.loom.com/share/f894a72ad10443b2a77ad4eff8005461

**Comment by robotdan** [comment]
What version are you running, we fixed an issue in `1.9.0` where the `tenantId` was not passed along to the `/password/sent` template which means it would not be themed correctly. I wonder if this is what you're encountering.

**Comment by davidmw** [comment]
1.9.2 has indeed fixed the issue and revealed the missing macro with the updated default templates. 1.8.1.RC1 was current until two? days ago. Please think about publishing the release notes content on RSS since notifications don't seem to be happening other ways.

**Comment by robotdan** [comment]
Thanks for the feedback @davidmw we could look at some sort of push notification or just a dedicated email for release notes and release announcements.
