### ISSUE TITLE
/api/user/import silently fails if one user already exists

### ISSUE THREAD

**Issue by AlvMF1** [FusionAuth/fusionauth-issues#317]
### Description 
When importing more than one user, if at least one user already exists, all the others are ignored even though we get a 200.

### Steps to reproduce
1. POST to `/api/user/import` with one user (`user1@test.com`) - 200, user is added ✅ 
2. POST to `/api/user/import` with two users (`user1@test.com` and `user2@test.com`) - 200, no user is added 🛑 
3. POST to `/api/user/import` with two users (`user2@test.com` and `user3@test.com`) - 200, two users are added ✅ 

### Expected behavior
Ignore users that already exist, but add all the others. A list of ignored users might be useful as well. 😄 

### Platform
FA v1.9.2

**Comment by robotdan** [comment]
Thanks for the report @AlvMF1 this is a known issue. 

A little background: 

- The Import API is designed to be super duper fast. For this reason, we do not perform validation on certain FK constraints. 
- The initial intent was that you'd import with an empty database, and would not have any duplicates. (See bullet point one)

What is happening is that we take a FK violation and we exception and then we are not returning the correct response code when we fail. This will be corrected soon and ideally we'd return a `400` with a JSON error indicating you should run the same command again with additional validation enabled. 

In your scenario since you do have users in the database, you want to perform additional validation so that you get a more helpful error response.  See `validateDbConstraints` on the Import API. I would expect you to receive a nice JSON response when using this mode. 

```
{
  "validateDbConstraints": true
}
```

https://fusionauth.io/docs/v1/tech/apis/users#import-users

**Comment by AlvMF1** [comment]
Cool, I can work with `validateDbConstraints` for now. But the additional param to ignore would be great!

**Comment by robotdan** [comment]
Available in 1.11.0
