### ISSUE TITLE
[SAMLv2] Identity Provider's issuer property absent

### ISSUE THREAD

**Issue by leomdg** [FusionAuth/fusionauth-issues#329]
### Description 
Upon retrieving an Identity Provider previously created (including its "issuer"), the retrieved record does not include said property.

### Steps to reproduce
1. Create an Identity Provider, including the "issuer" property.
2. Retrieve previously created Identity Provider.

### Expected behavior
"Issuer" property should be included in the retrieved Identity Provider record.

### Additional context
This issue was experienced through the Python client specifically.
No test has been done with other clients.

**Comment by robotdan** [comment]
@trex  I think this a doc issue, we auto-generate the SAML v2 SP issuer.

Can you confirm, and then update the doc? I think we'll need to remove the `issuer` from the request and response example JSON and request body properties. 

In the UI we will display the Issuer, MetaData and Callback (ACS) in the SAML v2 Integration Details section. We should review how to communicate this in the API. Since we won't always know the correct endpoint when in the API, we could simply document the API that these values are generated and viewable in the UI. 

- ACS - `<base_url>/samlv2/acs`
- Issuer - `<base_url>/samlv2/sp/{identityProvider.id}`
- Metadata - `<base_url>/samlv2/sp/{identityProvider.id}`

**Comment by matthew-altman** [comment]
api docs updated to remove `issuer` and explain the integration values
