### ISSUE TITLE
Support for  "Sign in with Apple"

### ISSUE THREAD

**Issue by pawpro** [FusionAuth/fusionauth-issues#336]
### Description
1. Apple does not provide `Userinfo` endpoint which is required under FusionAuth OpenID configuration.
2. As it seems Apple may be returning the email address only once (the first time).

### More info
https://developer.apple.com/documentation/signinwithapplerestapi/authenticating_users_with_sign_in_with_apple

In particular:
> Ensure that your app relays the credentials and user information to your app servers. The API collects this information and shares it with your app the first time the user logs in to the app using Sign in with Apple. If the user then uses Sign in with Apple on another device, the API doesn't ask for the user’s name or email again. It collects the information again only if the user stops using Sign in with Apple and later reconnects to your app.
> 
> Because the user’s information isn’t shared with your app in any subsequent API calls, your app should store it locally, immediately after you receive it from the API response. In case of subsequent failures in your process or network, you can read the information from local storage and try processing it again.

### Additional Context

https://developer.apple.com/documentation/signinwithapplejs/configuring_your_webpage_for_sign_in_with_apple
https://bitbucket.org/openid/connect/src/default/How-Sign-in-with-Apple-differs-from-OpenID-Connect.md

**Comment by robotdan** [comment]
It is possible this won't work with our OpenID Connection integration if they are not OpenID Compliant. 

https://developer.apple.com/documentation/signinwithapplejs/configuring_your_webpage_for_sign_in_with_apple

This seems to imply that the user comes back on the access token response, which we are not currently parsing and passing to a lambda or anything like that. 

It seems they are planning to be OpenID Connect compliant, or attempt to be anyway. 
https://openid.net/2019/06/27/open-letter-from-the-openid-foundation-to-apple-regarding-sign-in-with-apple/
https://bitbucket.org/openid/connect/src/default/How-Sign-in-with-Apple-differs-from-OpenID-Connect.md

The bitbucket link says the following in the Peculiarities section:


> * No Discovery document is published at https://appleid.apple.com/.well-known/openid-configuration which makes developers have to read through the Apple docs to find out about endpoints, scopes, signing algorithms, authentication methods, etc.
> * No UserInfo endpoint is provided, which means all of the claims about users have to be included in the (expiring and potentially large) id_token.

This makes it incompatible with our OpenID Connect IdP configuration. 

We could add an Apple configuration that would be specific, similar to what we do for Twitter, Google and Facebook. 

In theory we could pull stuff out of the `id_token` but that would mean we'd have to verify the token signature manually and since they do not publish an OpenId Discover document this makes it difficult because we don't know how to discover their public keys. 

If Apple decides to properly support OpenID Connect by adding the Userinfo endpoint and discovery document then it will work with what we have today.

**Comment by pawpro** [comment]
Apple is providing JSON Web Key here https://appleid.apple.com/auth/keys this can be used to generate their public key. It also appears that the auth/tokens request id_token returned the first (and only the first time) will include the user's email.

This all means that if:
 - userinfo endpoint would be optional
 - id_token information would be verified and used to populate "userinfo"
 - the JWT argument in reconcile lambda would receive a merged id_token info and userinfo or both separately for manual reconciliation

This could provide ability to complete the flow successfully.

**Comment by robotdan** [comment]
Thanks for the update @pawpro. 

The `Userinfo` endpoint takes the `access_token` instead of the `id_token`, so if we were to build support for Sign in with Apple assuming they are not going to fully adopt OpenID Connect, we'd need to build a separate login type to support their implementation. 

We currently require an email address, so to the extent they will return us an email address in the `id_token` or in the `user` object returned on their Token response, we can complete login on our end.

**Comment by robotdan** [comment]
Discussion on reconciling a user by unique Id rather than email address that is relevant to this discussion here --> https://github.com/FusionAuth/fusionauth-issues/issues/336

**Comment by pawpro** [comment]
@robotdan do you mean #341 or #346 ?

**Comment by robotdan** [comment]
Ha.. thanks @pawpro yes, I meant https://github.com/FusionAuth/fusionauth-issues/issues/346
