### ISSUE TITLE
OAuth Endpoint Log out

### ISSUE THREAD

**Issue by janakapdj** [FusionAuth/fusionauth-issues#342]
OAuth Endpoint Log out not work with axios

Hi 

when its sent user log out request through browser its return http : 200  (it should return 302) and not invalidated user session held by fusion auth but when its try directly put on browser url its work as expected and user get lou out
blow is my browser request 
FYI (I try to adding API key to header/ with out tenantId too but got same result)

Request URL: http://myfusionserver.com:9011/oauth2/logout?client_id=c6bcfb81-7387-4448-92fe-979fbc183864&tenantId=998aa744-18a5-42b9-0dfe-e11f73d68a41
Request Method: GET
Status Code: 200 
Remote Address: myfusionserver.com:9011
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Expose-Headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
Content-Type: text/html;charset=UTF-8
Date: Fri, 18 Oct 2019 04:17:48 GMT
Transfer-Encoding: chunked
Vary: Origin
Provisional headers are shown
Accept: application/json, text/plain, */*
Origin: http://localhost:3000
Referer: http://localhost:3000/dashboard
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
client_id: c6bcfb81-7387-4448-92fe-979fbc183864
tenantId: 998aa744-18a5-42b9-0dfe-e11f73d68a41

![app](https://user-images.githubusercontent.com/5866239/67067754-1ec29300-f195-11e9-8607-2c5b1cd4c877.png)
Please help with this , if you want to know see any application settings please let me know

**Comment by robotdan** [comment]
This is the intended behavior of this endpoint. 

If you don't call `/oauth2/logout` using a redirect (GET) in the browser (user-agent) there is no session cookie that can be utilized to end the user session. 

This endpoint is what we call a "front channel" logout, so it is intended to be used with a user-agent.  This endpoint returns `200` because it will build an iframe with a logout URL for each application in the tenant to complete logout for all applications, and then perform a redirect using a `<meta http-equiv="refresh" /> ` tag back to your application. 
https://fusionauth.io/docs/v1/tech/oauth/endpoints#logout

**Comment by janakapdj** [comment]
Hi @robotdan 
thanks for explanation ,with redirect its work
