### ISSUE TITLE
Edit roles on an existing application

### ISSUE THREAD

**Issue by trex** [FusionAuth/fusionauth-issues#344]
### Problem
When creating an application in the FusionAuth admin UI I can add roles to the application.  When I save, and later edit that application, I expect to be able to edit and add roles for this application.

### Solution
"Roles" tab exists on /admin/application/edit in the FusionAuth admin UI allowing the admin user to edit, add and delete roles for this application.

### Alternatives/workarounds
The api can be used to add/edit/delete roles and update an application.  See:
https://fusionauth.io/docs/v1/tech/apis/applications

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by voidmain** [comment]
This is actually something we discussed and decided not to implement early on. 

The reason we don't allow roles to be edited on the edit application screen is roles are often used in code and any modifications (adds, edits or deletes) could have unintended consequences to the integration. If an admin were to click to edit an application and accidentally delete a role either via a stray mouse click or a keyboard click, saving the application could cause issues. 

Also, deleting a role has major consequences because it removes that role from every user that it has been assigned to.

I'm okay adding this in if everyone likes the idea and doesn't think it is dangerous. We can also make the process of deleting a role extremely difficult and even go as far as adding additional roles in the FusionAuth admin UI to control if a user can delete roles.

**Comment by bostjan** [comment]
I agree with @trex, the lack of this feature feels odd.

In every larger SaaS product that you start using, it's quite unlikely that the authentication/authorization configuration will be set in stone the moment SSO is set up. Often one team purchases the product, but then _other_ teams from within the same organization want to leverage said product too, and the usage+authentication scope expands. Forcing users to recreate the application (and all registrations + updating SSO on the SP side) instead of just editing/adding the roles seems... limiting.

I think @voidmain suggestion (a separate permission + enough warnings) should be a good enough approach.

**Comment by robotdan** [comment]
To clarify the issue - since I didn’t see it listed as an alternative. 

Once an application exists, you can edit roles in the UI. The role management is just on a separate page. Applications > Roles (purple button).

@bostjan do you know you can edit roles in the UI -just on a separate page. Or are you aware of this and you don’t like the UX of managing roles on a separate page after application creation?

**Comment by bostjan** [comment]
@robotdan oh cr*p, you're right, I've totally missed that.

Sorry for the false info, I am completely fine with where it is.

PS: This input of mine does suggest where I intuitively expected to find it, so a UX hint for you ;)
