### ISSUE TITLE
Feature : Passwordless  login

### ISSUE THREAD

**Issue by JanLoebel** [FusionAuth/fusionauth-issues#38]
### Problem
We don't want the user to remember another password, therefore we want to support "passwordless" authentication. The user enter his E-Mail address as the login credential and receives a mail with a link (including a secret token), if the click that link, the token is checked by FusionAuth and then you will be redirected to the application with e.g. the resulting JWT.

### Solution
We would also support you by implementing this feature request as a plugin, but as far as we've seen this is not yet possible with the current plugin-architecture.

### Alternatives/workarounds
Another option would be to implement it directly as another "provider".

### Additional context
See other projects like:
- https://passwordless.net/
- https://github.com/PwdLess/Cierge

**Comment by robotdan** [comment]
Thanks @JanLoebel for the feature request. This is definitely on the road map. 

We have most of the pieces to make this work in place already, but we have not yet enabled this login workflow. 

In your deal implementation, would you want to be able to restrict this feature by FusionAuth Application or any other criteria?

Would you primarily be looking to use this feature with email, or do you think you'd be using this feature with SMS push as well? 

> ... but as far as we've seen this is not yet possible with the current plugin-architecture.

You are correct. Currently the only plugin option we support is for additional password encryptors. 

We will take a look at what it would take to deliver this feature and prioritize it with the work that we have in progress. Thanks for the feedback, it is appreciated.

**Comment by JanLoebel** [comment]
@robotdan you're welcome. I also really appreciate the work you do with FusionAuth. 

Restricting the authentication to any FusionAuth Application would be enough for us. 

In our use-case there is also the request to support email authentication. But in general I'm pretty sure that there will also be people who want to support SMS or another push solution. Therefore, I would recommend you to implement the "default" email-notification workflow but support sending the one time token by your plugin-architecture also to other systems. I think the interface for that should be very easy and everybody could extend the token delivery function them self.

Looking forward to the road map. If I can contribute anything or you want to discuss some ideas, let me know :)

**Comment by chaudhry** [comment]
@robotdan It would be great if you can provide support for SMS as well. 

Cheers to you guys.

**Comment by robotdan** [comment]
In progress. Initial support will likely be email only.

**Comment by JanLoebel** [comment]
Awesome! If you need anything or want to discuss something let me know :)

**Comment by robotdan** [comment]
Thanks @JanLoebel 

Here is what we are currently building: 

1. Enable / disable passwordless login per application, default will be disabled
2. New API to push a passwordless link, to begin with, likely just email. For example [POST] `/api/passwordless/login`, or something like that. 
3. A new globally configured email template that can be overridden per tenant
4. The existing Login API and OAuth2 Authorization grants will be able to take this one time password in lieu of a username and password. 
5. The default TTL for these one time passwords will be 2-3 minutes, this can be configured. 
6. Our login page will have a link or button if passwordless is enabled to "Send me a Login link" or something like that. 
7. If 2FA is enabled, you'll still need to provide the 2FA challenge after you click the passwordless link.

Undecided if using passwordless login can return a refresh token, and undecided what password change required means in this workflow. If an application is doing all passwordless, then forcing the user to change their password is not helpful. In a scenario where passwords are used, and for some applications passwordless is allowed - then it gets fuzzy. 

Any feedback, or is this missing anything to satisfy your use case?

**Comment by JanLoebel** [comment]
So far it sounds pretty good :) I think the workflow could be something like:

1. User enter email-address and press "Send me a Login link"
2. User recieve a mail with a link which includes "userId" and "oneTimeToken" (link can be configured)
3. This userId and OneTime-Token can be exchanged by "FusionAuth" with a "Access-Token" and "Refresh-Token" like OAuth.

The password change could afterwards be handled like any other login provider. I think most of the people will just use passwordless link or another provider but not both combined. But you're right, that could get a little bit fuzzy, that's the reason why I think the credentials (access/refresh-token) should be handled after the link like any other provider do. I hope you get what I mean :)

**Comment by robotdan** [comment]
Initial support for Passwordless is available in 1.5.0. Documentation should be available shortly. 
https://fusionauth.io/docs/v1/tech/release-notes/

**Comment by nraibaud** [comment]
Hi,
We use the /api/passwordless/send API.
But it returns 403...
In fusionauth administration panel, i cannot see the field for activate password less,
but we have
<img width="917" alt="Capture d’écran 2019-05-25 à 17 52 26" src="https://user-images.githubusercontent.com/2615311/58371876-eedccf80-7f15-11e9-9529-2371ea100434.png">


https://fusionauth.io/blog/2019/03/28/fusionauth-passwordless

Why? any idea?
Thanks a lot

**Comment by voidmain** [comment]
Hi @nraibaud. 

The error you are seeing when you try to save the System Configuration with new email settings is actually Chrome trying to prevent cross-site scripting. The reason for this is that under the "UI" tab, you can configure the login theme templates that control the OAuth login pages for FusionAuth. These textareas contain HTML, CSS, and JavaScript. When Chrome sees a form submit with JavaScript, it complains about possible XSS attacks.

This issue was fixed back in version 1.5.0 by adding the `X-XSS-Protection` header in our responses. If you open your Inspector in Chrome, you should see this header being sent back by FusionAuth on the System Configuration edit page. 

It could be that your version of Chrome doesn't support that header. You might need to try a different browser in order to enable email settings. You could also see if Chrome is up-to-date.

**Comment by nraibaud** [comment]
@voidmain ok works only over Firefox.
Now i can see passwordless, and when activated, no more 403 :)
But the 200, response is empty :(

**Comment by robotdan** [comment]
@nraibaud can you open a new issue if you need assistance with the password less API? 

Thanks!

**Comment by nraibaud** [comment]
Finally this is not an issue for the 200 response!

The documentation return nothing because it is only for sending email.
But in our case we would like to have this code back, not from email.
So could i create a improvement to have a new API?
Our use case is to redirect user from an email into some page of our app with auto login passing the code and other parameter in the Route app.

**Comment by voidmain** [comment]
@nraibaud you can edit the email template that is used by FusionAuth for this login workflow. It allows you to customize the content, URL and look-and-feel. Would that cover your needs?

**Comment by nraibaud** [comment]
@voidmain not really, we need to have several access from different emails that auto logged the user.
by the way for now we made a workaround using hash and uuid with guest access.

**Comment by voidmain** [comment]
@nraibaud does that mean you need to have different email templates? Or different `from` email addresses? Or different URLs in the emails?

**Comment by nraibaud** [comment]
@voidmain i am not using the fusion auth email system at all.
We just use a service that send a lot of mails after any actions.
And we just populate these mails with different urls...
So i would like to have a new fusion API to create and get magik link.

**Comment by colundrum** [comment]
Hello @voidmain ,
We use FusionAuth without email functionality because we have complex workflow and we just need to integrate the magic link in our workflow so the best will be to have the possibility to request the magic link through local network to FusionAuth and after to integrate it in our workflow.
We can use FusionAuth email templates because it's impossible to integrate it in actual workflow and this is impossible.
We have a lot of dynamic template and it'll be more usefull to integrate the get of magic link from FusionAuth in our system.
Regards

**Comment by voidmain** [comment]
Thanks for the explanation. We will definitely look into adding that feature to the API so that you can integrate with external providers. I'll open a feature request for that now and if it gets upvoted, we can add it to an upcoming release.

**Comment by voidmain** [comment]
I created #175 to track this feature.
