### ISSUE TITLE
Database upgrade alert and button shown to world

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#397]
### Description 
We had an unintentional upgrade to v1.12. Our AKS pod seems to have been automatically restarted and that process pulled and installed the latest FusionAuth release.

Visitors to our site saw this screen 
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/3413901/70499626-a8b81980-1abd-11ea-8afd-bade59a80dcd.png)

and strangely the db upgrade was triggered by me without any authentication. Presumably multiple people could have pressed the button.

Does this suggest that FusionAuth didn't restart into Maintenance Mode?  If this was to happen again, I'd probably want users to see 'down for maintenance' rather than this alert and upgrade button. And is FusionAuth sane enough at this point to send a notification that it needs attention?

**Comment by voidmain** [comment]
This has come up a few times and we are definitely discussing various ways to lock down maintenance mode. Some ideas include requiring a secure code that is output to the log files to initiate upgrades or to require an admin authenticate before upgrading.

Currently, FusionAuth is designed such that upgrades should not be done automatically because it could put FusionAuth into maintenance mode unexpectedly. Our recommendations is that you only upgrade FusionAuth as part of a strict and scripted process. This process should run the database migration scripts as part of the process. Then, when the nodes come back up, they will connect to the database and not enter maintenance mode.

We use Chef for upgrades and our process looks something like this:

1. Bring all the nodes down
2. Run the database migrations in order from the current database version to the new database version
3. Bring the nodes back up

This process ensures that our clusters don't ever enter maintenance mode during an upgrade and FusionAuth is always accessible once it is running.

**Comment by robotdan** [comment]
Same as  https://github.com/FusionAuth/fusionauth-issues/issues/366

**Comment by davidmw** [comment]
@voidmain Yes I'm not interested in automatically updating FusionAuth so we'll pin the version on restart to something we've tested and are happy with.

But even with that change, a small single node deployment could result in some exposure during scheduled upgrades. I need to front our SPAs with my own maintenance mode option and gracefully handle active sessions.

What if your Maintenance Mode interface appears on a special port?  The interface on 443 could show the 'Sorry, we'll be back soon' message.  

The large screen shot on https://fusionauth.io/docs/v1/tech/installation-guide/fusionauth-app#maintenance-mode had me believing I wasn't actually seeing Maintenance Mode. Maybe the Super User credentials are unavailable if the db is offline but it feels like that account that would be needed to do anything with the database upgrade.

**Comment by voidmain** [comment]
@davidmw - if you perform the database upgrade first, then you won't ever have a compute node go into maintenance mode. This is the safest upgrade method and there are two variations:

**Variation # 1**
1. Bring down all the compute nodes
2. Upgrade the database
3. Upgrade all the compute nodes
4. Bring all the compute nodes back up

**Variation # 2**
1. Upgrade the database
2. Upgrade the compute nodes
3. Restart all the compute nodes

Variation # 1 is the safest way to upgrade since the compute nodes won't ever be out of sync.

**Comment by robotdan** [comment]
Closing this out, I think this was satisfied in version 1.16.0. The `production` runtime mode now means that the Maintenance Mode screen will not be displayed. 

https://fusionauth.io/docs/v1/tech/release-notes#version-1-16-0-rc-1
https://fusionauth.io/docs/v1/tech/installation-guide/fusionauth-app#runtime-modes
