### ISSUE TITLE
Using FusionAuth Behind API Gateway such as Kong?

### ISSUE THREAD

**Issue by zbruhnke** [FusionAuth/fusionauth-issues#420]
### Description
Hi Team,

I'm wondering what the official FA recommendation would be around putting FA behind an API Gateway like Kong? https://github.com/Kong/kong

We're using microservices for our backend services and likely to put most of them behind some API gateway, Kong seems to be one of the most popular options for this rather than stringing things together ourselves however some of the calls that will be hitting our FA instance will actually come from some of our backend services.

I have to imagine that putting FA behind an API gateway has come up before but don't see much in the docs about this setup.

Is this something you see happen often? If so is there a recommended set of best practices for this?

**Comment by robotdan** [comment]
There are many using FusionAuth in this manner, we don't currently offer any specific documentation on integrating with API Gateways. 

I would love to have this documentation at some point, however as far as I know most if not all of the options I've seen have a fairly standard integration using a JWT. 

Once you know what the Gateway such as Kong is looking for in the JWT to perform authorization you can use the JWT populate lambda to ensure the JWT has everything you need. 

https://fusionauth.io/docs/v1/tech/lambdas/jwt-populate
https://fusionauth.io/docs/v1/tech/oauth/tokens

Hope that helps!

**Comment by zbruhnke** [comment]
ah nice thanks for that – will check these docs out, would definitely be a nice enhancement to have docs on that in the future

**Comment by soullivaneuh** [comment]
@zbruhnke I'm also looking to integrate FusionAuth beside Kong.

If you have any tips and warning to share during your integration, it would be awesome. I'll try to do same here if necessary. :+1:

**Comment by mostafahussein** [comment]
I would love to see this too. @zbruhnke if you don't mind keep us updated with your progress or if would like to work together on the integration I will be happy to help

**Comment by zbruhnke** [comment]
@soullivaneuh @mostafahussein we're actively working through this now – I will try to write up something when I get time to sit down and finish it up assiming we're happy with how it turns out :)

**Comment by mreschke** [comment]
All of my own APIs are behind Kong using JWT.  So my apps login to FusionAuth using OIDC and get a JWT token, the APP then uses that token to access my API via kong with the JWT plugin which works perfect.  BUT now I want my apps to also access FusionAuth API itself through Kong using the same JWT.  The problem I have is that the built in "FusionAuth" app has much less settings than a custom app, in particular you cannot disable "Require an API Key" in the security tab as there is no security tab.  The API key requirement seems hard coded for the FusionAuth app and I cannot turn it off.  So using just JWT in the Authorization header does not work because its expecting an API key also.  I cannot pass both an API key and a JWT in the Authorization header.  Also my apps are Angular SPA apps, which means I couldn't store an API key in angular securely anyhow.  If I could just disable the API key requirement and use plain JWT like I do the rest of my apps then Angular could simply query FusionAuth /api directly.  How can I solve this?

**Comment by robotdan** [comment]
@mreschke the "Require an API Key" setting is only for the Login API. All other APIs require an API key unless otherwise documented. 

It sounds like what you're asking for is a way to call any / all of the FusionAuth APIs using a JWT instead of an API key? If that is correct, this is not related to the FusionAuth Application configuration. This is a current limitation of the FusionAuth API. 

There are plans to enable all of the APIs to be called using a JWT instead of an API key and then the authorized assigned the user in the JWT will be used for authority to the API.

**Comment by mreschke** [comment]
Yes.  Bottom line is this.  I have an Angular App, call it "Tools".  That Tools app not only needs to call its own API but several of my other internal APIs + FusionAuth /api itself.  Why?  To get user info, app info, membership etc...directly in Angular.  Angular cannot store API keys securely this is why OIDC exists.  So angular uses the Tools apps fusion OICD setup to login and obtain a JWT token, works great.  With that one single JWT I can login to all my own APIs via Kong as normal but I cannot use it to query FusionAuth /api.  In essense, Angular has no way to call FuaionAuth apis directly which is a hindrance.  My current work-around is to write code in my own Tools API called /api/users which proxies on the server-side-code into FusionAuth /api.  FusionAuth API can essentially only be accessed internally on a secured channel where the API key can be stored.  Allowing access to FusionAuth via an OICD obtained JWT would be very helpful for all SPA apps like Angular.

**Comment by robotdan** [comment]
Thanks @mreschke got it, this is a common use case. 

The one API you can call currently with a JWT is the User API which will return the User, User Registrations and User Group Memberships.  https://fusionauth.io/docs/v1/tech/apis/users#retrieve-a-user

**Comment by mreschke** [comment]
Wow @robotdan you are exactly right.  But with one note, you must use `Authorization: JWT yourtokenhere` instead of `Authorization: Bearer yourtokenhere`.  I just by chance found that.   So for reference, Angular logins into my Tools app using the oauth2 OICD setup in FA for that app as normal.  Angular received the JWT from the tools app which I use for all API request into Kong, works great.  I can then take that same JWT to call FusionAuth /api directly as long as I change Bearer to JWT in the authorization header that Angular sends.  I am really glad to know Angular can at least query /api/users/xyz as that is one of the main ones that any Angular app would need to query directly.  One down side though is my Angular app needs to know the users registration APP NAMES, but the /api/users/xyz registration{} only has all the app GUIDs and since I cannot query /api/registrations/xyz from Angular I cannot display the list of APP NAMES in angular.

**Comment by mreschke** [comment]
For the `app name` missing in /api/users/registration I realize I can use the registration custom .data object to store the name if I need to.  I would think that name is a common need though and perhaps worth consideration to add the app name as part of the main /api/users/registration API to prevent us from further quering the registration endpoint just to get the name.

**Comment by mostafahussein** [comment]
@zbruhnke, Hello, did you completed the integration with kong?

**Comment by mooreds** [comment]
Added a forum post: https://fusionauth.io/community/forum/topic/210/can-you-use-fusionauth-behind-kong/2

**Comment by mooreds** [comment]
Closing this, since it is better suited to the forum.
