### ISSUE TITLE
Feature: Support runtime without Elasticsearch

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#427]
### Problem
For very small installs, development purposes, or embedded use cases when user counts are relatively small such as < 1000, Elasticsearch is not really necessary and may just add complexity. 

### Solution
Provide a reduce function search capability using straight db queries. 

### Alternatives/workarounds
N/A

### Additional context
N/A

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by a1730** [comment]
Elasticsearch is a hog. It got so bad that we are thinking of mocking out the calls.

**Comment by robotdan** [comment]
Can you provide some additional details @a1730 about your environment ?

**Comment by a1730** [comment]
Sorry, I don't understand your request.
We have a "legacy" application that leverages LDAP for authentication and authorization.
We run Elasticsearch because FA requires it. We do our AAA reporting from LDAP
We have found a way in our POC to make FA work. We have more details [here](https://github.com/FusionAuth/fusionauth-issues/issues/219#issuecomment-586795309).
IHTH

**Comment by robotdan** [comment]
@a1730 

> Sorry, I don't understand your request.

I was referring to the following comment:

> Elasticsearch is a hog. It got so bad that we are thinking of mocking out the calls.

This is a general comment about Elasticsearch, and is not helpful for us to justify allocating development resources to complete this feature.  😃

What makes it a hog in your specific use case? Is it using too much memory, or do you just not like having the dependency when you do not have enough users to justify the need for this high performance search option? 

Thanks!

**Comment by a1730** [comment]
> > Elasticsearch is a hog. It got so bad that we are thinking of mocking out the calls.
> 
> This is a general comment about Elasticsearch, and is not helpful for us to justify allocating development resources to complete this feature. 😃
> 
> What makes it a hog in your specific use case? Is it using too much memory, or do you just not like having the dependency when you do not have enough users to justify the need for this high performance search option?
> 
Unfortunately, both the hard dependency on Elasticsearch and memory use are technical debts for our use case. We currently get our AAA reports from LDAP so the 2GB (x2 for HA) memory requirement is a waste for us. These are two VMs that we would love to shut down on GCE. We would rather allocate that memory to LDAP. LDAP with LMDB was allocated 128MB (x2 for HA) currently and it flies even with the amount of writes that we are perfoming. The performance is expected to improve when the POC/migration is complete because of reduced write workload.

The hard dependency on Elasticsearch is also a problem for us. FA runs an old version of Elasticsearch and has a  different release cadence from Elastic. Needless to say that this makes us nervous. We already voted for FA to support V7 of [Elasticsearch ](https://github.com/FusionAuth/fusionauth-issues/issues/199#issue-460841005). We currently don't use search in FA specifically because we have some delegated admin (password change/reset) and self service flow that we do not have enough experience executing in FA - put those under lack-of-knowledge with FA folder. 

However, FusionAuth is currently worth the two inexpensive VMs but we would love to get rid of them if possible. FWIW ease of implementing multi-tenancy is the FA killer feature for us.

IHTH.

**Comment by jerryhopper** [comment]
My 2 cts:    i tried FusionAuth on a Arm64 based platform ( i know, its not supported )  and i found out that fusionauth can run on a Arm64 SBC equipped with 1GB.   the FA provided ElasticSearch however - doesnt run (yet) on my test machine.   When using a External ES server,  i got FusionAuth running.

Obviously, without the need of ES, -as stated in this issue- FA would run (almost) out of the box on a Arm64 platform, which is quite cool.

Although im confident i can make the ES working in the described setup,  i think its quite a neat feature to have a option to exclude ES in a minimal FA setup.

interested in my sbc project? : [FusionAuth on a SBC -> its possible! ](https://twitter.com/jerry_hopper/status/1229184992607186946)

**Comment by atresnjo** [comment]
I have played around with FusionAuth and it's great! Thanks for the great work. Removing ElasticSearch would be amazing. There're many smaller projects I would like to use FusionAuth for, but spinning up ElasticSearch just for the auth is a no-go for those projects.
