### ISSUE TITLE
Google SSO fails silently in Safari private browser

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#428]
### Description 
Using Chrome, Chrome Incognito, and Safari allows successful login to our apps using Google SSO option. The Google popover appears, authentication occurs, the popover is dismissed, and the FusionAuth login screen displays a busy indicator until the app callback is loaded in the browser.

With Safari in Private mode, the Google popover is dismissed and then nothing else happens. No console messages, no busy indicator, no return to our app.

I can send demo video link privately if needed.

**Comment by eirikur-grid** [comment]
The use of a popup for Google authentication is undesirable because
a) it might be blocked
b) it can degrade the sign-in experience on mobile devices

I've been evaluating different authentication services and all those that I've tested so far use the 'redirect' UX mode for Google authentication. I'd propose to switch to 'redirect' mode or make it configurable which mode is used.

**Comment by robotdan** [comment]
We could add this as an option in the configuration, you can also configure Google as an OpenID Connect Provider I believe - and use our OpenID Connect IdP configuration to achieve this result as well.

**Comment by eirikur-grid** [comment]
Thanks, I'll try the OpenID Connect Provider approach.

**Comment by davidmw** [comment]
Thanks, this work well with these params:

Issuer: https://accounts.google.com
Scope:email profile openid
Button Image to: /images/identityProviders/google.svg

**Comment by andrewpai** [comment]
Closing this issue as it is no longer applicable with current versions of FusionAuth, Google SSO, and Safari.
