### ISSUE TITLE
Prevent registration with an application

### ISSUE THREAD

**Issue by SeanStayn** [FusionAuth/fusionauth-issues#431]
If a FusionAuth user logs in via OpenId Connect to an application they are not registered with, the application still allows access.

The UserState parameter indicates that the user is not registered with the application, but the login is still successful. 

Due to the fact that the UserState parameter is not provided in the OpenId Conncept, third-party providers do not take this parameter into account.
As a result, it is not possible for us to prevent a FusionAuth user from registering with an application.

How can this problem be solved?

Many greetings
Sean

**Comment by robotdan** [comment]
If you do not configure the OpenID Connect IdP to "Create registration", FusionAuth will not register the user for the application. 

When the user is not registered, but successfully authenticates with the external OpenID Connect provider, the `UserState` will be added to the redirect as you point out indicate the user has been authenticated but not registered. 

The core of this issue comes down to how you identify a user as authorized to your application. FusionAuth has not registered the user, so if you do not verify with FusionAuth the state of the user, then you may have a problem. 

The token (JWT) that is returned for this user in the scenario you describe will not contain the `applicationId` or `roles` claims because the user is not registered or authorized to the application in question.  ( https://fusionauth.io/docs/v1/tech/oauth/tokens )

**Comment by robotdan** [comment]
I opened a feature request that I believe would satisfy this request, please comment on the linked issue if you have additional ideas that you'd like to see. 
https://github.com/FusionAuth/fusionauth-issues/issues/439
