### ISSUE TITLE
Feature: Allow Elasticsearch index name to be user configured

### ISSUE THREAD

**Issue by hamelsveld** [FusionAuth/fusionauth-issues#451]
### Description
The default index name in Elasticsearch is `fusionauth_user` and it would be helpful for this value to be end user configurable via the `fusionauth.properties` configuration file or via an environment variable.

**Comment by ictcorebiz** [comment]
I have the same issue, it is easy to use a different database in postgress, but it seems you can't configure a different index.

**Comment by robotdan** [comment]
The index name is `fusionauth_user` and this is not currently user modifiable. 

We could expose this via a configuration in the `fusionauth.properties` file and allow it also to be set via environment variable. 

I can convert this issue to a feature request.

**Comment by ictcorebiz** [comment]
That would be great!! Especially in smaller installations, it is no problem sharing an ElasticSearch cluster for multiple fusionAuth instances.

**Comment by ictcorebiz** [comment]
Do you have a roadmap so that I could see when you plan to implement features?

**Comment by robotdan** [comment]
This project plan doesn't go out real far, but it should show you what is coming. 

https://github.com/FusionAuth/fusionauth-issues/projects/2

Otherwise, vote on issues, the higher voted items get prioritized.

If you have a business need for anything we have paid offerings which allow us to prioritize resources. 

Thanks!

**Comment by robotdan** [comment]
Delivered under https://github.com/FusionAuth/fusionauth-issues/issues/631
