### ISSUE TITLE
Default email templates missing after kickstart

### ISSUE THREAD

**Issue by trollr** [FusionAuth/fusionauth-issues#467]
Default email templates missing after kickstarting fusionAuth

### Description 

I created a default admin user with kickstart.json. After kickstarting all default email templates are missing. 

### Steps to reproduce
Kickstart fusionAuth with:

```
{
  "variables": {
    "defaultTenantId": "d7d09513-a3f5-401c-9685-34ab6c552453",
    "adminEmail": "admin@fusion.local",
    "adminPassword": "awesomeSecretPassword"
  },
  "apiKeys": [
    {
      "key": "bf69482b-4733-4470-a592-f1bfce7af580",
      "description": "Core API Key"
    }
  ],
  "requests": [
    {
      "method": "POST",
      "url": "/api/user/registration",
      "body": {
        "user": {
          "email": "#{adminEmail}",
          "password": "#{adminPassword}"
        },
        "registration": {
          "applicationId": "#{FUSIONAUTH_APPLICATION_ID}",
          "roles": [
            "admin"
          ]
        }
      }
    }
  ]
}
```

Goto `System->Email Templates`. 

### Expected behavior
Admin user and all default email templates will be created.

**Comment by robotdan** [comment]
When using the kickstart everything is started from scratch, including email templates. 

If you view the `kickstart-development.json` example - this is the one we use in development to pre-populate all of the templates. This should provide a good starting place for email templates. 
https://github.com/FusionAuth/fusionauth-kickstart-examples/blob/master/fusionauth/kickstart-development.json

The reason we decided to go this way is that our default templates are very basic and the end user needs to update the URL in the template before using them. So we decided to just let them be custom created from the beginning so that you do not have to modify them during a kickstart to get them how you like.
