### ISSUE TITLE
FusionAuth UI Dashboard Logins chart not shown in local timezone

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#476]
### Description 
Local time is 1:41 PM. The Dashboard 'Recent Logins' table is showing activity in my local timezone.  

The Logins By Hour chart is attached. It seems to be stuck at least 3 hours behind. Refresh and login/logout doesn't update it and it is missing significant activity in the last hour that is logged correctly in Recent Logins and in System Login Records.

<img width="511" alt="Screen Shot 2020-02-11 at 1 27 16 pm" src="https://user-images.githubusercontent.com/3413901/74289995-a39d6380-4cd4-11ea-8b7a-8f3e3fd09325.png">

Fusion 1.14

**Comment by davidmw** [comment]
The chart did update, showing the traffic increase about an hour after the fact. It just isn't adjusted for the local timezone. 

<img width="496" alt="Screen Shot 2020-02-11 at 2 34 08 pm" src="https://user-images.githubusercontent.com/3413901/74292347-de56ca00-4cdb-11ea-8885-9668a492e389.png">

**Comment by robotdan** [comment]
Those reports are not real time, that part is working as designed. The report data is calculated and rolled up through a scheduled service. 

 The report timezone can be adjusted in the system settings.

Settings > System > Reports.

**Comment by davidmw** [comment]
Ok - so logs are local TZ (HST) while reports are using reportTimezone (Sydney). Little odd but no big deal.

**Comment by robotdan** [comment]
The reports are all calculated using the timezone set in the system configuration because in order to do rollup calculations we have to identify when the start and end of each day occurs. 

All of the metrics we store are in UTC - and once we calculate the totals for a day we do not go back and calculate it again. We continually roll up the data from days, to months, etc. 

For this reason we do need to know what time zone to use for reporting, which can be different than the timezone you set on your user profile, or the one that is used in the admin UI to display other date and times. 

Hope that helps.
