### ISSUE TITLE
Support for MariaDB

### ISSUE THREAD

**Issue by Garogat** [FusionAuth/fusionauth-issues#48]
### Problem
MariaDB is not having the function RANDOM_BYTES. https://mariadb.com/kb/en/library/function-differences-between-mariadb-102-and-mysql-57/

```
-- Internal API key, replace new lines with empty
INSERT INTO authentication_keys(id, permissions, meta_data, tenants_id)
   VALUES (concat('__internal_', replace(to_base64(random_bytes(64)), '\n', '')),
           '{"endpoints": {"/api/cache/reload": ["POST"]}}',
           '{"attributes": {"internalCacheReloader": "true"}}',
           NULL);
```

### Solution
```
-- Internal API key, replace new lines with empty
INSERT INTO authentication_keys(id, permissions, meta_data, tenants_id)
   VALUES (concat('__internal_', replace(SUBSTR(CONCAT(MD5(RAND()),MD5(RAND())),1,64), '\n', '')),
           '{"endpoints": {"/api/cache/reload": ["POST"]}}',
           '{"attributes": {"internalCacheReloader": "true"}}',
           NULL);
```

**Comment by robotdan** [comment]
Hi @Garogat thanks for bringing this to our attention. 

Officially we don't support MariaDB. 
https://fusionauth.io/docs/v1/tech/installation-guide/system-requirements

However, we do try to make our SQL as compatible as possible. Thank you so much for offering a solution. I'll review your solution and if it looks to be compatible I'll commit your change.

**Comment by robotdan** [comment]
Hi @Garogat I am testing out your suggested fix. Everything looks good so far. 

Have you been able to work around this issue for now and run on MariaDB?

**Comment by Garogat** [comment]
I am missing the complete .sql file, so I couldn't test any further.

**Comment by robotdan** [comment]
Hi @Garogat thanks for the update. 

So I will try to get this fixed shortly in a patch release. 

One option if you'd like to continue before this patch is released - 

1. Download the db zip 
  https://fusionauth.io/downloads `fusionauth-database-schema-<version>.zip`
2. Follow the advanced schema install
  https://fusionauth.io/docs/v1/tech/installation-guide/fusionauth-app#advanced-installation
3. See the MySQL section, the last step will be to create the schema. 
  `mysql --default-character-set=utf8mb4 -u<ordinary_user> -p<ordinary_password> fusionauth < mysql.sql`

So, depending on how far you got, part of the schema may exist already. So you may want to drop the database, `DROP DATABASE fusionauth` and then repeat the MySQL steps to create the db, grant the `fusionauth` user rights, and then create the schema. 

The `mysql.sql` file can be found in the db zip you downloaded, you can patch any usage of `randon_bytes` found in that file with your solution. 

Otherwise, I'll update this issue once a new version is released with this fix.

**Comment by robotdan** [comment]
Great, I'll add that info to the documentation and add some additional links.
