### ISSUE TITLE
Users without registrations can access application

### ISSUE THREAD

**Issue by sedough** [FusionAuth/fusionauth-issues#504]
### Description 
I created a new user, but forgot to add an application registration for him.   He is still able to login to my application, and no record of this exists in the "Login Records" page.

### Steps to reproduce
1. Create a new local user without registrations.
2. Login as that user in an application.

### Expected behavior
The login should should fail because the user has no application registration and self-service registration isn't enabled.   In any case, there should be a record of that login.

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome

**Comment by sedough** [comment]
I did some more digging, and this seems to be related to the "Require authentication" setting in the Application OAuth settings.   I had this disabled because my application is a single-page application and there is no secret.

So this brings up several issues:
- Disabling "Require authentication" allows unregistered users access to the application
- Enabling "Require authentication" doesn't actually require clients to provide a secret
- It's possible a user to authenticate and access an application without any log record (!?!)

It also seems a little odd to me that when a user logs in against a certain application, and there's no registration, FusionAuth still redirects back to the application.    I would expect FusionAuth to show a "not authorized to access this application" message.

**Comment by robotdan** [comment]
This is working as designed. There is an open feature request to allow (through configuration) to restrict login when the user is not registered. 

See https://github.com/FusionAuth/fusionauth-issues/issues/439 and feel free to comment there. 

The login workflow consists of two parts, authentication, and authorization. The user authenticates successfully because their credentials are correct. In this case, the user is not authorized to the requested resource (`applicationId`) - and so the will contain a `userState` indicating the user is not authorized, and the JWT provided in response will not have the `applicationId` or `roles` of the requested resources. 

See  https://fusionauth.io/docs/v1/tech/oauth/tokens for more info on what is returned on a login response.
