### ISSUE TITLE
Add Spring 5 Security Example

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#506]
### Problem
Add Spring 5 Security Example

Update this repo or add a Spring5 if it is way different? 
https://github.com/FusionAuth/fusionauth-spring-security

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by ccaspanello** [comment]
This is great stuff!  I am curious how this would work with the frontend libraries like `@fusionauth/react-sdk`

I am currently trying to convert the NodeJS code in this example https://github.com/FusionAuth/fusionauth-example-react-sdk into Spring Boot.  While I am making some progress; I feel like it's not very "Spring Security" like.  Would you be able to advise on a good direction to take?

**Comment by mooreds** [comment]
@ccaspanello we have a more modern spring example here: https://fusionauth.io/docs/quickstarts/quickstart-springboot-web

The react SDK stores access tokens in cookies. This article appears to show how to pull a token out of a cookie: https://www.sohamkamani.com/java/spring-jwt-authentication/#spring-security-configuration

It's not precisely what we'd recommend because it uses HMAC instead of an asymmetric algo, but should give you a start.

Also, probably best to post in the forum for this kind of question: https://fusionauth.io/community/forum/

**Comment by mooreds** [comment]
Closing this because we have a new spring example here: https://fusionauth.io/docs/quickstarts/quickstart-springboot-web
