### ISSUE TITLE
Feature: NodeBB OIDC / OAuth2 Plugin

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#523]
### Problem
All of the OIDC plugins for NodeBB suck or don't work, and it makes me sad. 

### Solution
Build a better one that is supported by the awesome devs at FusionAuth. 

- [x] Plugin that exposes client_id, client_secret, discovery endpoint (or optionally authorize, token and userinfo), client authentication method (client_secret_basic, or client_secret_post), scopes?
- [x] Connects to FusionAuth IdP via OIDC
- [ ] Connects to Keycloak IdP via OIDC
- [x] Connects to Google IdP via OIDC
- [x] Unique claim? Default to `email`

### Alternatives/workarounds
Cry. 

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by tyduptyler13** [comment]
Tasks
====

* [ ] Build a passport authentication module for openidc (there is an openid-oauth20 module but I need to verify it is compliant with openid connect or modify it to be compliant, it is also well written so is probably a good base) (https://github.com/kertof/passport-openid-oauth20)
* [ ] Build a settings page in the plugin and test that all of the settings come back (See https://github.com/Alexkin2609/nodebb-plugin-sso-oidc as a reference)
* [ ] Build a mechanism to both skip and stay on the login page. The skip is a redirect to the oidc login and the stay is a parameter or secondary url that allows the user to use local authentication instead.
* [ ] Test the authentication module end to end
  * [ ] Fusionauth
  * [ ] Google
* [ ] Add similar function to cleanspeaks inherit roles from the roles claim. This would allow the oidc provider to dictate authorization instead of the application.
  * Does this mean the admin interface of nodebb can't promote users and only fusionauth can or should we allow changes in nodebb from an admin call our apis?

**Comment by tyduptyler13** [comment]
Everything is done with the exception of testing with other providers. (But I assume they work as long as their userinfo is compliant since that is largely the only feature I had to implement)

**Comment by robotdan** [comment]
@tyduptyler13 I think I have some Google creds so we can test their OIDC endpoints.
