### ISSUE TITLE
HMAC signed id_token is not able to be validated with client_secret per OIDC 3.1.3.7.

### ISSUE THREAD

**Issue by Garogat** [FusionAuth/fusionauth-issues#57]
### Description
Which JWT secret is used for signing the id_token response from /oauth2/token? As I know OpenID it should be the client_secret, but that fails for me.
https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

**Comment by robotdan** [comment]
Hi @Garogat - I think what you're after are the claims in the `id_token` and to verify the token signature is valid and not expired. 

The easiest way to validate the token and obtain claims in JSON will be to send the `access_token` returned from the `/oauth2/token` endpoint to the `/oauth2/userinfo` endpoint. https://fusionauth.io/docs/v1/tech/oauth/endpoints#userinfo

This will validate the token for you and return you a JSON response with the claims contained in the token as well as a few additional ones. 

You may also choose to validate the `id_token` externally from FusionAuth. To do this, you will need the secret that was used to sign the token if using HMAC, or the public key that corresponds to the private key that was used to sign the token if using RSA. 

See the `Signing algorithm` field in this tutorial to see where this signing algorithm is configured for your application. https://fusionauth.io/docs/v1/tech/tutorials/json-web-tokens  If you review your application configuration you can see what method your are using, and you will be able to view the public key if using RSA or the HMAC secret if using HMAC.

If you do wish to validate these externally, it is preferred that you use RSA so that you only need to share a public key with anyone that needs to verify the JWT signature. If you use HMAC, while this is a much faster hash, the secret is used to sign and verify the signature, so you'll need to share with value outside of FusionAuth. 

When using RSA key pairs, you can anonymously retrieve any public keys using the JWT Public Key API. https://fusionauth.io/docs/v1/tech/apis/jwt#retrieve-public-keys

We will also be supporting the  JSON Web Key Set (JWKS) endpoint shortly, which is a more generic way to discover public keys that can be used to validate a JWT signature. 

Let me know if that answers your question. 
Thanks!

**Comment by Garogat** [comment]
Hi @robotdan. Correctly, my library is trying to verify the correctness of the `id_token`s. I am currently using HMAC SHA256 for this.

> The easiest way to validate the token and obtain claims in JSON will be to send the access_token returned from the /oauth2/token endpoint to the /oauth2/userinfo endpoint. https://fusionauth.io/docs/v1/tech/oauth/endpoints#userinfo

That's what I am doing if I need to retest an `accesstoken` in a later request, but after getting my `accesstoken` and `id_token` from `/oauth/token` my client (openid-certified) tries to verify it by the `client_secret` as described in the openid specs.

> If the JWT alg Header Parameter uses a MAC based algorithm such as HS256, HS384, or HS512, the octets of the UTF-8 representation of the client_secret corresponding to the client_id contained in the aud (audience) Claim are used as the key to validate the signature.

As I understand it, you are signing the `id_tokens` by using your self generated HMAC secret, but as you pointed out in your docs, that needs a way to share this secret again and if only a system-wide secret is used, it is consequently known by any application. In my opinion using the `client_secret` is a safer way and you won't need to provide another key.

> The downside of using HMAC signing is that each application that has access to the HMAC secret. Anyone with the secret can both produce a JWT with a valid signature and verify the signature which makes it difficult to know for certain who issued and signed the JWT.
https://fusionauth.io/docs/v1/tech/tutorials/json-web-tokens

(BTW: there seems to be a small mix-up with that sentences ;) )

> We will also be supporting the JSON Web Key Set (JWKS) endpoint shortly, which is a more generic way to discover public keys that can be used to validate a JWT signature.

Nice. Will it support the openid discovery with `jwks_uri` aswell?

Thank you for your effort explaining everything to me.

**Comment by robotdan** [comment]
Hi @Garogat 

*Re: JWKS*
> Nice. Will it support the openid discovery with jwks_uri as well?

Yes, the URL will be `/.well-known/jwks.json` and it will also be returned in the OpenID Configuration response when accessing `/.well-known/openid-configuration` in the `jwks_uri` property.

I do not believe the JWKS specification supports HMAC keys, so in this scenario you'll need to use RSA or Elliptic algorithms. 

&nbsp;

*Regarding the `client_secret` and `id_token` validation.*

Thank you for the clarification, it looks like you are correct. We are not currently using the `client_secret` to sign the `id_token` when you are using `HS256`, `HS384` or `HS512` signing algorithm.

https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

> 3.1.3.7. ID Token Validation
>
> 8. If the JWT `alg` Header Parameter uses a MAC based algorithm such as `HS256`, `HS384`, or `HS512`, the octets of the UTF-8 representation of the `client_secret` corresponding to the `client_id` contained in the `aud` (audience) Claim are used as the key to validate the signature. For MAC based algorithms, the behavior is unspecified if the `aud` is multi-valued or if an `azp` value is present that is different than the `aud` value.

To work around this issue, please copy the `client_secret` found in your application configuration under the `OAuth` tab and save it as your HMC secret in the `JWT` tab. If the `Enable` toggle is not yet enabled, do so, and ensure the `Signing algorithm` is set to `HMAC using SHA-256` and paste in the `client_secret` into the `HMAC secret` field. I believe doing this step will allow you to validate the `id_token` as you expect. 

We'll need to see how we can fix this w/out breaking our current API, but we should be able to correct this behavior shortly. 

Thank you for bringing this to our attention.

**Comment by robotdan** [comment]
The JWKS endpoint is available in version [1.4.0](https://fusionauth.io/docs/v1/tech/release-notes/#version-1-4-0). The `client_secret` fix should be coming soon.

**Comment by robotdan** [comment]
This is now fixed in version `1.5.0`. 
https://fusionauth.io/docs/v1/tech/release-notes/

Thanks for taking the time to report this issue @Garogat .
