### ISSUE TITLE
Mysql driver always having to be downloaded

### ISSUE THREAD

**Issue by nulian** [FusionAuth/fusionauth-issues#597]
The mysql driver is being downloaded from http://savant.inversoft.org/com/mysql/mysql-connector-java/8.0.12/mysql-connector-java-8.0.12.jar.

That location seems unstable at the moment so sometimes it fails to download and breaks our fusionauth kubernetes pod.

Would be nice if that file could be compiled inside the container. The jar file isn't too large and for an on premise customer of ours it already seems to work if you download the file inside the container in `/usr/local/fusionauth/fusionauth-app/web/WEB-INF/lib` then it will just fail that download. After that I just save the fusionauth container as an image and it will just work without downloading it though download seems hardcoded.

**Comment by robotdan** [comment]
Hi @nulian we had a DNS issue yesterday that was causing this error. 

The reason for downloading this jar is runtime is due to the Oracle license terms of this connector. We are reviewing our options currently to see if we can safely bundle this jar instead of downloading it at runtime to alleviate the possibility of this type fo error in the future. 

Thanks for letting us know.

**Comment by robotdan** [comment]
We have fixed the DNS issue, and have decided to leave this as is for now. The MySQL connector jar is licensed under GPL which means we can't bundle it with commercial software. 

We have moved the dep to a Google storage URL which should make it more reliable. You have the option of remastering the Docker image with this on the filesystem if you want to remove the possibility of this being downloaded at runtime.
