### ISSUE TITLE
Office 365 as SMTP (again)

### ISSUE THREAD

**Issue by lamuertepeluda** [FusionAuth/fusionauth-issues#601]
## Cannot send email using Office 365

Maybe this is not a bug and FusionAuth is working as intended, but then it can be an issue in the documentation

### Description 
I am trying to add a Office 365 account for SMTP, which my company uses. And I keep getting this error in the event log.

`535 5.7.3 Authentication unsuccessful [AM0PR10CA0036.EURPRD10.PROD.OUTLOOK.COM]`

Can be related to #220 , though, using the proposed solution, nothing seems to change.

### Steps to reproduce
- do anything related to sending email

### Expected behavior
The mail is sent

### Screenshots

![image](https://user-images.githubusercontent.com/2249342/81065948-a6c37c80-8edc-11ea-868b-61182413ce3b.png)

This is what I get from the event log. Sadly the container logs do not offer much more information (it would be good to have a verbose log level with headers, requests and so on).

My Tenant settings
![image](https://user-images.githubusercontent.com/2249342/81065791-6f54d000-8edc-11ea-9179-1d8e0d394147.png)

**I made sure the sender name and email match those of the account, in each template.**

#### Advanced Settings

Can the following settings help? How specifically? Should we set some headers? There is no mention of this in the documentation.

![image](https://user-images.githubusercontent.com/2249342/81065531-f2c1f180-8edb-11ea-9742-6f4127dbfc55.png)

Thanks

### Platform

 - FusionAuth 1.15.8 on docker containers

**Comment by mooreds** [comment]
Hiya,

It looks like you are using option #1 as outlined here: https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3 "Authenticate your device or application directly with an Office 365 mailbox, and send mail using SMTP AUTH client submission"

If so, can you verify that your account isn't using Microsoft Security Defaults or MFA? And that SMTP Auth is enabled for the mailbox being used? (Links for both are in the above doc.)

Googling showed me a couple of possible other solutions:

This post indicated changing the password can help?
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_dep365/smtpoffice365com-relay-535-573-authentication/9de8d176-1c07-4e66-b14f-148d3bd51bbf

This post indicates you need to enable SPF.
https://wordpress.org/support/topic/incorrect-authentication-data-port-587-smtp-starttls-siteground/#post-10873384

**Comment by andrewboring** [comment]
You need to set the password associated with the SMTP username you are using. 

Select "Change Password", and then enter your *current* Email password in the Password field that appears. Then click Send test email.

The UI on this page is poor.

The correct approach would be a switch/button that said "Use authentication" instead of "Change password", causing both the SMTP username and password fields to display for entry.

**Comment by robotdan** [comment]
Thanks for the feedback @andrewboring. 

To summarize, when you have not yet set a password, the `Change password` control is confusing because you have not set one yet? 

There are a couple of use cases we want to cover I think, let me know if you can think of more. 

1. No credentials, Security is `None`. 
2. No credentials, Security is `SSL`
3. No credentials, Security is `TLS`
4. Username & Password, Security is `None`. 
5. Username & Password, Security is `SSL`
6. Username & Password, Security is `TLS`

The Security configurations instructs us how to build the SMTP connection, `TLS` will add `mail.smtp.starttls.enable=true` `SSL` will add `mail.smtp.ssl.enable=true` and Username & Password will add `mail.smtp.auth=true` with other credential properties. 

So perhaps we should add another control that says "Use authentication" as you mentioned, and that would show and hide the username and password field. Then once you have set a username, we show the `Change password` control as we have it today. The purpose of that control is to allow you to indicate you want to change the password as we do not show the current password on this form. 

All feedback is welcome to improve the UX here.

**Comment by andrewboring** [comment]
Ah, thanks for the reply, @robotdan. I was just about to file a bug report with this information (was about to hit "Submit" when I got a notification of your reply). Looking at the screenshots of @lamuertepeluda 's Authentication errors, I was assuming he's encountering the same thing I was: Authentication errors because no SMTP password is configured, because there is no field displayed for it ("Change password" implies "change _existing_ password", not "set password for the first time").

Testing a bit further on my [new] configuration, it appears the password field disappears after saving it, but a new test email still goes through. This means the screenshot above won't tell us if OP even has a password configured at all! 

Even though this issue is around four months old, I'd rather not hijack it just in case OP's issue was different from mine and needs to follow-up. I'll continue with a new bug report and link back to this one, and address the use cases you describe for the UI.

**Comment by robotdan** [comment]
Yes, please do open an issue if you have a UI / UX concern. I always assume if one developer is confused, there are at least 10 more that just didn't open an issue. So we welcome the feedback. 

We can continue the thread on your new issue.

**Comment by robotdan** [comment]
Can we close this issue out and track the UX issue, or is there a separate issue to resolve here?  
- https://github.com/FusionAuth/fusionauth-issues/issues/884
