### ISSUE TITLE
Feature: Deploy to Heroku

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#62]
### Problem
I want to be able to deploy to Heroku using `heroku create` 

### Solution
Support Heroku. 
https://devcenter.heroku.com/articles/getting-started-with-java

### Alternatives/workarounds
Build it your self. 

### Additional context

Related issues: https://github.com/FusionAuth/fusionauth-issues/issues/1024

### Bounty
This issue qualifies for the FusionAuth bounty program. If you can get FusionAuth up and running in Heroku, document the procedure so we can get it published for the rest of the community. 
https://fusionauth.io/write-for-fusionauth

If you find changes are necessary to FusionAuth to make it run in Heroku properly, please comment here or open an issue. 

If you are interested, please contact us using the link provided above and let us know.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by pankyka** [comment]
@robotdan Hi, can you tell me please, how did you successfully deployed to heroku?

**Comment by robotdan** [comment]
Hi @pankyka we don't currently support Heroku, this issue is opened to track the issue through development. 

It may currently work in Heroku but this is not a configuration we have tested internally.

**Comment by pankyka** [comment]
Thanks, it’s working in heroku. I figured out the port binding with sed command.

**Comment by robotdan** [comment]
Thanks for the update @pankyka 

Would you be interested in submitting a PR or providing a brief overview of any necessary configuration to run FusionAuth in heroku to help the rest of the community? 

Thanks!!

**Comment by pankyka** [comment]
I think I have to make you sad @robotdan Currently the only way to deploy FusionAuth in Heroku is the Dockhero addon. This addon isn't free, several bucks for first stage as well and I don't think this solution is perfectly fits for Paas ecosystem. I wouldn't use such strategy for production.

Some changes needed in FusionAuth to work with Heroku perfectly. The biggest things are to use persistent layers as addons: MySQL or Postgres and Elasticsearch.

1. MySQL and Postgres addons have DATABASE_URL env variable that aren't jdbc connection strings
https://devcenter.heroku.com/articles/connecting-to-relational-databases-on-heroku-with-java#using-the-database_url-in-plain-jdbc

2. Database addons doesn't provided with superuser account but an empty database already done with RW user

3. FusionAuth App and Search may merge into one dockerfile due to network linking between dynos not supported
https://devcenter.heroku.com/articles/container-registry-and-runtime#dockerfile-commands-and-runtime

4. FusionAuth Search app should use Elasticsearch addon as well

5. Heroku have dynamic port binding on dynos. This port number can we reach with PORT env variable and use it for `fusionauth-app.http-port` setting

6. It is possible to allow mapping the environment variables due to addons can have different env variable naming

To support Heroku correctly I think you have to do the steps above. What I only did just changed this PORT variable with sed command and deploy with dockhero.
`RUN sed -i s/9011/$PORT/g /usr/local/fusionauth/config/fusionauth.properties`

**Comment by robotdan** [comment]
Thank you for that great description @pankyka.  This is very helpful.

**Comment by robotdan** [comment]
@mooreds is your work with Heroku helpful here and perhaps sufficient to close out this issue?

**Comment by mooreds** [comment]
We should document this. Here's the issue to do so: https://github.com/FusionAuth/fusionauth-issues/issues/1024

For anyone reading this in the future, issue 1024 has a community supported heroku deploy option.

So I'd say that we could close out this issue, as long as we leave the other one open.

**Comment by robotdan** [comment]
Closing as superseded by #1024
