### ISSUE TITLE
Add Webhook for Group Membership Changes

### ISSUE THREAD

**Issue by JLyne** [FusionAuth/fusionauth-issues#633]
### Description
I am attempting to listen for when a user's groups change so I can update things elsewhere, however there doesn't seem to be a webhook that fires when a user's groups are changed.

I have tried both user.update, and user.registration.update, however the former doesn't fire at all for group changes, and the latter only fires when I manually update the registration, but not when the registration's roles are changed by a group change.

Is there another webhook I should be using, or is it not possible to listen for group changes?

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1803

**Comment by mooreds** [comment]
It doesn't appear that there are any events available for taking action on group changes. So at this point it is not possible to listen for group changes. I'm sure you've seen this, but this is the full list of events available: https://fusionauth.io/docs/v1/tech/events-webhooks/events

The only workaround I can think of right now is polling for group changes using the user search API. 

I'll mark this as a feature to be considered for future development. If you could expand on your use case (I think I understand it but don't want to make assumptions) that would be helpful to us.

**Comment by JLyne** [comment]
Sorry for the delayed reply.
My intention was to use the webhook to update the permissions of users on the sites behind fusionauth, so that the group changes take effect immediately rather than needing the user to logout and back in.

**Comment by ric-sapasap** [comment]
I also need this feature for integrating FusionAuth with other services that require authentication that I don't have full control over. 

Any updates?

**Comment by mooreds** [comment]
@ric-sapasap Thanks for checking in. I suggest voting on this issue since when we are considering community feedback, we sort by number of upvotes on the issues in this repo. You can vote by using the plus 1 emoji, like I just did.

Here's our general roadmap guidance:

https://fusionauth.io/docs/v1/tech/core-concepts/roadmap/

We do not have this particular feature on the current release plan nor can I commit to a timeline. If you need this feature and have budget, feel free to reach out to the sales team and discuss what a professional services agreement would entail: https://fusionauth.io/contact/

**Comment by rabshire** [comment]
I also need this but I'm using it a little differently to work around a problem.  I want to add a data field with the group_name to the group.membership table to pass the group names instead of just the ids to the SAML populate request for our external group permissions.  Please make sure any updates to the group.memberships do not re-trigger the add or remove event. I don't think an update would but just in case. Thanks!

**Comment by robotdan** [comment]
@rabshire 

> Please make sure any updates to the group.memberships do not re-trigger the add or remove event. I don't think an update would but just in case. Thanks!

I don't know if I understand this, can you clarify? Thanks!
