### ISSUE TITLE
Bulk deletion of users by metadata or wildcard

### ISSUE THREAD

**Issue by jakobrosenberg** [FusionAuth/fusionauth-issues#64]
### Problem
In E2E tests it would be nice to have a test application without users. (Duplicate errors, DB seeding etc)

### Solution
Add a an API feature that allows users to be deleted by metadata, wildcard or application. IE. 
``DELETE /api/user/bulk?group="testusers"``
``DELETE /api/user/bulk?match=testuser-``
``DELETE /api/user/bulk?applicationId={testappid}``
``PUT/api/application/{applicationId}?flushusers=true``

### Alternatives/workarounds
Search for all users in an application and delete them by ID. (is it possible?)

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by voidmain** [comment]
Hi @jakobrosenberg. I believe this might be a great use case for the FusionAuth tenant feature. What your tests would do is to create a tenant and then create the applications and users inside that tenant. When you are done testing, you can delete the tenant and it should delete all the users and applications inside it.

Here's the API doc for the tenant DELETE:

https://fusionauth.io/docs/v1/tech/apis/tenants#delete-a-tenant

In order to associate applications and users with a tenant, you need to either create an API key for that tenant or pass the tenant id in with the request as a header. Here's a tutorial that covers using tenants in more detail:

https://fusionauth.io/docs/v1/tech/tutorials/tenants

**Comment by jakobrosenberg** [comment]
Great! I'll definitely have a look at that.

Thank you very much!
