### ISSUE TITLE
Cannot start FusionAuth on Ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by s-vlade** [FusionAuth/fusionauth-issues#645]
### Description 
When trying to start the server (startup.sh) the following error occurs
**./catalina.sh: 38: <-installation path->/fusionauth/fusionauth-app/apache-tomcat/bin/setenv.sh: Syntax error: "(" unexpected**

### Steps to reproduce
1. Go to https://fusionauth.io/download and download the latest version for Linux 
2. After successful install go to **fusionauth/bin** and run the **startup.sh**
3. Server is not running and the logs in **fusionauth/logs/fusionauth-app.log** says **"./catalina.sh: 38: <-installation path->/fusionauth/fusionauth-app/apache-tomcat/bin/setenv.sh: Syntax error: "(" unexpected"**

### Expected behavior
The server should be up and running

### Platform
 - OS: Ubuntu 18.04.4 LTS and Ubuntu 20.04

**Comment by yrammos** [comment]
I faced the same issue yesterday. This is because the `catalina` script has an incorrect "shebang" and incorrectly runs within the obsolete `dash` shell. Just change the first script line to:

`!/usr/bin/env bash`

**Comment by robotdan** [comment]
Thanks for the report, it looks like we may have a non POSIX compliant function definition. 

Ubuntu sym-links `dash` to `/bin/sh` so `catalina.sh` is running under `dash` and a POSIX implementation of `/bin/sh. 

Your workaround is valid, if you want to try a "fix" - you can modify line `38` in `setenv.sh` from `function downloadJava() {` to `downloadJava() {`.  My assumption is that this line of code is causing the error since `function` is not a POSIX recognized keyword for a function.
