### ISSUE TITLE
Roles per group

### ISSUE THREAD

**Issue by landorg** [FusionAuth/fusionauth-issues#656]
### Problem
In our app we have multiple groups (Organization) each user can be part of. In each of the groups a user can have a "group-role" in addition to the application role. 
Is there already a way to model this?

### Solution
Add additional roles to the groups.

**Comment by mooreds** [comment]
You can add roles to groups as documented here: https://fusionauth.io/docs/v1/tech/core-concepts/groups

> The selected application roles will be assumed by members of this Group.

Does that not accomplish what you're trying to do?

**Comment by rolandg** [comment]
I can add roles from application level to a group right? 
Not sure if understood everything right though.

What I'd like to have is are roles per group independent of the application level role. 
Means it should be possible to for example be admin in one group but be user in another group. And at the same time the user also has a "global" role on the application level.

**Comment by mooreds** [comment]
Hmmm. I'm a bit confused on what you're trying to accomplish. Roles are always associated with an application, they don't exist outside of that.

Groups, on the other hand, do exist outside of applications. 

If a group has a role for an application and also has a member who is also associated with application (is registered in that application) the user will get those roles.

Here's an example.

Application A has two roles
* admin
* member

Application B has one role
* superadmin

User 1 has a registration in Application A

User 2 has a registration in Application B

There's a group 'Admin Group' which has the application roles of 'admin' for Application A and 'superadmin' for application B. 

If you add User 1 to the 'Admin group' they will receive the role 'admin' in Application A, but not 'superadmin' (because they aren't registered in Application B).

Does that help? If not, can you please outline what you're trying to do in with an example?

**Comment by mooreds** [comment]
I added some additional documentation to the 'groups' page which will hopefully make group usage a bit clearer: https://fusionauth.io/docs/v1/tech/core-concepts/groups

**Comment by rolandg** [comment]
Thank you for the update. Then I got the application concept wrong. Thought a user has to login to each application separately.

**Comment by mooreds** [comment]
This may be a useful forum post to read: https://fusionauth.io/community/forum/topic/5/can-you-limit-a-user-s-login-authentication-access-to-applications-within-a-single-tenant/5

In it, Daniel talks about the difference between authorization and authentication in FA.
