### ISSUE TITLE
Is there a way to populate the username in any of the SAML lambdas?

### ISSUE THREAD

**Issue by patrickvalle** [FusionAuth/fusionauth-issues#676]
### Description
I have a business case for populating the `user.username` field based off of fields returned on the SAML response. I've used the SAML v2 Reconcile lambda to populate other `user` fields with success, but I've been unable to map any value to the `user.username` field.

If this is functioning as intended, is there another way to populate the `username` via a lambda?

**Comment by robotdan** [comment]
You cannot set the `username` using a reconcile lambda, we ignore it if you attempt to set it.

The reason for this is that a `username` is not globally unique. I could set a username called `robotdan`, and I could log in using this `username` in FusionAuth. Then if we connect FusionAuth to SAML or some other IdP where you have a username of `robotdan` we are unable to understand if this is the same user that we already know by `robotdan` or if this is a new user that happens to have the same username. 

In order to support this capability we'd have to provide a way to define a namespace ahead of time to declare where a username is unique. For example, if within Twitter, a username / handle is unique, then if we were to allow you to define a namespace called `Twitter` we could then allow you to set a username as an identity of type Twitter. In this scenario we could assume it is unique because of the declared namespace.  This scenario may b covered in the future by this feature: https://github.com/FusionAuth/fusionauth-issues/issues/1

If you only require this data for reference, and not to allow login to FusionAuth, you could set the value in `registration.username`. This value cannot be used to login, but you can use it in your own application however you like.

**Comment by patrickvalle** [comment]
@robotdan What you're saying makes sense and I can understand why it's implemented that way. In my scenario, I'm trying to generate a deterministic and globally unique username in the reconcile lambda (e.g. using the Identity Provider's ID + the IdP's username). It sounds like I may have to find an alternate path to accomplish the goal.

Thanks as always for the prompt support!

**Comment by robotdan** [comment]
>  It sounds like I may have to find an alternate path to accomplish the goal.

If you want to be able to login with this value, yes.

One alternative method would be to use the lambda to build this unique value (IdP Id + Idp Username) and set it into user or registration data. Then using a webhook for the Change User or Change Registration event, we send the old and the new values. If the value for this unique username has changed or has been added, you could use the Update User API to set the `username`. 

Another option is for us to revisit this design point and possibly allow through configuration the option to set the `username` using a Reconcile Lambda with the big warning of "This is dangerous unless you can guarantee this username is unique".

**Comment by patrickvalle** [comment]
> Then using a webhook for the Change User or Change Registration event, we send the old and the new values. If the value for this unique username has changed or has been added, you could use the Update User API to set the username.

@robotdan I've just tested this out using the webhook events listed below. It appears as though on first login for SSO users, these webhooks all get fired off before the user has actually been committed to the database. This results in a `404` when I try to update the `username` via the  Update User API. I have the webhook transaction setting as "All the webhooks must succeed".

- `user.create`
- `user.registration.create`
- `user.login.success`

**Comment by robotdan** [comment]
You're correct. In the scenario where the webhook is required to succeed and it returns failure, we have to roll back the transaction. 

Are you attempting to call the Update User API within the webhook request? In other words, which one of the following workflows are you doing:

1. `user.create` fires
2. You consume `user.create`
3. Call Update User API
4. Return `200` from webhook

Or 

1. `user.create` fires
2. You consume `user.create`
3. Return `200` from webhook
4. Call the Update User API

**Comment by patrickvalle** [comment]
@robotdan The first scenario- my intent is to ensure that all users have usernames by the time they are using my app.

**Comment by robotdan** [comment]
This is a reasonable point, but because each event type can optionally be configured to require the webhook to succeed, it is inside of a TX on our end. 

I'll have to think more about this, perhaps there is a better way for us to handle this scenario.

**Comment by patrickvalle** [comment]
@robotdan Thanks again for the support 🚀
