### ISSUE TITLE
Session cookie misses `Secure` attribute

### ISSUE THREAD

**Issue by JuliusPC** [FusionAuth/fusionauth-issues#705]
## Session cookie misses `Secure` attribute

![fusionauth-cookie](https://user-images.githubusercontent.com/15018932/85863724-da77a000-b7c3-11ea-9c2c-81aec17178ce.png)

### Description
Since it is safe to assume that nobody wants to use FusionAuth without HTTPS in production, the `Secure` attribute should be set.

**Comment by mooreds** [comment]
Interesting. When I'm running locally but behind apache serving over HTTPS, it is marked secure (because I'm connecting via AJP, I suppose).

<img width="297" alt="Screen Shot 2020-06-26 at 8 21 44 AM" src="https://user-images.githubusercontent.com/91825/85867420-1c81f100-b786-11ea-9ed9-c50aa78d3864.png">

What happens when you sign in via https://localhost:9013/ ? You'll get a self signed SSL cert error, but if you accept that and sign in, the `JSESSIONID` cookie is set to `secure`.

Is your suggestion that the cookie always be marked `secure`? I believe that would prohibit being able to log in over a non secure connection, which is sometimes useful in development contexts.

Or are you seeing the JSESSIONID cookie sent with `secure = false` even when fusionauth is behind a proxy which terminates SSL?

**Comment by robotdan** [comment]
The `Secure` attribute is true if you are using `https`. I'm assuming you're in development and running over `http`.

**Comment by JuliusPC** [comment]
Thank you for your replies!

> Or are you seeing the JSESSIONID cookie sent with `secure = false` even when fusionauth is behind a proxy which terminates SSL?

Yes. I forgot about the proxy.

> The `Secure` attribute is true if you are using `https`. I'm assuming you're in development and running over `http`.

No, but FusionAuth is behind a reverse proxy 🤦 and therefore "seeing" HTTP.

What is the recommended way to deal with this issue?

1. Proxying port 1013 and configure the reverse proxy to accept FusionAuth's self signed cert? ([Something like this.](https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/))
2. Proxying port 1011 and configuring FA to set the `secure`-Attribute anyway (if possible).
3. Use port 1011 Configure the proxy to change the attribute (seems like a dirty workaround).

**Comment by robotdan** [comment]
If you're behind a proxy providing TLS termination, your proxy should be adding the `X-Forwarded-Proto` header. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto

**Comment by JuliusPC** [comment]
> If you're behind a proxy providing TLS termination, your proxy should be adding the `X-Forwarded-Proto` header.

nginx does, but FusionAuth doesn't add the Attribute anyway. I solved the problem by proxying `https://127.0.0.1:9013` instead of 9011.

The JSESSIONID cookie is now marked as secure. The cookies fusionauth.wn (maybe to save the "What is new" state?) and fusionauth.locale are not. Not critical, but why bother handling those different?

**Comment by robotdan** [comment]
`fusionauth.wn` and `fusionauth.locale` are cookies written and utilized in JavaScript, we may be able to mark them as secure, but they are not sensitive.

**Comment by robotdan** [comment]
Closing. https://github.com/FusionAuth/fusionauth-issues/issues/1414 may address this issue.
