### ISSUE TITLE
[Feature] WebAuthn

### ISSUE THREAD

**Issue by tyduptyler13** [FusionAuth/fusionauth-issues#77]
### Problem
It would be convenient to authorize login via my phone or ubikey. It's faster and more secure than a password.

### Alternatives/workarounds
Use old school password authentication... psh

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1845
- https://github.com/FusionAuth/fusionauth-site/issues/1707

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
A possible native integration with https://www.hypr.com may satisfy this requirement.

**Comment by JuliusPC** [comment]
I would like to add some thoughts about WebAuthn. First, support by devices:

- Many users already unknowingly use a device capable of WebAuthn:
  - Devices with Android > 7 (and probably only with Google Play services installed)
  - recent Versions of Windows 10 and a computer with a TPM
- relatively inexpensive hardware tokens (starting from $20) are available (Google Titan, Yubikeys -- especially Solo Key and NitroKey are open hard- and software)
- [Current Browsers on all major platforms support WebAuthn](https://caniuse.com/#feat=webauthn) using one of above methods

-> try it on [webauthn.io](https://webauthn.io) (btw, the site mentions Java implementations)

Second, use cases:

1. Providing a **second factor** to secure sensitive accounts, requirements:
   - users are able to add one or more (as fallback in case one is lost) authentication devices 
   - possible recovery methods:
      - very long recovery codes provided to the user when he first adds a hardware token
      - in corporate environments it may be suitable to allow an admin to remove a lost hardware dongle by authentication the user in person
2. Provide a single **authentication method**:
   - much more secure than `$Password123` since the keys are not likely to be guessed due to random generation
   - password reuse not possible
   - secrets like passwords do not need to be transmitted over the wire
   - Phishing is not possible since the used keys are different on every domain
   - better user experience, since there is no need for memorizing or storing complex passwords. Just the need for one of the above mentioned devices and you simply have to push a button, provide a fingerprint or authorize with some kind of PIN in case you want to authenticate.
   - fallback provided by email address or one of the methods mentioned in the previous use case

**Comment by mooreds** [comment]
See also https://webkit.org/blog/11312/meet-face-id-and-touch-id-for-the-web/

**Comment by mooreds** [comment]
This looks like it might be useful as well: https://github.com/Yubico/java-webauthn-server

**Comment by feraudet** [comment]
Hey,
Will we have the chance WebAuthn this year ? Each time a client ask for it I'm forced to implement another solution

**Comment by mooreds** [comment]
@feraudet Thanks for asking!

It's currently in plan for 1.38: https://github.com/FusionAuth/fusionauth-issues/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.38.0 though things do shift around.

In the interests of transparency, the current thinking is to have it be a paid feature and not in the Community edition.

Here's our general roadmap guidance: https://fusionauth.io/docs/v1/tech/core-concepts/roadmap and you're always welcome to examine our milestones to get insight into our near term work.

**Comment by feraudet** [comment]
Thank you for responding quickly.
No problem to pay for. Need saas anyway.

> @feraudet Thanks for asking!
> 
> It's currently in plan for 1.38: https://github.com/FusionAuth/fusionauth-issues/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.38.0 though things do shift around.
> 
> In the interests of transparency, the current thinking is to have it be a paid feature and not in the Community edition.
> 
> Here's our general roadmap guidance: https://fusionauth.io/docs/v1/tech/core-concepts/roadmap and you're always welcome to examine our milestones to get insight into our near term work.
