### ISSUE TITLE
Two Factor Challenge: Cleanup code on failure

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#775]
### Description

Currently, if we submit the wrong two factor challenge verification code, we have an error and the code is still present on an input.

![image](https://user-images.githubusercontent.com/1698357/88544636-ff0ca500-d019-11ea-87e3-d2bd1f5cfa01.png)

It's more usual to have the form cleaned up on that case.

A two factor code is always very short (4 to 6 digits max).

It is easier to type (or copy paste) it again than dig across the text input to fix the code.

I am not sure I can do anything myself to achieve that as it's depends to the backend code.

**Comment by robotdan** [comment]
This is our standard form validation handling. Perhaps this is an outlier, but in most cases we want to show the user input so they can correct it. 

Because the themes are modifiable, if you would like, you can clear the input using JavaScript or modify the template to set the value to empty when a field error is displayed.
