### ISSUE TITLE
Definition for minimal hardware requirements

### ISSUE THREAD

**Issue by jsanta** [FusionAuth/fusionauth-issues#78]
### Problem
I'm trying to deploy FusionAuth on the smallest Linode machine (1 CPU, 1Gb RAM). I tried using the docker installation and the zip installation. Docker gets the CPU and RAM to 90% (and more), regardless any configuration I try. The zip installation stands running a little more (about 30 minutes) without blowing the CPU and memory usage, but I had to set all memory limits from 256M to 128M.

### Solution
Documentation should include the minimal recommended hardware requirements to get FusionAuth working without problems.

### Additional context
The Linode machine I'm using is an Ubuntu 18.04 and has only a Nginx server, used to forward auth requests to port 9011. No other software running.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by paustint** [comment]
I am having memory issues at well. I have the env var set to 512MB and my instance is crashing every hour or so. I have 0 logins and am not using the system while this is occuring and used the Docker deployment.

I am using Render.com to host my service and the metrics show that the memory usage slowly increases then has a huge spike for seemingly no reason.

I have increased my server capacity from 512mb to 1gb to see if this will avoid this issue and will try to decrease the env var if the problem persists.

It sort of feels like a memory leak, but not really sure.

**Comment by robotdan** [comment]
@paustint 512 should be adequate. Can you describe your config? Total user count, tenant count , lambda count, etc. Version of FusionAuth, search type, DB type.

**Comment by paustint** [comment]
@robotdan - I just got FusionAuth setup for the very first time over the weekend for a system where we do not yet have any users.

**Here is my configuration**:
1. production mode
1. 2 users
1. 1 tenant
1. ran 1.71.0 database scripts, so I have the templates/lamdas that came with this but nothing extra so far
1. one application
1. database search
1. postgres - I am using a hosted database solution, so I am required to run production mode because I do not have superuser privileges

**Here are the problems I am seeing**:
1. There are large spikes in memory occasionally
1. In the logs, the server seems to restart very frequently, I see `Starting FusionAuth version [1.17.0]` regularly show up in the logs


![image](https://user-images.githubusercontent.com/5461649/84665456-17e35000-aedd-11ea-85a6-a308c2e0b2eb.png)

**Comment by robotdan** [comment]
We don't restart ourselves, so I'm assuming this is due to a threshold configured in k8s or whatever container manager you're using?

**Comment by davimello28** [comment]
I also experienced the same happening, even with a full set of spects on the container (`memory`, `memory-swap`), in both container and Swarm modes.

It's important to notice that java itself bypasses any limitations imposed by the container, since JVM isn't aware of the containers limitation (and containers do not run it's own OS to enforce isolation). Even with namespaces correctly inserted, the problem remains. 

[Nobody puts Java in a container](https://vimeo.com/181900266)
[Java inside docker: What you must know to not FAIL](https://developers.redhat.com/blog/2017/03/14/java-inside-docker/l)

I was validating FusionAuth to implement it's service as part of a company, but I'm planning to move away now.

**Comment by mooreds** [comment]
Just updated the comment to correct the url for the second link, @davimello28 . Thanks for the links.

Have you set the memory limits via environment variables as per https://fusionauth.io/docs/v1/tech/reference/configuration and https://fusionauth.io/docs/v1/tech/installation-guide/system-requirements

I'd be interested in hearing more about the specs of your system and the behavior you are seeing, @davimello28 .

**Comment by robotdan** [comment]
Closing, we have hardware system requirements posted in the link @mooreds referenced. If we are missing any additional details please feel free to re-open or open a new issue some any specifics we are missing.
