### ISSUE TITLE
Does fusionAuth support golang??

### ISSUE THREAD

**Issue by kalprem** [FusionAuth/fusionauth-issues#79]
### Request
Build a Go client library for FusionAuth.
https://golang.org/

### Bounty
This issue qualifies for the FusionAuth bounty program. If you can get a Go client library working, provide a stub and we can build the rest with out template system, see comment below.
https://fusionauth.io/write-for-fusionauth

If you are interested, please contact us using the link provided above and let us know.

**Comment by robotdan** [comment]
We do not currently have a `go` client library. Are you interested in contributing to help us build one? 

We build our client libraries using a template, so we only need to get a few basic examples to extrapolate that into a full client. If you wan to take a look at one of the templates such as `typescript.client.ftl` and if you want to build one of those in `go` we may be able to build the whole thing. 

For example these clients are built using these templates:

https://github.com/FusionAuth/fusionauth-typescript-client
https://github.com/FusionAuth/fusionauth-java-client/blob/master/src/main/client/typescript.client.ftl

https://github.com/FusionAuth/fusionauth-php-client
https://github.com/FusionAuth/fusionauth-java-client/blob/master/src/main/client/php.client.ftl

https://github.com/FusionAuth/fusionauth-ruby-client
https://github.com/FusionAuth/fusionauth-java-client/blob/master/src/main/client/ruby.client.ftl

https://github.com/FusionAuth/fusionauth-python-client
https://github.com/FusionAuth/fusionauth-java-client/blob/master/src/main/client/python.client.ftl

**Comment by medhir** [comment]
Hey @robotdan, I'd like to help out with this if possible. Is there any context that would be helpful on understanding the `.ftl` files?

**Comment by robotdan** [comment]
Hi @medhir - this is great. 

Currently it isn't real easy for me to get you setup to build the client from the template, so it may best if you just build the client w/out the template and I help back it into the template once we get the syntax down. 

The templates are built using our JSON DSL, you can see each API here: https://github.com/FusionAuth/fusionauth-java-client/tree/master/src/main/api 

In most of the libraries we have so far we have built our own REST client to keep our dependencies down. Depending upon how heavy it would be to build a REST client in Go from their [http](https://golang.org/pkg/net/http/) object you could just use something off the shelf as well. (ideally something with minimum deps and well maintained)

So my suggestion would be to take one of the existing clients, such as [ruby](https://github.com/FusionAuth/fusionauth-ruby-client/blob/master/lib/fusionauth/fusionauth_client.rb) and delete all of the API methods except for `retrieve_user`, `create_user`, and `delete_user`, so this will leave you with the constructor and the `start` method.  Go-if-fy that code - plug in a workable REST client or build one. 

You could write a sanity test to make sure those work against FusionAuth, and then I can help you build the template from there. I'll stubbed out a new GitHub project so you have something to submit a PR against. https://github.com/FusionAuth/fusionauth-go-client

Find the `Chat with Users` button on the [FusionAuth](https://fusionauth.io/) home page and that will get you added to our Slack channel, this may be helpful while you're building this out.

**Comment by medhir** [comment]
Cool, thanks for the guidance. I think Go's standard library should be able to do most of the heavy-lifting... I'll get going on this and see how far I get! Cheers.

**Comment by medhir** [comment]
Hey @robotdan, some updates... I'm about 90% complete on effort, would be good to get your feedback on using the `.ftl` template syntax. Currently, I've [added a template](https://github.com/medhir/fusionauth-client-builder/blob/master/src/main/client/go.client.ftl) and made a [few updates to the macros](https://github.com/medhir/fusionauth-client-builder/commit/8b0f0ac7340411c830d1515c4295722a3ddb0ed9) in the client builder. [The output](https://github.com/medhir/fusionauth-go-client/blob/773a92719a779409c11d7e147a73135533e57434/FusionAuthClientTest.go) had some build errors that I [fixed in this commit](https://github.com/medhir/fusionauth-go-client/commit/773a92719a779409c11d7e147a73135533e57434), am wondering how to translate those fixes into the template syntax. 

More specifically: is there a way to check against the query param type? For string slices (arrays), I'd like to do [something like this](https://github.com/medhir/fusionauth-go-client/commit/773a92719a779409c11d7e147a73135533e57434#diff-ac194eea449b9cb4f59abc1352cb36b6R357), `bool` values [have to be converted](https://github.com/medhir/fusionauth-go-client/commit/773a92719a779409c11d7e147a73135533e57434#diff-ac194eea449b9cb4f59abc1352cb36b6R377). Also wondering if I can declare `q := req.URL.Query()` just once before encoding (potentially many) query params. 

Let me know what you think... will try and add a testing suite soon. Did verify the initial stub was able to communicate with the API, but need to run some more thorough tests in the coming days once the template is fully baked. 

Cheers, 
Medhir

**Comment by robotdan** [comment]
Hi @medhir sorry for the delay, swamped. Things are looking good! 

Do you still need some assistance? 

In this [commit](https://github.com/medhir/fusionauth-go-client/commit/773a92719a779409c11d7e147a73135533e57434) it looks like you are manually removing `q := req.URL.Query()` from the built output?

> Also wondering if I can declare `q := req.URL.Query()` just once before encoding (potentially many) query params.

Not sure I understand. If you can do it in Go, then we should be able to do it in the template. 


> `bool` values have to be converted. 

```
${global.convertValue(param, "go")}
```

And the `convertValue` function in the `_macros.ftl` file will have something like this. (this may not work, but should be close?)

```
 [#elseif param.type == "boolean" || param.type == "Boolean"]
strconv.FormatBool(true))
      [#if param.value?? && param.value == "true"]
        [#return "strconv.FormatBool(true)"/]
      [#elseif param.value?? && param.value == "false"]
        [#return "strconv.FormatBool(false)"/]
      [/#if]
``


Let me know what else I can help with. Since I don't know Go, the easiest way for me to help will be if you give me what you want the output of the template to look like, compared to what you're seeing and I can help with the template parts. 

Thanks for your help!

**Comment by roychowdhuryrohit-dev** [comment]
Since Go is very popular in backend development, a subsequent open source Go client library will be much appreciated. I have been searching for a good and reasonably priced AaaS and FusionAuth is one of them. Okta has great golang support but it's serverless and doesn't come cheap.

**Comment by medhir** [comment]
Hey @robotdan. I managed to get the template output to build correctly. Have been able to use the client to integrate FusionAuth into my Go app. PRs open for both the [client builder](https://github.com/FusionAuth/fusionauth-client-builder/pull/1) and the [Go client repository](https://github.com/FusionAuth/fusionauth-go-client/pull/4). Let me know what you think!

**Comment by robotdan** [comment]
This is great @medhir , I'll try to take a look today.

**Comment by robotdan** [comment]
Initial support for Go is available. Thanks to @medhir for the hard work!
https://github.com/FusionAuth/fusionauth-go-client

Have at it, and submit issues or PR if you find any issues. 

As a side note, we're working towards a system that will let us build the domain out for libraries such as Go.
