### ISSUE TITLE
OAuth refresh tokens

### ISSUE THREAD

**Issue by Garogat** [FusionAuth/fusionauth-issues#81]
### Description
I am using the `offline_access` scope to request a refresh_token. I am sometimes getting a refresh_token back sometimes I am not. As I saw in your docs, I need to provide a field called `device` to the  authorization code Grant ednpoint? Why do you need this `device` id, is it a part of the official specification or just a way of your implementation?

**Comment by robotdan** [comment]
Hi @Garogat 

Yes, we will ignore the scope request for `offline_access` unless a `device` parameter is also required.  I'm assuming you're using the Resource Owner Credential grant? 

We consider a Refresh Token to be unique by `User`, `Application` and `Device`, this is not explicitly part of the specification, but much of the implementation is left open to interpretation and it seems to be implied in different places that a refresh token should be scoped to an application and a device. 

So these three data points are the rationale for this additional input on the request. 

- `loginId` :  `User`
- `client_id` : `Application`
- `device` : `Device`

With these input values we can return a refresh token for a particular device for authorization to a specific application. 

In addition, one of the counter measures identified in RFC 6819 in section 3.3 (https://tools.ietf.org/html/rfc6819#section-3.3 ) 

-`    o  Combine refresh token request with device identification (Section 5.2.2.5)`

```
5.2.2.5.  Device Identification

   The authorization server may require the binding of authentication
   credentials to a device identifier.  The International Mobile Station
   Equipment Identity [IMEI] is one example of such an identifier; there
   are also operating system-specific identifiers.  The authorization
   server could include such an identifier when authenticating user
   credentials in order to detect token theft from a particular device.

   Note: Any implementation should consider potential privacy
   implications of using device identifiers.

```

This strategy allows us to limit the number of refresh tokens we generate, for example when you log in using our OAuth frontend, we generate a unique Id (using Fingerprintjs) that we pass along as the `device` parameter so that we only generate a single refresh token for this browser (device).

If you also provide some optional metadata, it helps an administrator understand what device a particular refresh token is used. I compare it to when you log into your Netflix account and see `Daniel's iPad` as a connected device, this is helpful because you can see the name of the device and when it was last accessed so you can decide when and if to revoke that token. 

Is there a use case where you cannot or would rather not send a unique device identifier?

**Comment by Garogat** [comment]
> The device parameter is no longer required on the Login API or the Authorized endpoint in order to receive a Refresh Token. If the device parameter is provided it will be ignored.

Seems like you found another way of implementing the `device` identification in >1.5.0?!

I like your idea of providing a human readable device name / description by adding `metaData.device.description`.

**Comment by robotdan** [comment]
> Seems like you found another way of implementing the device identification in >1.5.0?!

Sort of, we talked it through a few times and convinced ourselves that it wasn't really adding any additional security and was mostly just a PITA for devs. :-) 

We've previously had the `metaData.device.name`, `metaData.device.type`, and  `metaData.device.description` but I found they were missing from the doc for the Authorization request. 

The `name` and `type` are currently set on your behalf if you're using our Authorization grant on the OAuth login. We set that in JavaScript.

**Comment by Garogat** [comment]
> The name and type are currently set on your behalf if you're using our Authorization grant on the OAuth login. We set that in JavaScript.

Letting JavaScript set the name and type is fine with my integrations.

After removing `device` I can now use most of my oauth supporting software, that was having trouble with special fields before.

**Comment by robotdan** [comment]
Awesome, glad that was helpful. Keep up all of the great feedback!
