### ISSUE TITLE
Automating the API Key generation

### ISSUE THREAD

**Issue by LohithBlaze** [FusionAuth/fusionauth-issues#819]
### Problem
We are automating most of the configurations done with fusionauth writing api to configure most of them. But for library to contact fusionauth, we need an api key to be generated and I saw in the documentation that the API key creation is not provided through Rest APIs. Is there any script that I can refer to or any way I can generate the API key automactically.

### Solution
A way to get API key generated.

### Alternatives/workarounds
No workaround,  only way is to create it through UI

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by LohithBlaze** [comment]
Is there a way to get access to admin apis

**Comment by LohithBlaze** [comment]
Saw the kickstart documentation,  I think it solves what I'm trying to do thanks!

**Comment by Tintwo** [comment]
Sorry to reply to this closed issue, but it seems to match with my request :
How can we create a new APIKEY (scoped to a tenant we created by API) using the API ? We already have running FA environments and managing tenants dynamically and we can't use the kickstarter workaround to automate APIKEY creation (we can't use the UI because of automation)
Regards
