### ISSUE TITLE
Login report - error message + PHP SDK doc

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#84]
## (Put bug title here)
With this query I get:

<img width="1005" alt="screen shot 2019-02-18 at 10 40 32 am" src="https://user-images.githubusercontent.com/1580512/52932816-768cce00-336a-11e9-8cb2-350cdafafa9c.png">

Because `start` and `end` are missing... First could we have a better message and not a 500 error code?

Also the API `/api/report/user-login` defined in the PHP SDK

<img width="620" alt="screen shot 2019-02-18 at 10 46 53 am" src="https://user-images.githubusercontent.com/1580512/52932883-beabf080-336a-11e9-94b1-9ff51dac4989.png">

does not exist in the API? Im getting a 404 and I do not find anything in the documentation, did you remove it?

**Comment by blanchonvincent** [comment]
Also, the SDK does not support the `user` parameter:

<img width="573" alt="screen shot 2019-02-18 at 10 48 17 am" src="https://user-images.githubusercontent.com/1580512/52932932-f6b33380-336a-11e9-9b6e-cc6660758a30.png">

while the doc does:

<img width="965" alt="screen shot 2019-02-18 at 10 48 53 am" src="https://user-images.githubusercontent.com/1580512/52932941-ffa40500-336a-11e9-8f54-8fde4ae9399b.png">

**Comment by robotdan** [comment]
Hi @blanchonvincent 

I apologize for the confusion. The `/api/report/user-login` was sort of an anomaly and was un-documented and because it wasn't really a report, it was moved. 

The recent logins is now a documented API ([/api/user/recent-login](https://fusionauth.io/docs/v1/tech/apis/users#retrieve-recent-logins)) , and can be found in the client library with these methods:

- `retrieveUserRecentLogins`
- `retrieveRecentLogins`

The Login report will now take a `userId` or `loginId` as a request parameter, they are separated out into three different method signatures: 

- `retrieveLoginReport`
- `retrieveUserLoginReport`
- `retrieveUserLoginReportByLoginId`

If you don't see these methods, ensure you've pulled the latest `1.4.0` version of the library. 
https://packagist.org/packages/fusionauth/fusionauth-client

Regarding the `500` error message, I'll take a look at that one, you should always receive a `400` with a JSON response body for parameter validation. Thanks for letting us know.

**Comment by robotdan** [comment]
Regarding the `500` status code, this will be corrected in the next release. Here is the response you should have received with a `400` status code:

```
{
  "fieldErrors" : {
    "end" : [ {
      "code" : "[missing]end",
      "message" : "You must specify the [end] property."
    } ],
    "start" : [ {
      "code" : "[missing]start",
      "message" : "You must specify the [start] property."
    } ]
  }
}
```
