### ISSUE TITLE
Out-of-date Linux packages listed on download page

### ISSUE THREAD

**Issue by JuliusPC** [FusionAuth/fusionauth-issues#853]
### Description
The most recent release on the [download page](https://fusionauth.io/direct-download) is 1.17.4. According to the [release notes](https://fusionauth.io/docs/v1/tech/release-notes) the most recent is 1.19.2.

Copying the link <https://files.fusionauth.io/products/fusionauth/1.17.4/fusionauth-app_1.17.4-1_all.deb> and changing some digits works: <https://files.fusionauth.io/products/fusionauth/1.19.2/fusionauth-app_1.19.2-1_all.deb>  
So it seems that only the links that are broken.

**Comment by JuliusPC** [comment]
It works now...

**Comment by robotdan** [comment]
Good to hear it is working! 

I think the issue is that that page caches the downloaded versions in local storage. Then on page load, an AJAX task fetches the latest versions and rebuilds the version listing. 

It is possible for the update to be slightly delayed, and when that is the case, the initial render of the page will have the versions available the last time you visited the page.

**Comment by JuliusPC** [comment]
I finally found out what happened:

I use uMatrix to block third party requests per default. Some time ago, I temporarily allowed requests to third party resources (namely <https://license.inversoft.com/api/fusionauth/version>), because the page did not work. Therefore, the old versions document was cached in local storage. After that, uMatrix again blocked requests to third party resources,  from that point on I saw a two months old version of the page.  
I thought I had verified it in another browser 🙃.

I know that this is a rare edge case, but maybe you should consider adding a timestamp to the local storage to invalidate it in any case.
