### ISSUE TITLE
FusionAuth not persisting db configuration 

### ISSUE THREAD

**Issue by davidmw** [FusionAuth/fusionauth-issues#94]
### Description
We are attempting to deploy FusionAuth on Azure and would like to use Azure's managed PostgreSQL server as the database so it can be scaled independently of the VM node that FusionAuth is on.

As this is a managed service we don't have superuser access on the database. We've created a user manually with (seemingly) sufficient rights / roles and can get past the db connection setup screen and access the FusionAuth dashboard.

However the database config is not persisting if the FusionAuth instance is restarted - resulting in the configuration screen again.  Is there any configuration or env variables we need to keep in mind during every deployment of FusionAuth?

Thanks!

David

**Comment by robotdan** [comment]
How are you deploying to Azure? Docker, k8s, or a VM using a package such as the zip, Debian or RPM?

The DB configuration that you setup during maintenance mode will be saved to the FusionAuth configuration. 
https://fusionauth.io/docs/v1/tech/reference/configuration

Can your confirm that file has the correct configuration and is persisted across a restart?

I'm assuming from your description that you did get past the maintenance mode DB configuration? Did you just enter the same credentials for the super user section as well as the FusionAuth section?

Thanks this feedback will help is improve the setup process for many different deployment options.

**Comment by prabhakarreddy1234** [comment]
@robotdan I am part of the same team. We used k8s (AKS) to deploy to azure. We didn't use db deployment through k8s but we used Azure managed Postgres db.  We tried below options

1. We configured `database_url`, `database_root_user`, `database_password` environment variables for fusionauth container. After the deployment, it took us to silent configuration page with `Silent configuration failed`. Attached is the screenshot. 
![image](https://user-images.githubusercontent.com/1984707/54884830-5e2e3880-4e6d-11e9-8dec-7a500544305a.png)

2. We removed `database_url` env variable to see the database configuration page. After deployment it took us to `database configuration page`. Super user for Azure managed postgres server would be accessed/managed by Azure only. We wouldn't have access to that user. So i followed `fustion auth database advanced settings` to create database, user and assign required privileges to that user. In the database configuration page we entered manually created `super user or root user` details and `ordinary  user` details. It worked and took us to account creation and then to dashboard. But after few hours we again deployed same fusionauth-deployment.yaml. Deployment successful but it took us to database configuration page again and this time the same `super user or root user` and `ordinary user` credentials didn't work.

**Comment by robotdan** [comment]
Ok, in your case since you are running in AKS, if you are setting the environment variables, you should need to persist the config file in `/usr/local/fusionauth/config`.

Now that the schema is created, you should be able to set the following environment variables:
(others defined here : https://fusionauth.io/docs/v1/tech/installation-guide/docker)

- `DATABASE_URL`
- `DATABASE_USER`
- `DATABASE_PASSWORD`
- `FUSIONAUTH_SEARCH_SERVERS`

You can omit the `DATABASE_ROOT_USER` and `DATABASE_ROOT_PASSWORD` since the schema will already exist.  I think should allow you to deploy another node and have it correctly connect to the database. Let me know if you run into issues. 

We have had a few other users run into these types of db configuration issues on managed db services where there is not access to a root user. We will be enhancing our maintenance mode to better accommodate your configuration.

Also, if you will be running more than one node in your AKS configuration, you will ideally also set the `FUSIONAUTH_URL` environment variable. The value of this variable should be a URL that is addressable by each node. Currently this value is used by FusionAuth nodes to let other nodes know of Cache reload events, etc. If you do not have this value set, the configuration will still function, but cache reloads may be delayed slightly between nodes. This will only affect configuration changes, such as Application configuration changes.

**Comment by robotdan** [comment]
Closing, issue #95 will be used to track enhancements.
