### ISSUE TITLE
Add an API to manage the FusionAuth license

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#949]
### Problem
Currently you can only activate the FusionAuth Reactor license using Kickstart or through the admin UI. 

There may be a use case where you want to remote activate this using an API. 

### Solution
Add an API to activate and de-activate (decommission) the FusionAuth Reactor (license) using an API. 

This will need some thought to see if there is a valid use case for this, and if there are any security concerns with offering this API. 

### Alternatives/workarounds
Use Kickstart, or the UI. 

### Additional context
N/A

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by seanadkinson** [comment]
Thanks @robotdan.  Our use case is that we have each of our engineers running their own version of fusionauth via docker, as well as a version running in each of our environments (dev, qa, prod, etfc), and want to promulgate the License ID to all those instances without manual intervention.

We have a separate service that manages fusionauth configuration, so that on startup of that service, we configure email templates, theme files, lambdas, webhooks, CORS, etc.  This allows us to commit/track changes to this configuration, and automatically configure fusionauth in each environment as they pull those updates.  With the addition of a Generic Connector to this configuration, we need to have a proper License ID before this configuration can be applied on startup.  This unfortunately causes the service to not be able to startup, since FusionAuth returns an error if the License ID is not set when trying to add a Generic Connector.

Before I merge this Generic Connector code then, I'd need all users/environments to configure the License ID manually.  What I'd like to do instead, is configure the License ID as part of this service's startup configuration, so that it's applied automatically, and even if it changes going forward, it automatically gets updated.

**Comment by robotdan** [comment]
Thanks @seanadkinson and in this use case The KickStart option is not sufficient, and and API would solve it for you?

**Comment by seanadkinson** [comment]
Kickstart would’ve worked if i setup the license ID initially in our kickstart file, but now we have dozens of environments that we need to patch, so an API endpoint would avoid the need to do this manually, since we have a mechanism to configure fusion auth updates using its API automatically when new code is pulled.

**Comment by robotdan** [comment]
This should now be available using the Reactor API. 
https://fusionauth.io/docs/v1/tech/apis/reactor/


Please re-open if we are missing any capability.
